### ISSUE TITLE
Support for live preview

### ISSUE THREAD

**Issue by isle9** [mProjectsCode/obsidian-meta-bind-plugin#10]
Any plans for live preview?

**Comment by mProjectsCode** [comment]
Markdown post processors for inline code blocks are not supported in live preview. 

So I added code blocks that need to be prefixed with `meta-bind`, so like this:

```meta-bind
INPUT[text_area(class(meta-bind-full-width), class(meta-bind-high)):meta bind/test2#title]
```

**Comment by isle9** [comment]
Unfortunately, this doesn't seem to be working for me.

**Comment by mProjectsCode** [comment]
It is not in the latest release yet

**Comment by mProjectsCode** [comment]
And now it is
