### ISSUE TITLE
More Dataview support for Suggester

### ISSUE THREAD

**Issue by terrychenzw** [mProjectsCode/obsidian-meta-bind-plugin#103]
I really appreciate your genius work for creating this amazing plugin.

I love to use it with Dataview. So i would like to request 2 more features about Suggester:
1. **Support complex query**. Now suggester can only support dataview data source query. it will be great if it support complex query like where(), sort() and so on.
2. **Support more fields to show**. Now Suggester can only show the file name. i expect that it can show like this:  file.name, created time, other_frontmatter_fields

Again, thanks a lot.

**Comment by mProjectsCode** [comment]
I won't be doing this as part of the input field declaration syntax, but this will be possible with the JS API that I am currently working on.

**Comment by mProjectsCode** [comment]
The API is finalized and will be part of the next release.

**Comment by terrychenzw** [comment]
Are there any documentations about how to use the JS API you mentioned?

**Comment by mProjectsCode** [comment]
Not yet, but i am working on it

**Comment by mProjectsCode** [comment]
You can take a look at the `src/api` folder
