### ISSUE TITLE
[Help] Pulling list automatically for metadata binding

### ISSUE THREAD

**Issue by mentosweet** [mProjectsCode/obsidian-meta-bind-plugin#105]
Hi, 

I would like to have a multi-select from a list of items that could increase overtime. Instead of manually keying in option(XXXX), option(YYYY)... etc, is there a way to pull it from a central list that i can continue to add on over time and it automatically provides it as a metadata selection?

Thanks!

**Comment by mProjectsCode** [comment]
You can create a template in the plugin settings for this.

**Comment by mProjectsCode** [comment]
https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/templates

**Comment by mentosweet** [comment]
Thanks for the assistance!

I am currently using this template. Perhaps on a way for this template inputs to extract options from another file? I am currently typing in newer options as the list of options increases.

**Comment by mProjectsCode** [comment]
No. But things like that will be possible once I finish the JS API for the pluign.
