### ISSUE TITLE
Null option for date_picker

### ISSUE THREAD

**Issue by Spiralo-Idioide** [mProjectsCode/obsidian-meta-bind-plugin#106]
**Is your feature request related to a problem? Please describe.**

I want to use the date_picker to track the date of Movies I watch and books I read. I create notes for books/movies before I read/watch them. 
The problem is that there is no 'null' option with the date_picker, it will always fil the metadata even when I don't touch it. 

**Describe the solution you'd like**
Some way to set a null option with the date_picker

**Comment by dxcore35** [comment]
We need this. Null can be empty value too!

**Comment by mProjectsCode** [comment]
I implemented it, but allowing `null` as a value breaks some other input fields, so there is more to be done before i can release this.

**Comment by mProjectsCode** [comment]
took me some time but this should be done and release ready now in 5279544dfb543b5a59f9dd062674dd07e43ab3ea
