### ISSUE TITLE
Add dataview query inside the field

### ISSUE THREAD

**Issue by dxcore35** [mProjectsCode/obsidian-meta-bind-plugin#107]
I would like to type something like:

INPUT[suggester(`dv.pages().where(b => b.class === 'needs').sort(b => b.date_created, "asc"`)):needs]` 

---

This suggester should be filled with filenames coming from this dataview query.

# Here is the very tiresome work around with dataviewJS:

```dataviewjs

const setFilter = "" ;
let filter = "Need | "
const pages = dv.pages().where(b => b.class === 'needs').sort(b => b.date_created, "asc")
let list = []

for (let items of pages) {
	list.push('option(' + items.file.name + ')')
}


// This is the Mermaid configuration.
const codeblock = "INPUT[suggester(";
const backticks = "`";

await dv.paragraph(
  `${filter}${backticks}${codeblock}
  ${list}):needs]
  ${backticks} 
  `);
```

But there is a glitch, for good few seconds I see this:

![Screenshot 2023-07-06 at 13 30 09](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/7279156/f0427741-69df-4966-8ccb-b81fe3318611)

Before the select button renders correctly.

**Comment by mProjectsCode** [comment]
https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues/103

**Comment by dxcore35** [comment]
It doesn't explain why there is a glitch I mentioned above, that for good few seconds before the meta-bind button is generated there is just text.

**Comment by mProjectsCode** [comment]
it seems like the parser has some strange problem with the line breaks in the input field declaration.
Try changing your last line to 
```js

await dv.paragraph( `${filter}${backticks}${codeblock}${list}):needs]${backticks}`);
```

**Comment by mProjectsCode** [comment]
Correction, it seems like dataview is doing some fancy predictive rendering and reactive evaluation of the querry, which reevaluates the script and potentially breaks the input fields

**Comment by mProjectsCode** [comment]
This is something that dataview does and i have no influence over it, so i can't fix it.

**Comment by dxcore35** [comment]
For example im generating with dataviewJS:
- mermaid diagrams
- heatmaps

Non of those generate first text and then the GUI. So I think there is something in meta-bind plugin that is doing it. Please check.

**Comment by mProjectsCode** [comment]
Closing this for now. In the next release, you will be able to build the input field using js.
