### ISSUE TITLE
Add existing files via [[]] links not just strings

### ISSUE THREAD

**Issue by dxcore35** [mProjectsCode/obsidian-meta-bind-plugin#108]
I would like to link the existing not as metadata. Meaning I would like to add for example:

`INPUT[suggester(option([[low]]), option([[medium]]), option([[high]])):frequency]`

I would expect the plugin will add:

frequency: [[medium]].

Now the plugin has some internal issue with handling of the [[ ]]

**Comment by mProjectsCode** [comment]
the only error i can repo with this setup is, that the value shown on the suggester is not updated

**Comment by mProjectsCode** [comment]
i fixed that issue, the suggester should update now
