### ISSUE TITLE
Support for templates

### ISSUE THREAD

**Issue by isle9** [mProjectsCode/obsidian-meta-bind-plugin#11]
**Is your feature request related to a problem? Please describe.**
If you're planning on having identical code blocks in all your notes, for instance, you're going to need to do a lot of refactoring every time you want to change anything.

**Describe the solution you'd like**
A solution for this is to implement templates in some way. The simples way to do this is just to allow us to define templates in the settings and then to reference them in some way in our code blocks.

**Comment by mProjectsCode** [comment]
Yes.

I was thinking about `INPUT[template(template_name):bind_target]` or `INPUT_TEMPLATE(template_name)` and then you define the bind target in the template.

**Comment by mProjectsCode** [comment]
Templates are the next thing on my list (so release `0.2.1` or `0.2.2`, if I find a more important bug)
