### ISSUE TITLE
Add optional step argument for slider, etc.

### ISSUE THREAD

**Issue by utopicchaotica** [mProjectsCode/obsidian-meta-bind-plugin#110]
**Is your feature request related to a problem? Please describe.**
For some number inputs, it's more user-friendly to have steps (number intervals) instead of just increasing/decreasing by 1, e.g. it makes more sense when you're dividing a cookie recipe that originally makes 12 by 2, 4, or 6.

**Describe the solution you'd like**
Be able to add steps(#) as an input argument. Looks like it's already in the generated HTML as step="1"

**Additional context**
N/A

**Comment by mProjectsCode** [comment]
TODO: add the step size to the progress bar as well

**Comment by mProjectsCode** [comment]
released as part of `0.7.0`
