### ISSUE TITLE
Allow for title argument in inlineSelect

### ISSUE THREAD

**Issue by anpalcactus** [mProjectsCode/obsidian-meta-bind-plugin#112]
**Is your feature request related to a problem? Please describe.**
As of now, title doesn’t look to do anything with inlineSelect. 

**Describe the solution you'd like**
I think it would be great if title would show in inlineSelect by default, when there’s no option selected.
Could be also shown as grayed-out option on the top of dropdown list

**Additional context**
```
`INPUT[inlineSelect(title(Баланс), option(⭐️), option(⭐️⭐️), option(⭐️⭐️⭐️), option(⭐️⭐️⭐️⭐️), option(⭐️⭐️⭐️⭐️⭐️)):Баланс]`
 ```

INACTIVE STATE
Current
![IMG_0071](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/61033274/afe5d7cc-d90f-4271-a653-9e36cef465ba)

Intended
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/61033274/3a4e538a-c707-426f-9e3d-e73489deeabe)

ACTIVE State
Current
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/61033274/e6601c09-74c6-4058-8869-4cf86af6c012)

Intended
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/61033274/fb804e5e-a6fc-4dbc-b249-9b618069ecd0)

Thank you for your attention!

**Comment by mProjectsCode** [comment]
That is not possible, since i am using obsidians select prefab, which does not allow for a placeholder string.
