### ISSUE TITLE
Multiselect: Items in horizontal list

### ISSUE THREAD

**Issue by ykorzikowski** [mProjectsCode/obsidian-meta-bind-plugin#113]
Currently, multiselect looks like this: 

<img width="845" alt="Screenshot 2023-09-10 at 12 47 30" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/20556547/16195042-3411-4031-8910-75d115e94269">

Would be nice, if all can be in one line like: 

<img width="594" alt="Screenshot 2023-09-10 at 12 47 53" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/20556547/36700d0c-ec54-437f-9505-5a7b054cc912">

**Comment by mProjectsCode** [comment]
added in b0ad160
