### ISSUE TITLE
Bug: Parse Failure with two-word field

### ISSUE THREAD

**Issue by thecookiemomma** [mProjectsCode/obsidian-meta-bind-plugin#114]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
Parse Failure: 

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/15720918/c2ac0db7-778b-4ad4-b61a-afd916f5aab5)

**To Reproduce**

Create a metabind toggle field.  Include a field with more than one word with a space in the name, such as Bible Reading.  
**Expected behavior**
Previous versions, the input accepted the two-word field without an error.

**Screenshots**
Incl above. 

**Occurs on**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.6.1

**Additional context**

**Comment by mProjectsCode** [comment]
Oops. Will fix

**Comment by thecookiemomma** [comment]
thank you, that works. I don't mind adding the extra, just needed to know. Thanks!
