### ISSUE TITLE
Inline Select: Type Mismatch with Properties

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [mProjectsCode/obsidian-meta-bind-plugin#115]
-   [X] The Plugin is up to date
-   [X] Obsidian is up to date

**Describe the bug**
I have an InlineSelect field that works. The properties is changed when the InlineField is changed. However Properties reports it as a Type Mismatch and this causes any calculations that use that field to fail. 

**Select Travel Speed:** `INPUT[inlineSelect(option(0.666667), option(1.0), option(1.333333), showcase):SpeedMultiplier]` 

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/96321415/dea3941c-97dc-4ca6-bf75-17d8145196bf)

**To Reproduce**

1. Create now with SpeedMultiplier Property as type Number
2. Add InlineSelect to note: `INPUT[inlineSelect(option(0.666667), option(1.0), option(1.333333), showcase):SpeedMultiplier]` 
3. Change value using InlineSelect
4. Property updates however Obsidian reports Type Mismatch.
5. Click ! to Save the change of the Type.
6. Reload note to fix calculations.

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/96321415/7991759d-a9a1-42d4-be79-97920daca857)

**Expected behavior**
Value should change and know that it is a number. 

**Screenshots**
See above

**Occurs on**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.6.1

**Additional context**
I love MetaBind

**Comment by mProjectsCode** [comment]
There was a small bug in the inline select code that caused the values to be stringified, since i can only pass strings as values to obsidians inline select prefab.
