### ISSUE TITLE
Titles with apostrophes no longer work as of v0.6.5 

### ISSUE THREAD

**Issue by gypsyav** [mProjectsCode/obsidian-meta-bind-plugin#116]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
A parsing error occurs if there is an apostrophe in a title such as "Today's"

**To Reproduce**
Add a title with an apostrophe to a title argument

1. add input field 
	INPUT[input type:metadata]
2. add title argument
        INPUT[input(title()):metadata]
4. add title with an apostrophe
        INPUT[input(title(Today's)):metadata]
5. Parsing error of unexpected character occurs.

**Expected behavior**
The title for the input field should show

**Occurs on**

-   [ ] Windows
-   [ ] macOS
-   [x] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.6.5

**Additional context**
Title's with ' parsed correctly in versions prior to 0.6.5. Prior to the update this worked fine 
	\```meta-bind
	INPUT[number(title(Today's Weight)):weight]
	\```
After updating the same block produces an error.

**Comment by mProjectsCode** [comment]
Yes, that is a breaking change. 

Try `INPUT[number(title('Today\'s Weight')):weight]`. (Surrounding the string in quotes and escaping the `'` with a backslash)

The new docs that I am currently working on include a section about this.

**Comment by gypsyav** [comment]
> Try `INPUT[number(title('Today\'s Weight')):weight]`. (Surrounding the string in quotes and escaping the `'` with a backslash)
> 
This works. I had tried double quotes " before I filed the report and those gave the same parsing error. I didn't think about trying single quotes.
Thank you
