### ISSUE TITLE
bind target frontmatter ident parser fails to parse ident with non ascii letters

### ISSUE THREAD

**Issue by oyvindsolstad** [mProjectsCode/obsidian-meta-bind-plugin#119]
I have properties that contain characters from other alphabets, like these Scandinavian characters: æøå ÆØÅ

The plugin immediately errors when I enter a properties name with ø, like "ønske" (Norwegian for "wish").

 [META_BIND_ERROR]

![Skjermbilde 2023-10-06 kl  12 01 58](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/4631971/1a94a376-a381-4fd9-83d9-8f355461ac41)

Latest public version of Obsidian on MacOS, latest version of plugin.

**Comment by mProjectsCode** [comment]
can you click on the error, copy the full error message, and paste it here?

**Comment by oyvindsolstad** [comment]
Sure: 

code: 

![Skjermbilde 2023-10-06 kl  14 33 46](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/4631971/54034a28-7467-4f62-913d-5105b97b13c5)

error:

![Skjermbilde 2023-10-06 kl  14 33 37](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/4631971/78b1ec12-8b10-4c06-9fe4-4d16f40658a5)

If I change the "ø" to "o" it works again. Same with other Scandinavian letters like æøå ÆØÅ.

Or characters from other alphabets. I use [ᑷ](https://graphemica.com/ᑷ) in many of my properties, which also gives an error.

**Comment by mProjectsCode** [comment]
ah, ok. I see the problem. I will try to fix it for the next release. For now you can try `["ønske"]` as the bind target. So `INPUT[...:["ønske"]]`

**Comment by oyvindsolstad** [comment]
Great, thanks for the quick reply!

**Comment by mProjectsCode** [comment]
Note to self: This is bc the metadata ident parser only matches ascii and not unicode letters.
