### ISSUE TITLE
Inline `INPUT` doesn't work in callouts (live preview and reading)

### ISSUE THREAD

**Issue by caasion** [mProjectsCode/obsidian-meta-bind-plugin#12]
- [x] The Plugin is up to date
- [x] Obsidian is up to date

**Describe the bug**
Inputs that are done with `inline code blocks` don't work inside callouts whether it'd be in live preview mode or reading view. I originally thought I could have a working slider by putting it in callouts, but the slider doesn't even work in reading mode (while in callout)

**To Reproduce**
1. Create a callout
2. Try out any inline INPUT elements

**Expected behavior**
Callouts to render properly in callouts while in live preview and reading view

**Screenshots**
![image](https://user-images.githubusercontent.com/103465188/176783210-f994d7ed-19fc-47f7-87f8-86c1fc67d647.png)

**Occurs on**
- [x] Windows
- [ ] macOS
- [x] Linux
- [x] Android
- [ ] iOS

**Plugin version**
0.2.0

**Comment by caasion** [comment]
Update: I'm not sure what happened, but these input slides are working in live preview, when it previously wasn't (at the time i posted this issue). However, it still doesn't render in these plain callouts:
![image](https://user-images.githubusercontent.com/103465188/176786671-211c2b31-c456-414a-ba25-af20dea4a5dc.png)

**Comment by caasion** [comment]
However, it seems to be only live preview. In reading view, the inputs remain the same:
![image](https://user-images.githubusercontent.com/103465188/176787155-f8cf1d4a-bfba-408c-a9ba-c813b7cd3626.png)

**Comment by mProjectsCode** [comment]
It seems to be working for me in reading mode. Inline fields generally don't work in live preview (limitation of obsidian), I am surprised it works in callouts though.

**Comment by mProjectsCode** [comment]
Source
![image](https://user-images.githubusercontent.com/61602848/176788233-dc9097a8-9fde-4f14-89d3-9a1af9ac09bf.png)

Live Preview
![image](https://user-images.githubusercontent.com/61602848/176788261-9b8c626c-8a7c-40fa-9cd5-cb1181d1661d.png)

Reading
![image](https://user-images.githubusercontent.com/61602848/176788283-55763b06-6b96-4724-8cc1-af34139a47fa.png)

**Comment by mProjectsCode** [comment]
You could check the console for any errors, but the input field declaration staying the same, without an error message is an indication, that the markdown post-processor hasn't picked up that declaration.
