### ISSUE TITLE
Request: Character Limit in List/Text Field Types

### ISSUE THREAD

**Issue by TristGit** [mProjectsCode/obsidian-meta-bind-plugin#120]
**Is your feature request related to a problem? Please describe.**
There is not problem; Outside of me exploring the uses of Metabind and I often find that the List/Text field types for the plugin usually can mess up the format of some things/tables and whatnot. Or sometimes I just want to not be able to type too many details if I am using it for adding flavor text for something elsewhere. 

**Describe the solution you'd like**
Having a variable that adjusts the character limit of list/text field entries would allow me to set a hard cap on things that allows me to make sure it doesn't mess with the format of anything.

**Additional context**
In instances like this where you might want to limit yourself: 
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/57966174/30fa1a2b-3f05-472f-9d19-14221378bd1b)

**Comment by mProjectsCode** [comment]
released as part of `0.7.0`
