### ISSUE TITLE
Markdown rendering support in js view fields

### ISSUE THREAD

**Issue by TDSrock** [mProjectsCode/obsidian-meta-bind-plugin#121]
**Is your feature request related to a problem? Please describe.**
Whenever you include HTML objects in more complicated querries they cannot render the nice markdown style nor through HTML.

This makes usefull little snippets like: 
```meta-bind-js-view
{Requirements} as req
---
if(context.req == null || context.req.length == 0)
	return null;
var reqText = "Requirements: ".bold();
context.req.forEach((val, key, arr) => {
	if (Object.is(arr.length - 1, key)) {
		// execute last item logic
		reqText += " and " 
	}
	reqText += val
	if(key != 1 && key != arr.length - 1){
		reqText += ", "
	}
});
reqText += "\r---"
return reqText;
```
Not render as I intended.
Similair for lists etc. I think this is mainly something that is lacking from the "code-block" renderer that Obsidian uses?

**Describe the solution you'd like**
It would be neat-o if lists etc can be rendered just like text from anywhere. 
Since Obisdian can already render these things hijacking their solution would be the easiest (and most consistent)

**Additional context**
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/12527285/99b7de89-7511-4c37-a292-f2f78fd8f0ea)
This list for example generated through this simple snippet:
```meta-bind-js-view 
{Effects} as effects
---
return "- " + context.effects.join("\r- ")
```
Also sadly doesn't render with the nice little bubbles I would have hoped for

**Comment by mProjectsCode** [comment]
yeah, the rendering here is not optimal ATM. I am thinking of making [JS Engine](https://github.com/mProjectsCode/obsidian-js-engine-plugin) a requirement for them and using JS Engine to render js view fields.

**Comment by mProjectsCode** [comment]
This would be a breaking change though, so I will have to leave the current version untouched and just mark it as deprecated, and build a new version based on js engine.

**Comment by TDSrock** [comment]
Makes sense to keep this seperation of concerns as high as possible. Perhaps a non-breaking option is to detect if JS Engine is available and us it when it is, otherwise use what it does now as a fallback?

**Comment by mProjectsCode** [comment]
I am going to close #122 in favor of this issue

**Comment by mProjectsCode** [comment]
done in aaccbc6, will be part of the next release
