### ISSUE TITLE
Note links don't work

### ISSUE THREAD

**Issue by TDSrock** [mProjectsCode/obsidian-meta-bind-plugin#122]
**Is your feature request related to a problem? Please describe.**
If the property you are including into text includes a note-reference the note-reference doesn't work. I assume this is related to the other FR I just made, making it seperate (and not as a BR) as I beleive the behavior can be somewhat up to you.

Example:
File YAML:
```YAML
ShortDescription: [[Template - Feat]]
```
Tested view-js snippet:
```meta-bind-js-view 
{ShortDescription} as test
---
return context.test
```
Expected result: text with a clickable link to file
True result:
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/12527285/76a35327-2a13-4e93-b7f1-05e44b1e9eff)

**Describe the solution you'd like**
The same result as above just being clickable (and working with the [text|overrideText] linkage)

**Comment by mProjectsCode** [comment]
https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues/121
^ referenced as `the other FR I just made`
