### ISSUE TITLE
New js view field powered by JS Engine

### ISSUE THREAD

**Issue by mProjectsCode** [mProjectsCode/obsidian-meta-bind-plugin#123]
See https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues/121.

**Comment by TDSrock** [comment]
Any idea on the complexity/timeline of adding this?

I really love your plugin and incorporating this fully into my workflow would be awesome

**Comment by mProjectsCode** [comment]
currently, this has low priority. There is some stuff that i need to change with js engine and ofc with meta bind, so it's not a one-day thing and i want to finish the stuff that i am currently working on first. So this will probably be a task for november

**Comment by mProjectsCode** [comment]
done in aaccbc6
