### ISSUE TITLE
[FR] Dropdown / Alternative Multiselect

### ISSUE THREAD

**Issue by ProStashio** [mProjectsCode/obsidian-meta-bind-plugin#131]
**Is your feature request related to a problem? Please describe.**
Right now, if you want to use a multi-select, you have to see all the options available.

**Describe the solution you'd like**
It would be nice to have a template of options we can use and then have them assorted within a dropdown so we can select the ones we wish to display and then hide all unselected options.

**Comment by mProjectsCode** [comment]
Note to self: 
- `inlineListSuggester` inline list with suggester modal as source
- `inlineList` inline list with text input modal as source
- `inlineMultiSelect` inline list with dropdown as source

**Comment by mProjectsCode** [comment]
i have the `inlineListSuggester` and the `inlineListSuggester` working, but i don't think i will do the `inlineMultiSelect`

**Comment by unxok** [comment]
If I may ask-- Why was `inlineMultiSelect` abandoned?

**Comment by mProjectsCode** [comment]
Because at the time, I didn't feel like implementing it.

**Comment by unxok** [comment]
Fair. Do you plan on eventually adding it? If not, I could probably work on it and open a PR?

**Comment by mProjectsCode** [comment]
maybe at some point. You making a PR for it is probably faster.
