### ISSUE TITLE
Space with VIEW

### ISSUE THREAD

**Issue by ProStashio** [mProjectsCode/obsidian-meta-bind-plugin#132]
-   [ x] The Plugin is up to date
-   [ x] Obsidian is up to date

**Describe the bug**
No space between items

**To Reproduce**
Make an input list for aliases and then add some options. Then call on them with a VIEW and there will be no space after the ,

**Expected behavior**
A space after the ,

**Screenshots**
https://gyazo.com/07c4071a0d47548207bc5ce65d8be49f

https://gyazo.com/fb72c0e0877cf34e5532cdc7fe92fa84

https://gyazo.com/88ee64597fc3c9a403f134d5c7a3647d

**Occurs on**

-   [ x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.7.0

**Comment by mProjectsCode** [comment]
I guess i need to write a custom toString function for text view fields.
