### ISSUE TITLE
Multiple checkboxes to track project progress

### ISSUE THREAD

**Issue by gitgitdown** [mProjectsCode/obsidian-meta-bind-plugin#133]
There's a plugin called "Obsidian Task Progress Bar" that lets you create a progress bar that fills up as checkboxes are ticked.
It looks something like this:

![1](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/13779319/c0e87fbd-a90a-4ad4-b43c-db01bfddc699)

It's not the visual of the progress bar that interests me, but rather the indication of the number of checked checkboxes in relation to the total number of checkboxes: **[2/4]**
Would it be possible to implement something similar that displays in a property :

![2](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/13779319/37487082-bb24-484e-9f28-be6981c00a2a)

The aim is to be able, for example, with the "Database folder" plugin, to have something like this to know the current progress of a project: 

![3](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/13779319/7c98237c-2939-4e08-a5ba-ef0f75e79bd8)

Thanks for your attention

**Comment by mProjectsCode** [comment]
i could add an argument to the slider, which changes the frontmatter value the slider writes to include the maximum

**Comment by mProjectsCode** [comment]
Syncing something to checkboxes is not in the scope of the plugin. The multi select idea is not feasible, as the plugin needs to save all state to the frontmatter. If it were to only store the number of completed tasks, the info on which tasks are completed would be lost.
