### ISSUE TITLE
Add a date picker to the date field

### ISSUE THREAD

**Issue by isle9** [mProjectsCode/obsidian-meta-bind-plugin#14]
**Is your feature request related to a problem? Please describe.**
I personally find it a lot easier to change date using a date picker.

**Additional context**
The date picker could look something like this:
![image](https://user-images.githubusercontent.com/74906541/177001799-97d4c74e-a594-48d4-9060-b8f936d2a48b.png)

**Comment by mProjectsCode** [comment]
I am currently planning on adding it as its separate input field.

This is not the final version
![image](https://user-images.githubusercontent.com/61602848/177652042-08e5a219-cd02-453d-8285-fc8a1fec9473.png)

**Comment by mProjectsCode** [comment]
![image](https://user-images.githubusercontent.com/61602848/177876020-ad4f48f0-7f94-4fdf-8e33-c5efdaa24a08.png)
I am happy with this design, except for the misaligned icon, but idk how to fix that...

**Comment by mProjectsCode** [comment]
![image](https://user-images.githubusercontent.com/61602848/178159383-2610a73b-e585-45a7-8e6c-4e7fbf0518e9.png)
I also added a year input to quickly change the year.
