### ISSUE TITLE
[FR]: Expose API

### ISSUE THREAD

**Issue by Lisandra-dev** [mProjectsCode/obsidian-meta-bind-plugin#143]
# **Is your feature request related to a problem? Please describe.**
I'm the developper of [Obsidian Publisher](https://github.com/ObsidianPublisher/obsidian-github-publisher/). And some days ago, an user suggest me to integrate meta-bind in my plugin.

Too bad, I don't use the plugin and checked the documentation and didn't found API usage to directly export a meta-bind view in HTML/markdown when I parse the content of the file.

For reference, Dataview API allows this, so I can export all dataview into table, list, and inline too. If I could, I will use the same idea to export the meta-bind into a fully markdown file, with content and all. 

# **Describe the solution you'd like**
At last, expose the API and create a function (maybe it already exists) to export all meta-bind view into HTML/Markdown, allowing other plugin to use, for example, in export. 

# **Additional context**
See https://github.com/ObsidianPublisher/obsidian-github-publisher/issues/243

**Comment by mProjectsCode** [comment]
The plugin has an api, if you look into `src/api/API.ts`. I am not sure if that is what you are looking for. If not, I would need a more concise description of what you need from the API.

**Comment by Lisandra-dev** [comment]
Hello!
How I can use it in my own plugin ? Are they docs about the usage of the API ?

Thanks.

**Comment by mProjectsCode** [comment]
No, but i just added some doc comments to all functions. You can access it via `<pluginInstace>.api`
