### ISSUE TITLE
Meta bind js variables no longer in context obj

### ISSUE THREAD

**Issue by TDSrock** [mProjectsCode/obsidian-meta-bind-plugin#144]
-   [x] The Plugin is up to date (just updated)
-   [x] Obsidian is up to date

**Describe the bug**
All of my existing scripts now fail to bind to the values bound. It appears the context object is not passing in anything?

**To Reproduce**

1. Open a new note
2. Define a list with name "test"
3. Add three entries to the list I used:
```
test: 
- 3
- 3
- 3
```
4. Use the following meta-bind-js-view
```meta-bind-js-view
{Test} as t
---
var text = ""
for(a in context.t)
	text += a
return text
```
5. Empty data

Testing with just return t and 

**Expected behavior**
in the specific test sample, you would expect the result to be: `333`

**Occurs on**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [x] Android
-   [ ] iOS
* rest is untested
* 
**Plugin version**
0.8

**Additional context**
I would assume the reference to the variables has changed and that is all it is.
Otherwise it may be related to the context object not being initialized properly for whatever reason.

**Comment by mProjectsCode** [comment]
they are now in `context.bound.`

**Comment by TDSrock** [comment]
Thanks, was there anything special needed to cause them to render with markdown style now?
As that part doesn't appear to be working.

**Comment by mProjectsCode** [comment]
https://github.com/mProjectsCode/obsidian-js-engine-plugin
See JS Engine Readme.
I am working on the meta bind docs update right now.

**Comment by mProjectsCode** [comment]
you can do `return engine.markdown.create('string here');` to render as markdown

**Comment by TDSrock** [comment]
Awesome, thanks!
