### ISSUE TITLE
Unselect on select() input

### ISSUE THREAD

**Issue by martyTF** [mProjectsCode/obsidian-meta-bind-plugin#145]
**Is your feature request related to a problem? Please describe.**
I make use of the select() input in combination with dataview queries, where it takes a tag of the note to filter
rn i just have a text field that i clear to empty the filter again (see attached)

**Describe the solution you'd like**
clicking on the selected option of a select() input will clear the value of the frontmatter key

**Additional context**
**example:** 
on the "plants book" i have a metabind select() for the autumn colouring, and i can select the colour in metabind, and the dataview query only displays notes of plants with the respective autumn colouring
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/69526651/a2022b15-77c7-4286-9ff7-820d2a8d9974)

**Comment by mProjectsCode** [comment]
you could use a [suggester](https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/reference/inputfields/suggester/) as that supports dataview with [optionQuery](https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/reference/inputfieldarguments/optionquery/).

**Comment by mProjectsCode** [comment]
oh wait I completely misread what you are asking for xD
