### ISSUE TITLE
Increment input field

### ISSUE THREAD

**Issue by Davve37** [mProjectsCode/obsidian-meta-bind-plugin#147]
An upvote/downvote object that you can click to increase or decrease a modifier. So like if you have a field that shows a number/modifier, instead of typing in a different number or picking from a dropdown, you just increment it one step.

**Comment by mProjectsCode** [comment]
possibly implemented what you are looking for in b495086. Buttons can now modify frontmatter. [Here is an example](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/b4950861ab23fec2cc9d9472946e66defe270dcd/exampleVault/Button%20Example.md?plain=1#L200).
