### ISSUE TITLE
Allow `defaultValue` to be set to `null` or `none` for `datePicker`

### ISSUE THREAD

**Issue by Cornelius-G** [mProjectsCode/obsidian-meta-bind-plugin#148]
Hi, thanks a lot for this great package and all the work with the recent updates!

**Is your feature request related to a problem? Please describe.**
When using `datePicker`, the `defaultValue` cannot be set to display "none" like the button "Set no date" allows.

**Describe the solution you'd like**
I would expect something like ` INPUT[datePicker(defaultValue(null)):bind_target]`  to give the same result as "Set no date".

**Additional context**

**Comment by mProjectsCode** [comment]
hamm strange. I haven't tested this yet. But if it behaves as you say then this is a bug.
