### ISSUE TITLE
FR

### ISSUE THREAD

**Issue by cogscides** [mProjectsCode/obsidian-meta-bind-plugin#15]
Is it possible to prevent edit mode somehow in Live Preview?

When I'm entering the input field I want to edit the value, but not edit the setup of the field binding.

If it's possible, maybe on hover input to show settings gear on right from it? (require some UI options)
Maybe in case of preventing onclick, it still be possible to enter editing mode with keyboard, or click right on the same raw (right/left)

**Comment by mProjectsCode** [comment]
The plugin uses markdown post processors, a feature in the obsidian api. If you want a working input field in live preview, you have to use code blocks.
You can look up on the syntax here https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/tutorial

**Comment by mProjectsCode** [comment]
Inline code blocks do not work in live preview (obsidian limitation, nothing i can do about that)
