### ISSUE TITLE
Button functionality to create a Soundboard

### ISSUE THREAD

**Issue by Davve37** [mProjectsCode/obsidian-meta-bind-plugin#150]
I would ask for 4 simple options to such a function.
1. Play (Play the file once)
2. Repeat (Play the file over and over)
3. Stop (Stop the file)
4. Volume (Being able to adjust the relative volume, between 0%-100%

Also if you could play several tracks simultaneously. Now I already have such a program that a friend of mine made over 10 years ago probably at this point: https://i.imgur.com/rzWkA6q.png

It would just be nice to have the same functionality inside Obsidian.

**Comment by mProjectsCode** [comment]
Thanks for the suggestion, but I think this goes a bit beyond the scope of the plugin.
