### ISSUE TITLE
Persisntance of input field values without property attributes for pdf exports

### ISSUE THREAD

**Issue by tojkuv** [mProjectsCode/obsidian-meta-bind-plugin#152]
**Is your feature request related to a problem? Please describe.**
Exporting to pdf exports the selective fields empty (ex. time input field).

**Describe the solution you'd like**
It would be great to have the values export to pdf.

**Additional context**
![Screenshot from 2023-12-02 14-45-22](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/56209137/ad160c46-20d8-457d-a88f-129db996222a)

**Comment by mProjectsCode** [comment]
I have no idea how the PDF export works. I would expect all input fields to display their default values, and the date picker simply defaults to the current date.

**Comment by tojkuv** [comment]
Are there any workaround solutions (changing the default value to the selected value in some way)? pdf export is using the default values. This can be seen by changing the default values and exporting to pdf.

**Comment by mProjectsCode** [comment]
so you want input fields to display the correct values (not the default values) in the exported PDF?
Or what are you asking for?

**Comment by mProjectsCode** [comment]
> Yes. The selected values export as long as there is a properties attribute for it defined. In cases where there is no unique properties attribute defined, the exporter uses the default value. I don't really know how this could be changed without knowing how pdf export works.

sounds like the plugin works as intended.

> Is there a way to pass data to the pdf exported about the selected input fields?

what do you mean with selected input fields?

**Comment by tojkuv** [comment]
Input fields that are not explicitly assigned a properties attribute:

For example:
`INPUT[time]`

**Comment by mProjectsCode** [comment]
Unbound input fields can not persist their data, as they have nowhere to store it.
