### ISSUE TITLE
IOS app won't load

### ISSUE THREAD

**Issue by mmmmiru** [mProjectsCode/obsidian-meta-bind-plugin#158]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [X] iOS

### Plugin Version

0.9.0

### Describe the Issue

App was working alright on IOS 17.1.2 before installing the plugin.

I did so on my Mac, and when I went to check my vault on my phone it is an endless loop, of obsidian syncing the configuration files, then loading the cache, workplace etc, and the app screen going blank.

### Steps to Reproduce

Just making sure the plugin is activated and starting the obsidian IOS app.

### Expected Behavior

To act just like on my Mac.

**Comment by claremacrae** [comment]
I had this exact same thing several days ago.

I just tried getting a more reproduction of it, and this time it only crashed once rather than repeatedly.

I wrote up today's experiments in the earlier report: #102.

**Comment by mmmmiru** [comment]
I have some notes with meta bind text on them, and the app crashes even if the notes with the meta bind aren’t the ones open. 

I do need to check if having notes with no meta bind texts makes the app crash as well.

**Comment by mProjectsCode** [comment]
It could be that the plugin bundle is too big as one of the bundled deps (mathjs) is quite large.

**Comment by mProjectsCode** [comment]
Thanks for the report. I am closing this in favor of #102.
