### ISSUE TITLE
Suggester isn't working

### ISSUE THREAD

**Issue by mclearc** [mProjectsCode/obsidian-meta-bind-plugin#159]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.10.0

### Describe the Issue

suggester doesn't work after update. If there is a value in the front matter it will show that value, but dropdown options are not created -- i.e. there is no interactivity. 

### Steps to Reproduce

---
test: 2
---
`INPUT[suggester(option(0), option(1), option(2)):test]`

### Expected Behavior

does't create a pop up window to select from (note that inline suggester does work)

**Comment by mProjectsCode** [comment]
tanks for the report, fixed in version `0.10.1`
