### ISSUE TITLE
ERROR: [MB_BIND_TARGET_ERROR] bind target resolves to multiple files; please also specify the file path

### ISSUE THREAD

**Issue by ooker777** [mProjectsCode/obsidian-meta-bind-plugin#16]
I use the [example](https://raw.githubusercontent.com/mProjectsCode/obsidian-meta-bind-plugin/master/exampleVault/examples.md) and I get this error in every line:

![](https://i.imgur.com/GQFXzJ2.png)

**Comment by mProjectsCode** [comment]
you are using the example vault on the master branch. This is only works correctly with the newest changes on the master branch, which aren't released as a release yet.

**Comment by ooker777** [comment]
So you haven't push it to github yet?

**Comment by mProjectsCode** [comment]
no it is on github and if you build the plugin yourself from github, then the example vault should work
