### ISSUE TITLE
Suggester opening automatically

### ISSUE THREAD

**Issue by Lmasey** [mProjectsCode/obsidian-meta-bind-plugin#162]
### Is your Feature Request Related to a Problem?

I would like this feature to be disabled. On Obsidian .mobile I can't do anything because the bar comes across the page. If there is a way to turn this off, can someone please tell me how:)

### Describe the Feature you'd Like

I would like to be able to add or edit a field when I want instead of seeing the choice options.

### Additional Context

![Screenshot 2023-12-21 at 10 23 16 AM](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/121703468/21946fd9-4532-446b-bdb3-8444c1b11536)

**Comment by mProjectsCode** [comment]
This sounds more like a bug report. Could you open a bug report for this, please?
