### ISSUE TITLE
Hide Button after triggering :-)

### ISSUE THREAD

**Issue by xverbatim1971** [mProjectsCode/obsidian-meta-bind-plugin#166]
### Is your Feature Request Related to a Problem?

-

### Describe the Feature you'd Like

If you create a button that executes a command, it would be useful to hide it after execution.

For example, you have an invoice note with formulas etc.
then go to a button "PDF Export", this button will disappear and you can then export the note or invoice as a pdf without a button being visible in the pdf.

### Additional Context

hello,

I have a few suggestions:

it would be nice if you could create a button that would disappear after triggering, i.e. be deleted :-) or hide.

great things would be possible :-)

**Comment by mProjectsCode** [comment]
Thanks for the suggestion, but after some consideration, I have decided that I won't implement this for now.
