### ISSUE TITLE
Inputs not rendering when three or more dashes ("---") are anywhere in the note

### ISSUE THREAD

**Issue by Pachtjuilaard** [mProjectsCode/obsidian-meta-bind-plugin#17]
- [x] The Plugin is up to date
- [x] Obsidian is up to date

**Describe the bug**
Input fields of any kind don't render in Reading mode if there are three or more consecutive dashes anywhere in the note. I'm often using three dashes to render a horizontal line in Reading mode. Dashes containing frontmatter or in tables are fine however.

**To Reproduce**
1. Open note with this plugin working as intended.2. 
2. Add 3 or more dashes somewhere in the note.
3. Close, and reopen the note. 

**Plugin version**
0.2.0

**Comment by mProjectsCode** [comment]
That must be some wired thing with the regex that I am using to find and replace the metadata block
