### ISSUE TITLE
Add tooltips (hover text clarifying the purpose) to inputs

### ISSUE THREAD

**Issue by FitzFrobozz** [mProjectsCode/obsidian-meta-bind-plugin#170]
### Is your Feature Request Related to a Problem?

Currently it doesn't look like there is a way to enable tooltips (information that clarifies the purpose of the input when the cursor is over the input), even though the aria-label attribute is present in the rendered html.

### Describe the Feature you'd Like

The biggest benefit of having tooltips would be better general accessibility, but it would also be helpful in cases where, e.g., an inline button is styled to be made smaller (e.g. a small button at the end of a heading).

I would propose either: (a) pull text from the input label and display that as a tooltip or (b) add a new title argument and display that text as a tooltip.

(If falling back and using a title attribute instead would be easier, that would make me almost as happy, although it would be less accessible.)

**Comment by mProjectsCode** [comment]
I just pushed a commit that adds an optional tooltip to buttons. If no tooltip is set, the button label will be shown as the tooltip on hover.
I hope this solves this FR.

**Comment by FitzFrobozz** [comment]
I'm sure it does, regardless of how you implemented it. Thanks so much!
