### ISSUE TITLE
[docs] Fix typos and documentation

### ISSUE THREAD

**Issue by dbarenholz** [mProjectsCode/obsidian-meta-bind-plugin#172]
Hello! Please assign this to me so that I can do it when I have time.

When creating buttons, I noticed some inconsistencies in the documentation.

1. Typo: The type says `imput`, but should say `input`.

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/25849034/609b9623-8b32-4d38-8e10-c36937f6f185)

2. Typo: In the example for JS actions, you do not adhere to the `JSButtonAction` interface specified above, making it throw an error on copy-paste. Specifically, `command` should become `file`.

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/25849034/f1aef6eb-f1c7-4dac-8fc7-9f655698b515)

3. Typo: A sentence on this part about embeds is weird; `[...] it is not seamless and you the content of Note A still.`

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/25849034/9288f753-c567-4b33-8374-e01788126a8c)

Again, assign the issue to me so that I can do it soon :tm:.

**Comment by mProjectsCode** [comment]
The command id for the command examples is wrong, see #173.

**Comment by mProjectsCode** [comment]
Sorry to "steal" your contribution, but I implemented this as part of the docs update for the release tomorrow.
