### ISSUE TITLE
Button Action Doesn't Happen Upon Clicking

### ISSUE THREAD

**Issue by rchaklashiya** [mProjectsCode/obsidian-meta-bind-plugin#173]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.10.2

### Obsidian Version
v1.5.3 (installer v1.5.3)

### Describe the Issue

The buttons functionality does not work for me, even after testing with all other plugins disabled, in a different vault where there's very few notes, and in both reading and live preview mode.

I tried the most basic example from the documentation to see if it works, and clicking on the resulting button does not open the FAQ (the button itself shows up, but the action upon clicking does not happen).

This is the example I tested, it did not work, nor did the one for the specific command I was trying to run either.

```meta-bind-button
style: primary
label: Meta Bind Help
action:
  type: command
  command: obsidian-meta-bind-plugin:mb-open-faq
```

### Steps to Reproduce

1. Disable all plugins except for meta-bind
2. Open a new page
3. Paste the following test code from the documentation (documentation here: https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/ )
```meta-bind-button
style: primary
label: Meta Bind Help
action:
  type: command
  command: obsidian-meta-bind-plugin:mb-open-faq
```
4. Try to press the button in both live preview and reading mode, it doesn't work. The button will lighten up upon hovering by the mouse, but it won't do anything upon being clicked.
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/18043279/d83bb958-b1c8-409f-9594-423e9b279981)

### Expected Behavior

I expect it to open FAQ in the case of the test code from the documentation, and to run the set command in the case of the command I actually want to run (for the button I made for that purpose, which wasn't shown here since the more basic example of something straight from the documentation didn't work for me.)

**Comment by mProjectsCode** [comment]
I think the command ID changed and I didn't update the docs. Will check in more detail once I am back home.

**Comment by mProjectsCode** [comment]
Thanks for the report. I fixed the docs and will deploy the changes tomorrow.
