### ISSUE TITLE
Button works in edit mode, but not in view mode

### ISSUE THREAD

**Issue by ruben-sg** [mProjectsCode/obsidian-meta-bind-plugin#174]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.10.2

### Describe the Issue

I have a few inline buttons in a group with the following code (inside a column view with the obsidian columns plugin):

`BUTTON[cdn,cwn,cmn,cyn]`

While they work perfectly fine in edit mode, they don't work in view mode. Instead of the button, there is a message "unloaded meta bind button".

The buttons are hidden and are like this:

```meta-bind-button
label: Daily
hidden: true
id: cdn
style: default
actions:
  - type: templaterCreateNote
    templateFile: Organisation/system/templates/Daily Note.md
    folderPath: Privat/Periodic Notes/Daily Notes
    fileName: ""
    openNote: true
```
```meta-bind-button
label: Weekly
hidden: true
id: cwn
style: default
actions:
  - type: templaterCreateNote
    templateFile: Organisation/system/templates/Weekly Note.md
    folderPath: Privat/Periodic Notes/Weekly Notes
    fileName: ""
    openNote: true
```
```meta-bind-button
label: Monthly
hidden: true
id: cmn
style: default
actions:
  - type: templaterCreateNote
    templateFile: Organisation/system/templates/Monthly Note.md
    folderPath: Privat/Periodic Notes/Monthly Notes
    fileName: ""
    openNote: true
```
```meta-bind-button
label: Yearly
hidden: true
id: cyn
style: default
actions:
  - type: templaterCreateNote
    templateFile: Organisation/system/templates/Yearly Note.md
    folderPath: Privat/Periodic Notes/Yearly Notes
    fileName: ""
    openNote: true
```

### Steps to Reproduce

1. Insert Buttons (hidden)
2. Insert grouped inline buttons

### Expected Behavior

Display the buttons in both, edit and view mode.

**Comment by mProjectsCode** [comment]
That is probably an issue with the columns plugin. It is known to cause issues for other plugins. I would recommend you use a callout-based solution for multiple columns.

**Comment by mProjectsCode** [comment]
Does the issue persist with buttons outside of columns?

**Comment by ruben-sg** [comment]
You're right. It only persists inside of columns. That's a shame, but I'll find a workaround.

**Comment by mProjectsCode** [comment]
Great. Then this is not an issue with my plugin but with the columns plugin. I also found [this](https://github.com/tnichols217/obsidian-columns/issues/56) related issue on the columns plugins repo.
