### ISSUE TITLE
Loading Issues

### ISSUE THREAD

**Issue by ProStashio** [mProjectsCode/obsidian-meta-bind-plugin#175]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.10.2 (And older)

### Describe the Issue

I have been noticing issues where I would load up my metadata section, scroll through them and when I go back up to the top and close it it has issues loading everything. Doesn't always happen, but happens a fair amount.

### Steps to Reproduce

Open note, open large metadata tab, scroll through, close

https://gyazo.com/9eb8f5ff8422a737faa552c63aea3cfd

### Expected Behavior

To load the note normally

**Comment by mProjectsCode** [comment]
This is an issue with obsidian and not meta bind
