### ISSUE TITLE
Does the updateMetadata function work?

### ISSUE THREAD

**Issue by xverbatim1971** [mProjectsCode/obsidian-meta-bind-plugin#176]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.10.2

### Describe the Issue

hello,

i have a question, does the updateMetadata function already exist?

i used the code from the page [https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/master/exampleVault/Button%20Example.md#modifying-front-matter] and unfortunately i only get an error message :(
->"META BIND_ERROR" and BUTTON ID NOT FOUND"

i would like to increase a variable by +1 in the frontmatter, is that possible?

best regards

### Steps to Reproduce

---

count: 0

---

### Modifying Front-matter

```meta-bind-button
label: "+1"
hidden: true
id: "count-increment"
style: default
actions:
  - type: updateMetadata
    bindTarget: count
    evaluate: true
    value: x + 1

```

```meta-bind-button
label: "-1"
hidden: true
id: "count-decrement"
style: default
actions:
  - type: updateMetadata
    bindTarget: count
    evaluate: true
    value: x - 1

```

```meta-bind-button
label: "Reset"
hidden: true
id: "count-reset"
style: default
actions:
  - type: updateMetadata
    bindTarget: count
    evaluate: false
    value: "0"

```
```

`BUTTON[count-decrement, count-reset, count-increment]` `VIEW[{count}]`



### Expected Behavior

that the button increases a variable

**Comment by mProjectsCode** [comment]
they are now released in version `0.11.0`.
