### ISSUE TITLE
Feature Request: Change nested YAML, or lists in Frontmatter

### ISSUE THREAD

**Issue by Pachtjuilaard** [mProjectsCode/obsidian-meta-bind-plugin#18]
**Is your feature request related to a problem? Please describe.**
I would like to be able to edit keys in lists with this plugin. For example:

---
list: 
 item1: true
 item2: false
---

Here, it would be handy if I could toggle item2 to be true for example. 

**Describe the solution you'd like**
I would like a inline code block like: `INPUT[toggle:list.item2]`. This works the same way as the Dataview plugin, and is easy to use.

**Additional context**

**Comment by mProjectsCode** [comment]
That is something i will put on my todo list

**Comment by mProjectsCode** [comment]
I am currently, sort of working on this. 
I am writing a library to edit metadata that is shared between all my plugins, which would enable editing of nested metadata. Once the library is in a stable state, I will update this plugin to use it.

**Comment by mProjectsCode** [comment]
https://github.com/OPD-libs/OPD-libs/tree/main/libs/OPD-metadata-lib

**Comment by megclaypool** [comment]
Cool, thanks!!! ❤️

**Comment by Pachtjuilaard** [comment]
Thanks for the update! I don't understand how it works however, and couldn't find anything about that in the docs. Could you explain how I could target nested yaml with a toggle?

**Comment by mProjectsCode** [comment]
i just realized that there was a bug in the code, I will fix it today

if your metadata looks like this 
```
---
nested:
  object: "some text"
---
```
then you bind to it like this
`INPUT[text:nested.object]`

**Comment by mProjectsCode** [comment]
I will update the docs soon
