### ISSUE TITLE
Step Size Issue

### ISSUE THREAD

**Issue by AdSecIT** [mProjectsCode/obsidian-meta-bind-plugin#180]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.11.0

### Describe the Issue

When setting the Step Size to decimals for a progress bar, for example 0.1 it goes in odd numbers such as 1.1, 1.1000000009, 1.2, 1.3000000000

### Steps to Reproduce

Setup a Progress bar with steps of 0.1 and slide around.

### Expected Behavior

Should go 1.1, 1.2, 1.3 Etc

**Comment by dbarenholz** [comment]
I cannot reproduce this with the latest meta-bind version on Linux. Are you using the same thing that I'm using below? This works as expected on my end.

```
INPUT[slider(minValue(1), maxValue(10), stepSize(0.1)):slider]
```

**Comment by mProjectsCode** [comment]
Same on my end. I can not reproduce this.

**Comment by AdSecIT** [comment]
Thanks for testing it out, I copied your code exactly dbarenholz ( And changed slider to progressBar and put it in a new note, still happens for me )

```meta-bind
INPUT[progressBar(minValue(1), maxValue(10), stepSize(0.1)):pBar]
```

I also tested version 0.10.2 version of the plugin and it occurs, along with having a brand new vault.

I am on Windows 11, however this problems also happens on MacOS and my Mobile app.

**Comment by AdSecIT** [comment]
Just to add, it only seems to occur after going past the number 4 in the progressBar, if I set the limits between 1 and 4 it works fine. however anything more for example min 1 max 5 and go past 4 to 4.1 it bugs out.

**Comment by mProjectsCode** [comment]
Oh yeah sorry, I misread an tested with the slider 😅.
I see the issue with the progress bar on my end. Will fix soon.

**Comment by AdSecIT** [comment]
Thanks, appreciate your hard work.
