### ISSUE TITLE
BUTTONS: Allow using button from another note (by ID)

### ISSUE THREAD

**Issue by buttonpushertv** [mProjectsCode/obsidian-meta-bind-plugin#182]
### Is your Feature Request Related to a Problem?

Not a problem, just a feature missing from the way Obsidian Buttons worked.

### Describe the Feature you'd Like

In Obsidian Buttons, you could create a button on a note and then call it from any other note by using its ID.

With MD Buttons, it seems that you can only use buttons that are created within the same note.

For instance, I have a note in my vault called `Button Master Note`. On this note, I have created several buttons that are referenced throughout my my vault, on various pages, and I only need to define the button a single time on the `Button Master Note` and then it is available to be included on any note by referencing the ID of the button.

Could a feature be added to allow MB Buttons work as Obsidian Buttons did?

**Comment by mProjectsCode** [comment]
This would require a rewrite of how the inline button referencing works.
And it is going to make the entire system a lot more complicated. For now, I am not going to do this.

**Comment by mProjectsCode** [comment]
I am probably not going to implement this. 
Instead, i am considering adding the ability to define buttons in the settings which then can be referenced in notes.
