### ISSUE TITLE
Input Field Template Frustrations

### ISSUE THREAD

**Issue by ProStashio** [mProjectsCode/obsidian-meta-bind-plugin#183]
### Is your Feature Request Related to a Problem?

Sadly, I think the Input Field Template needs some work to make it more user-friendly. Writing code is quite tedious for some, especially me. What makes it even worse is when we have to work in a very narrow window like what we have in the Input Field Templates.

### Describe the Feature you'd Like

I would like to suggest one of two things,

1: The best thing I would personally enjoy is something like a code builder. Where you can click a + button and type in the new thing you want such as "#Person" and then click enter. That way the code would build itself and should work. Then if you needed to remove it, press a x button to remove that input.

2: Alternatively, if that's not possible. Some kind of error message pointing us into the direction of what's gone wrong. So we aren't scrambling for where the error is as for someone newer, it just not saving gives no user feedback.

**Comment by mProjectsCode** [comment]
There were some error messages at some point but i seems like i broke them.

**Comment by mProjectsCode** [comment]
fixed my errors so that the parsing errors show up again in 367bb65

**Comment by mProjectsCode** [comment]
I will improve the UI a bit when I add templates for buttons.

**Comment by ProStashio** [comment]
Okay I wasn't going crazy, as I thought so too

> fixed my errors so that the parsing errors show up again in [367bb65](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/commit/367bb6557700ca65dbdd699b70357e0c754d27ed)

Okay I am not going crazy, I thought I remembered there being

> I will improve the UI a bit when I add templates for buttons.

Perfect, thanks!
