### ISSUE TITLE
Button templates and template UI rework

### ISSUE THREAD

**Issue by mProjectsCode** [mProjectsCode/obsidian-meta-bind-plugin#184]
Related: #182 and #183

**Comment by buttonpushertv** [comment]
Defining buttons within the settings (sort of a global button definition section) is a great way to implement what I was requesting in #182 

Thanks for all you do with this plugin.

**Comment by reorganice** [comment]
Global buttons would be awesome!

I think an extra Ui for that might be too much...

As using the old buttons plugin, we could make a note containing all our button-definitions.
Then we would use/reference them using `BUTTON[test-button]`...
Also there should be a "Templater APPEND Note Action" to append the template underneath this section containing my buttons in use...

For styling purposes classes having names according to the button.id would be the win.

Yes, thank you very much !!

**Comment by mProjectsCode** [comment]
@reorganice this is not a place to put FRs. This is just an issue for me to track what I want to do. If you want me to consider your suggestions, please open separate feature requests on this repo.
