### ISSUE TITLE
api docs

### ISSUE THREAD

**Issue by simonfossom** [mProjectsCode/obsidian-meta-bind-plugin#188]
### Is your Feature Request Related to a Problem?

Sorry if this exists somewhere but I cannot find whre Meta BInd api is documented.

I've been exploring activity tracker example but I don't know how to extend it. There's no mention of these in docs:

- mb.createBindTarget
- mb.inputField.createInputFieldDeclarationFromString
- mb.createTable

### Describe the Feature you'd Like

Complete api documentation

**Comment by mProjectsCode** [comment]
documented as doc comments right [here](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/master/src/api/API.ts)

**Comment by simonfossom** [comment]
oh that's amazing! thank you!
(maybe would be good to at least link it in docs for other users.)
