### ISSUE TITLE
[FEAT] Hide certains metadata properties

### ISSUE THREAD

**Issue by MarcosDantasdeSantana** [mProjectsCode/obsidian-meta-bind-plugin#189]
### Describe the Feature you'd Like

A way to chose specific metadata properties, to not show in the properties.

**Comment by mProjectsCode** [comment]
Modifying the properties display is outside of the scope of the plugin.
If you don't want to store intermediate calculation products in the frontmatter, take a look at [this](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/bindtargets/#1-the-storage-type).
