### ISSUE TITLE
Takes 30s to load on iOS

### ISSUE THREAD

**Issue by giittyy** [mProjectsCode/obsidian-meta-bind-plugin#191]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [X] iOS

### Plugin Version

0.11.0

### Describe the Issue

This may be related to issue 102, but it's really bad for me now all of a sudden and wasn't before. I'm getting reported load times of 100+ ms for meta bind, but truly it's closer to 30s vs 1s without. Not sure what to do to fix. 

### Steps to Reproduce

1. Open app.
2. Wait to load

### Expected Behavior

1-3 second load times

**Comment by mProjectsCode** [comment]
> I'm getting reported load times of 100+ ms for meta bind

Then it's probably related to #102. 

I will close this as a duplicate. Should this issue not resolve itself when #102 is closed, please ping me so that I can reopen this.
