### ISSUE TITLE
cannot use templater in input fileds

### ISSUE THREAD

**Issue by simonfossom** [mProjectsCode/obsidian-meta-bind-plugin#195]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [X] Android
- [ ] iOS

### Plugin Version

0.11.0

### Describe the Issue

When in a text field I trigger templater to insert snippet. the output is added underneath the Meta Bind block instead of in the field.

### Steps to Reproduce

1. Enter a text field
2. Trigger templater template to insert any text

### Expected Behavior

The text should be added in the field where the cursor is.

**Comment by mProjectsCode** [comment]
That sounds like a templater bug. There is nothing that I can change about the pasting behavior of templater.

**Comment by simonfossom** [comment]
FYI it doesn't work with Obsidian native Templates also. just tried.
