### ISSUE TITLE
UX issue with table on mobile

### ISSUE THREAD

**Issue by simonfossom** [mProjectsCode/obsidian-meta-bind-plugin#196]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [X] Android
- [ ] iOS

### Plugin Version

0.10.2

### Describe the Issue

I used altered Activity Tracker table and there are issues

1. although the table is horizontally scrollable, fields have arbitrary width. table is not really usable as is right now
2. command to use template to enter content in the table fields doesn't work or fills under the table although the cursor is in any table field
3. dropdown for time is not usable on mobile (or desktop. it's too long. it should still allow typing it in or implement any common time-picker.

here's the video of how it looks on Android:

https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/8134850/82f27683-6df7-47ff-bce4-fd4911730aa8

If you need any questions or need help let me know.

### Steps to Reproduce

Try Activity tracker note from example vault on mobile.

### Expected Behavior

- Set min width (100px ?) and max width. 
- Fields should be proportional to expected content:
   - numbers should always be fully visible so that column should grow with input
   - text should be wider with eclipses or break in multiple lines
   - etc.
- time input should have stg like ios or android input and be able to also type in the value. it should be one modal (hh:mm) not two. (Added some good examples below)

![android_timepicker_types_diagram](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/8134850/b897fb90-ee7c-4139-8c8d-14e6fbf7f082)
![171391380-dcc40651-d15d-41ac-9592-cf6051107bae](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/8134850/940ade4e-0905-43cd-99dd-e04aba9467f5)
![timepicker---overview](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/8134850/167e5832-ef3f-4c1f-8ddb-778b4075c442)
![Screenshot 2024-01-25 at 20 56 29](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/8134850/fd834df4-2190-419e-975c-1cdde3d384a1)

**Comment by mProjectsCode** [comment]
please open a separate FR for the time input field
