### ISSUE TITLE
Image suggester incompatibility with Image Converter plugin

### ISSUE THREAD

**Issue by Pannerz** [mProjectsCode/obsidian-meta-bind-plugin#198]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.11.0

### Describe the Issue

Unable to alter image sizes with Image Converter plugin and VIEW image metabind 

### Steps to Reproduce

1. Attempting to change image size of an image displayed by`VIEW[!\[\[{art}\]\]][text(renderMarkdown)]` with the plugin Image Converter
2. Image size will not stay altered when reloading page

### Expected Behavior

To be able to alter image size with plugin Image Converter

**Comment by mProjectsCode** [comment]
I haven't tested this, but it seems like a problem with the image converter plugin. It should not touch images that are not part of the normal markdown document.

**Comment by mProjectsCode** [comment]
It seems like that plugin does not work in reading mode and meta bind uses the reading mode renderer for view fields, as that's the only renderer exposed to plugins.
This means that this issue is not on meta bind to fix.

**Comment by Pannerz** [comment]
Many thanks for your reply! I understand
