### ISSUE TITLE
Slider 

### ISSUE THREAD

**Issue by Neal-Specter** [mProjectsCode/obsidian-meta-bind-plugin#201]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.11.0

### Describe the Issue

<img width="787" alt="Screenshot 2024-02-02 at 5 39 05 PM" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/117009901/cee58d37-03cd-4356-a981-a30beef2f1c2">

There are too many decimal places. 

### Steps to Reproduce

Set a step size less than 1 and slowly move the slider. 

### Expected Behavior

I would like the precision to be linked to the step size if it's less than 1. 

Example)
INPUT[progressBar(minValue(0), maxValue(30), stepSize(0.001)):progressVal]
Round the progressVal to the thousandths place.

**Comment by mProjectsCode** [comment]
Already fixed but not yet released, see https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues/180
