### ISSUE TITLE
ClassName not working

### ISSUE THREAD

**Issue by fdg1370** [mProjectsCode/obsidian-meta-bind-plugin#202]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.11.0

### Describe the Issue

ClassName, mb-search-input, not operating as expected. Class mb-search-input is located custom.css. This works in version 0.05.0.  In version 0.11.0, using the following code:  INPUT[text(class(mb-search-input)):SearchInput] does not produce the correct result. 

### Steps to Reproduce

1.  INPUT[text(class(mb-search-input)):SearchInput]
2. In version 0.05.0 the html code is: 
```
<div class="block-language-meta-bind mb-input mb-input-block"> 
	<div class="meta-bind-plugin-input-wrapper">
		<input type-"text" spellcheck="false" class="mb-search-input>
	</div>
</div>
```
4. In version 0.11.0 the html code is: 
```
<div class="block-language-meta-bind mb-input mb-input-block"> 
	<div class="mb-input-wrapper mb-search-input">
		<input type="text" tabindex="0"' placeholder="Text">
	</div> 
</div>
```
6. The ClassName, mb-search-input, is in the wrong location for version 0.11.0

### Expected Behavior

For  INPUT[text(class(mb-search-input)):SearchInput], I expect the html code to be:
<div class="block-language-meta-bind mb-input mb-input-block"> 
	<div class="meta-bind-plugin-input-wrapper">
		<input type-"text" spellcheck="false" class="mb-search-input>
	</div>
</div>

**Comment by mProjectsCode** [comment]
This is intended. For consistency, the class name is always on the wrapper.
You will need to change your snippet to something like this.
```css
.mb-search-input > input {
  /* rules go here */
}
```

**Comment by fdg1370** [comment]
Thank you for your quick response. I made the change to the snippet and it worked.
