### ISSUE TITLE
Give text the option of being a list

### ISSUE THREAD

**Issue by Neal-Specter** [mProjectsCode/obsidian-meta-bind-plugin#204]
### Is your Feature Request Related to a Problem?

I want to have two text boxes, both be used for listing the workouts I did and other details. The problem is when I type in one of the boxes the other gets filled. I know I can make them different YAML but I want them to show up in the same query column.

### Describe the Feature you'd Like

Make an option for the text to be stored as a list item and let cloned text boxes remain empty until another unique list item is typed in.

### Additional Context

Would love it if this could be possible for inline select or other features so that the data type can be changed from text to list.

**Comment by mProjectsCode** [comment]
I am not sure I get what you want to do. Can you share what the YAML should look like?

**Comment by Neal-Specter** [comment]
<img width="794" alt="Screenshot 2024-02-04 at 12 28 14 PM" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/117009901/8e70b832-2620-429b-a8db-0b4fef5553bb">
<img width="648" alt="Screenshot 2024-02-04 at 12 30 22 PM" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/117009901/6e27b67a-e673-4480-a62f-100f2ef78508">
<img width="246" alt="Screenshot 2024-02-04 at 12 28 25 PM" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/117009901/7473fa5e-ee00-4b32-8fb8-b7b1664476d4">


I am hoping that I can copy and past the code snippet and have each new text box and inlineSelect act as one of the items in the YAML list and not automatically copy what was written in the first one. 

Maybe adding something like (class(meta-bind-YAML-list)) could format the output text as one entry in the list. 

Let me know if anything needs more clarification :) Thanks!

**Comment by mProjectsCode** [comment]
you will have to do something like this. (Increment the number in square brackets)

### Fist workout
`INPUT[...:WorkoutTypes[0]]`
`INPUT[...:WorkoutDetails[0]]`

### Second workout
`INPUT[...:WorkoutTypes[1]]`
`INPUT[...:WorkoutDetails[1]]`

### Third workout
`INPUT[...:WorkoutTypes[2]]`
`INPUT[...:WorkoutDetails[2]]`

...

**Comment by Neal-Specter** [comment]
Awesome! Is there I place I should check before coming to GitHub. I don't know how I was supposed to search for this feature. Thanks again :)

**Comment by mProjectsCode** [comment]
There is a page on the docs about bind targets which contains a section on nested metadata.
https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/bindtargets/#3-the-property
