### ISSUE TITLE
Extend text area to width of note

### ISSUE THREAD

**Issue by kmaustral** [mProjectsCode/obsidian-meta-bind-plugin#21]
Thanks for this very useful plugin. 

Is there a way to extend the text area to the width of the note? It is quite narrow and crops most of the text.

**Comment by mProjectsCode** [comment]
A test area within a code block (not inline code blaock) should be full width

**Comment by mProjectsCode** [comment]
The declaration:
![image](https://user-images.githubusercontent.com/61602848/195798568-d296d592-b574-42d3-9d3e-5e602ccfbb16.png)

And the result:
![image](https://user-images.githubusercontent.com/61602848/195798590-6acab871-aa54-4b7f-9dd9-af5897ab874e.png)

**Comment by mProjectsCode** [comment]
also you can resize the text area using that little white thing in the lower right corner

**Comment by kmaustral** [comment]
Thanks. That gives me something to play with.

**Comment by kmaustral** [comment]
Hi. That "little white thing in the lower right corner" seems to have disappeared. I've tried different themes, but it seems not longer available.

**Comment by mProjectsCode** [comment]
Hmm, it is still there for me

**Comment by kmaustral** [comment]
Weird. I'm on 0.4.0 and Obsidian v.1.1.9.  It must be conflicting with another plugin, then.
