### ISSUE TITLE
Add Date and Time as one Variable

### ISSUE THREAD

**Issue by giittyy** [mProjectsCode/obsidian-meta-bind-plugin#217]
### Is your Feature Request Related to a Problem?

No

### Describe the Feature you'd Like

I would like to be able to add date and time as one value and then be able update a property with the current date and time.

**Comment by Neal-Specter** [comment]
Would it be possible to have a text input that can understand general formatting to convert it to a time. 

Example)
input 3:15pm as text and it saves the YAML as 15:15

**Comment by mProjectsCode** [comment]
Detecting arbitrary time formats? No.
Parsing a specific time format? Yes, but I am currently busy with other things on the plugin.

**Comment by mProjectsCode** [comment]
done in 79f9691
