### ISSUE TITLE
What is with all these NULL's sent to the console?

### ISSUE THREAD

**Issue by willasm** [mProjectsCode/obsidian-meta-bind-plugin#219]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.1

### Describe the Issue

I am currently in the process of converting all my files with buttons from the `buttons` plugin to `Meta Bind` buttons. While doing this I was writing a helper js script for my vault so I had the console open while working on that and that is when I noticed all these NULL's being sent to the console from the `Meta Bind` plugin...

![ConsoleNULL](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/94352899/ed0a8f67-58de-4b2d-a8ef-aad3b920095a)

This is where they are coming from...

![ConsoleNULLSource](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/94352899/86bd42a2-bf09-44b1-84c0-6dbb7ef1555f)

Have not looked to closely at the source code yet to see why they are being sent as everything is working perfectly. All my buttons are working flawlessly and I am not seeing any errors or warnings regarding any of the buttons I have created. This is not really an issue as they are just log entries but there sure is a lot of them.

Thanks for the great plugin, William.

### Steps to Reproduce

They are all being sent every time I open a file. I just opened a file with 5 buttons in it and 23 NULL's were sent to the console.
Opening another file with 3 buttons also sends 23 NULL's to the console.
The file I have with the most buttons (16) gives me the same result, 23 NULL's sent to console.

Note that none are sent when switching between notes, only when the note with buttons is initially opened.

### Expected Behavior

I just want to know why they are being sent? All the buttons work perfectly so not really a problem, just curious about them.

**Comment by mProjectsCode** [comment]
yeah, I forgot to remove them from my testing. This is fixed in the latest canary release available through BRAT and will soon be released.
