### ISSUE TITLE
Note picker or suggest notes and typing [[

### ISSUE THREAD

**Issue by Rhydderch** [mProjectsCode/obsidian-meta-bind-plugin#22]
**Is your feature request related to a problem? Please describe.**
I want to be able to link notes

**Describe the solution you'd like**
I can imagine two solutions:
- a specific field type called "note picker": that would let you type the name out and search to find the right note
- or, suggesting notes within a text input once the user types "[[" (but I guess this is much harder to implement)

**Comment by mProjectsCode** [comment]
i am not sure that i understand what you mean.
Do you want a note picker input field? But what should be stored in the metadata then?

**Comment by Rhydderch** [comment]
Ideally, I would like to get note suggestions when typing "[[". In this
way, I don't have to remember the exact name of the note or type it
entirely.

It would be stored in the metadate as [[note title]]

**Comment by mProjectsCode** [comment]
so note suggestions once you type `[[` inside a text field?

**Comment by Rhydderch** [comment]
Yes, either that, or a note picker field (which sole purpose would be to
select a note that would be saved as [[note]]).

(but I haven't coded a plugin for obsidian yet, so I don't know which one
is feasible/possible or easier to implement)

**Comment by mayurankv** [comment]
I think what would be an optimal note picker would be a separate input type which takes options in the obsidian query language. Then the new picker would essentially allow you to choose a file from the results that the query returns and then inserts the file name [[file_name]] with path if duplicates exist (e
i.e. how linking with wikilinks work).

**Comment by ironfroggy** [comment]
A specific note input type would make a lot of sense, but a more flexible suggestion field would also be amazing. An example would be something that works like the `tp.system.suggester()` function in the Templater plugin (https://silentvoid13.github.io/Templater/internal-functions/internal-modules/system-module.html#tpsystemsuggestertext_items-string--item-t--string-items-t-throw_on_cancel-boolean--false-placeholder-string---limit-number--undefined)

It might look something like this?

```
INPUT[text(
suggest(apple),
suggest(orange),
suggest(banana),
):fruit]
```

or, also supporting notes:

```
INPUT[text(
suggestnotes("Recipes")
):recipe]

INPUT[text(
suggestnotes(#bookmark)
):reference]

INPUT[text(
suggestnotes([[Some Note]])
):linkednote]
```

The parameter here would work like the syntax of Dataview's sources.

**Comment by mProjectsCode** [comment]
@ironfroggy 
That sounds like a good idea, i will play around with this a bit.

Since I am not a use of templater, could you provide me with a simple templater script that showcases templaters suggeter?

**Comment by mProjectsCode** [comment]
Since a suggest input field is a bit more complicated, I made it into its own input field.
```
INPUT[suggested(
suggestOption(test), 
suggestOptionQuery(#test)
):suggest]
```
where `suggestOption` adds a simple option and `suggestOptionQuery` is a dataview query only using a dataview source

**Comment by mProjectsCode** [comment]
When a note is selected, it will turn into a link
![image](https://user-images.githubusercontent.com/61602848/205150170-79bc0846-899c-4b42-8720-0a02de5b1e72.png)
and it is saved as a link in the metadata
![image](https://user-images.githubusercontent.com/61602848/205150227-a8b7a938-9caf-45b1-b3c4-70f01732879a.png)

If a normal option is selected, it will be saved and shown as a plain string

**Comment by mayurankv** [comment]
That looks great, thanks!
