### ISSUE TITLE
The returned markdown of a meta-bind-js-view block is not interpreted by Meta Bind

### ISSUE THREAD

**Issue by BibiObscur** [mProjectsCode/obsidian-meta-bind-plugin#222]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.3

### Describe the Issue

The javascript content of a `meta-bind-js-view` block is interpreted as expected, but the string returned by calling the `engine.markdown.create` function is not interpreted by the Meta Bind plugin.

This happens on the exampleVault of the repository
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/7034987/380c6fbb-f5cb-4732-8461-c54c26332279)

### Steps to Reproduce

1. Clone the repository
2. Open the folder "exampleVault" as a vault on Obsidian
3. Install and enable the community plugins "Meta Bind" and "JS Engine"
4. Enable JS Input Field in the Meta Bind plugin options
5. Open the "Advanced Use-Cases.md" file

### Expected Behavior

I expect the plugin to display the Input Field instead of the markdown block `INPUT[number:list[2]]`.
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/7034987/a27eabd0-c49f-4c93-8b88-0de92e501b94)

**Comment by mProjectsCode** [comment]
Huh, I will check that tomorrow.

**Comment by Airtoof** [comment]
Hello,

It's not only with this exemple.
Another exemple with the inline Select.md file. See the picture with ```meta-bind too

![CleanShot 2024-02-19 at 11 52 31@2x](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/160486597/8cc86f63-824c-4ba8-948a-7bfc75c9d6e5)

![CleanShot 2024-02-19 at 11 53 01@2x](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/160486597/71cac0f9-2721-4111-b438-88855826e338)

**Comment by mProjectsCode** [comment]
Fixed in `0.12.4`
