### ISSUE TITLE
Button Builder - Copy to clipboard not working throws o.unload is not a function error

### ISSUE THREAD

**Issue by MRobinson-dev** [mProjectsCode/obsidian-meta-bind-plugin#224]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.4 

### Describe the Issue

![Screenshot 2024-02-19 165436](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/43482652/53781b21-50d3-4542-93f6-0e77d7aa7157)
this is the error thrown when I click the "copy to clipboard" button

### Steps to Reproduce

use the button builder, filled out all of the information,  copy to clipboard but not there

### Expected Behavior

to copy the button definition to the clipboard

**Comment by mProjectsCode** [comment]
fixed in `0.12.5`
