### ISSUE TITLE
Progress Bar Error

### ISSUE THREAD

**Issue by Neal-Specter** [mProjectsCode/obsidian-meta-bind-plugin#226]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.5

### Describe the Issue

I have this progress bar in a template that I use with the templater plugin.
<img width="860" alt="Screenshot 2024-02-20 at 10 40 02 AM" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/117009901/f237f814-039a-4448-89b9-c4ff0bea4c53">

When I run the Templater commands it turns the progress bar into this. 
<img width="690" alt="Screenshot 2024-02-20 at 10 38 52 AM" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/117009901/e910e1e1-4976-4b8b-9fe6-c9b21eb26a49">

### Steps to Reproduce

Have a progress bar in a note with a Templater command. Run the Templater command and the progress bar will error out. 

### Expected Behavior

The progress bar shouldn't error out after running Templater.

**Comment by mProjectsCode** [comment]
What you are seeing is not an error. It simply means that obsidian told meta bind to unload the input field or the note was moved/renamed. Reopening the note should fix this.

**Comment by Neal-Specter** [comment]
> What you are seeing is not an error. It simply means that obsidian told meta bind to unload the input field or the note was moved/renamed. Reopening the note should fix this.

Is it possible to not have this happen while still loading in Templater commands?

**Comment by Neal-Specter** [comment]
Is there a reason that a slider doesn't have this issue but a progress bar does? Could progress be an in line command instead?

**Comment by mProjectsCode** [comment]
> Is there a reason that a slider doesn't have this issue but a progress bar does?

Inline fields and blocks are handled differently by obsidian.

> Could progress be an in line command instead?

No.
