### ISSUE TITLE
No Sync to FrontMatter Variables

### ISSUE THREAD

**Issue by pwfraley** [mProjectsCode/obsidian-meta-bind-plugin#229]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.5

### Describe the Issue

When I add Inputs to my file and bind these to FrontMatter variables, the variable values in the front matter do not get updated

### Steps to Reproduce

Create a New Entry with variables in front matter:

```markdown
---
sleepScore: 0
---
>[!info]+ Schlaf
>```meta-bind
>INPUT[progressBar(title(Schlaf Bewertung), minValue(0), maxValue(5)):sleepScore]
>```
```
Now change the slider value, but the value is never persisted to the sleepScore variable.

### Expected Behavior

The sleepScore Variable gets updated when I change the slider.

**Comment by mProjectsCode** [comment]
I tested your example in a fresh vault and I can't reproduce it.

**Comment by pwfraley** [comment]
I figuered it out:

```
---
created: `<% tp.file.creation_date() %>`
sleepHours: 0
---
>[!info]+ Schlaf
>```meta-bind
>INPUT[progressBar(title(Schlaf in Stunden), minValue(0), maxValue(24)):sleepHours]
>```
```
It seems like, the single ` throws obsidian completely off.  Removing the ` from the created fixed all my issues.
