### ISSUE TITLE
Syncing makes writing long sentences impossible for inline text inputs in source mode

### ISSUE THREAD

**Issue by Rhydderch** [mProjectsCode/obsidian-meta-bind-plugin#23]
- [x] The Plugin is up to date
- [x] Obsidian is up to date

**Describe the bug**
When typing inside a text or text input, the sync messes with the typing experience: a few characters get deleted, which makes writing paragraphs smoothly impossible

**To Reproduce**
1. create an inline text area input field or a code block
2. go to source mode
3. try typing longs sentences
4. you should notice words getting cut as the field gets updated

note: I use obsidian syncing

**Expected behavior**
only update once I stopped writing for x ms.

**Screenshots**

**Occurs on**
- [x] Windows

**Plugin version**
0.3.0

**Additional context**

**Comment by mProjectsCode** [comment]
i can look into this, but i do not have obsidian sync, so I might not be able to reproduce this

**Comment by Rhydderch** [comment]
No worries.

Regarding how your code works, am I correct to think that current it
updates every x ms (based on settings)?

If so, perhaps a fix could be to change it to update x ms after last input
or key press (at least for text fields). Do you think that would be
possible?
If you post a code fix I can try just updating it on my side to see whether
it works, before you commit it to the main.

**Comment by mProjectsCode** [comment]
> If so, perhaps a fix could be to change it to update x ms after last input
or key press (at least for text fields). 

Seems like the best approach atm, but it will break real time sync

**Comment by Rhydderch** [comment]
> Seems like the best approach atm, but it will break real time sync

That's an okay trade-off  for me, but it could be a toggle in the settings? so that only users that use obsidian sync can activate it, if needed

**Comment by mProjectsCode** [comment]
I have a better idea of how to tackle this, but I have been quite busy lately, I hope I can implement and test it over the weekend

**Comment by mProjectsCode** [comment]
> If you post a code fix I can try just updating it on my side to see whether
it works, before you commit it to the main.

I created a fix, you should be able to clone the main branch of the repo and run the plugin from the example vault folder to test it

**Comment by AB1908** [comment]
I can't reproduce the original issue so that I know what to look out for in the updated branch. Can you share a more detailed set of steps or even a recording? I tried `text_area1` and `text1` in source mode but perhaps I'm not doing it correctly.

**Comment by mProjectsCode** [comment]
I will mark this as closed for now
