### ISSUE TITLE
Insert templater template at line X

### ISSUE THREAD

**Issue by lightheaded** [mProjectsCode/obsidian-meta-bind-plugin#231]
### Is your Feature Request Related to a Problem?

I currently have this button in my "Standups" note and it does what I want - it inserts a template (contains today's date and a few headings):

```button
name Add a Day
type line(32) template
action Standup Day
templater True
```

I'd like to replicate the behaviour using Meta Bind. I've considered the following approaches but none give me the result:

1. Use the [templaterCreateNote](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/#templater-create-note-action) action. This creates a separate note. I'd like the button to insert the template at line X.
2. Use the Command Action to bring up the command palette and Input Action to select the "Templater: Open Insert Template modal" action ([like in the example here](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/#input-action)). However, I'm not sure if and how I can send the "Enter" key as an action.
3. Use the [Run JavaScript Action](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/#run-javascript-action) and a script to trigger inserting a templater note, but I can't seem to figure out how to insert text at line X using [JS Engine](https://www.moritzjung.dev/obsidian-js-engine-plugin-docs/guides/usage/).

### Describe the Feature you'd Like

I'd like an action to perform templater template insertion at line X, like [templaterCreateNote](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/#templater-create-note-action). Perhaps add an action `templaterInsertTemplate` where instead `folderName` and `filePath` it accepts a `lineNumber` or similiar parameter.

### Additional Context

Asked for alternative solutions here:
https://forum.obsidian.md/t/insert-templater-template-via-a-button-using-meta-bind/77570

**Comment by mProjectsCode** [comment]
I have something along those lines planned, see #206.

For now, with JS Engine you could read the note's content, then do the inserting (either at a line or replacing a specific comment using something like regexp), and then write the content back to the note.

**Comment by mProjectsCode** [comment]
As for the JS Engine approach - can you point me to a doc/example on how to alter a note outside of the JS Engine block, as most of the examples show?

`context.file` should point at the `TFile` where the calling button is in. You can use that reference to call into the obsidian API, via `app` and modify the file.

**Comment by mProjectsCode** [comment]
> That's great to hear! Let me know if I can help and contribute. E.g. if you have a vision regarding the implementation and can share the idea. I could look into it and try and implement it if I can manage the time.

For the actions other than the regexp replace action the button would need to be aware of it's position within the document. We can get that from the markdown post-processor, but the codebase is currently not set up to pass that around. 

I am currently deep in some refactoring work as I work my way towards version 1.0.0, so it might not be easy to contribute right now, but you can try. If you have any questions regarding contributing, feel free to reach out to me via github or discord.

**Comment by mProjectsCode** [comment]
I implemented everything in #206, but I couldn't figure out how to insert a templater template at a specific line. So for there will only be a normal text insert in the next plugin version.

**Comment by mProjectsCode** [comment]
I figured out how to make the templater API abide by my will.

**Comment by lightheaded** [comment]
Superb! Amazing job! Thank you very much 🙏

Are you aiming for a bigger release, or when would we expect to be able to use the new functionality?
