### ISSUE TITLE
Text area as text input for list input field and editable list items

### ISSUE THREAD

**Issue by giittyy** [mProjectsCode/obsidian-meta-bind-plugin#232]
### Is your Feature Request Related to a Problem?

Yes, I can't edit list items after they have been added to the list and I cannot put paragraphs within list items

### Describe the Feature you'd Like

Be able to change list <input> as a <textarea> instead & also make each of the list items as a <textarea> instead of as just a view so they can be edited without being deleted.

**Comment by mProjectsCode** [comment]
fixed in 9370a2a
