### ISSUE TITLE
Buttons templates periodically get erased

### ISSUE THREAD

**Issue by zephyrdragon** [mProjectsCode/obsidian-meta-bind-plugin#235]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [x] Android
- [ ] iOS

### Plugin Version

0.12.5

### Describe the Issue

Buttons templates periodically disappear from Edit Templates menu, rendering inline buttons useless. This happens several times a day, seemingly at random, regardless of how many times I recreate the templates. May have to do with Remotely Save syncing config directory, although no other plugins I am currently using (about 20) appear to suffer from any similar issues. 

### Steps to Reproduce

1. Create button template in Edit Templates menu, under Button Templates section of plugin settings.
2. Save button template.
3. Wait. Close and reopen Obsidian a few times, go about your day.
4. Inline buttons will eventually report "Button ID not found" error, rendering them useless. Edit Templates menu will no longer display templates.

Again, I suspect this is due to the Remotely Save attempting to sync my config directory (with my mobile phone, for instance, which has this plugin installed, but does not have the existing button templates). I don't mean to place blame, here; I am simply noting that something about the way this plugin saves these button templates seems different than other plugins, and that Remotely Save doesn't very much like it. Rather than save the template files and upload them to the database, it appears to be wiping them out.

### Expected Behavior

Button templates should be saved in a folder that Remotely Save can access, save, and sync across Obsidian installations.

**Comment by mProjectsCode** [comment]
Button Templates are stored in the same file as all other plugin settings. Can you reproduce the disappearance of button templates with sync services disabled?

**Comment by mProjectsCode** [comment]
For my own reference

https://github.com/obsidianmd/obsidian-api/blame/9754fc87dd9a417f198a5cad7f08959206d2f69c/obsidian.d.ts#L3059

https://discord.com/channels/686053708261228577/840286264964022302/1213510590555750482
