### ISSUE TITLE
Style Settings compatibility? 

### ISSUE THREAD

**Issue by Lumireaver** [mProjectsCode/obsidian-meta-bind-plugin#238]
### Describe the Feature you'd Like

I'm having trouble keeping things square and aligned and that's partly because I'm still getting a handle on writing my own snippets. At any rate, I think it would be convenient if we could tweak things though Style Settings since the Meta-Bind elements don't seem to behave the way typical call-outs do.

**Comment by mProjectsCode** [comment]
Honestly, I don't see the benefit of style settings when I factor in that I have to maintain those settings. CSS snippets is the more powerful solution which takes no additional effort for me to maintain.

> since the Meta-Bind elements don't seem to behave the way typical call-outs do.

What do you mean by that? Meta Bind does not use callouts, so why would they not be different?

**Comment by Lumireaver** [comment]
Ah, I was using "callouts" incorrectly to refer to any sort of element that isn't handled exclusively through markdown. My bad. I also understand the burden of maintaining mostly superfluous features, especially in these stages of rapid iteration. 

As a hopefully modest concession, a section on the Meta-Bind Docs that lists the classes I'd need to modify get things looking the way I'd like them to would also be neat. (I haven't found any, but I may also just be looking in the wrong places.)

**Comment by mProjectsCode** [comment]
> a section on the Meta-Bind Docs that lists the classes I'd need to modify get things looking the way I'd like them to would also be neat.

I don't know what you want to change, but you can simply look at the DOM using the devtools and look at the classes the elements have. Then you can write your CSS snippets to target those classes/elements.

If you want a list of CSS classes that meta bind introduces, take a look at the `styles.css` in the repo root.

**Comment by Lumireaver** [comment]
Thanks for that tip. That'll help me figure out precisely what it is I'm doing without having to rely on other peoples' work.

**Comment by Lumireaver** [comment]
I've been able to tweak a lot of things with snippets since you passed along that advice, but I can't seem to find any properties responsible the width of inline text and number inputs. The default values are pretty wide for my purposes so I was looking to shrink them. 

Am I overlooking something, or are these elements not tweakable for some reason?

**Comment by mProjectsCode** [comment]
```css
.mb-input input[type='number'] {
    width: <width in pixels here>px;
}
```

And the same for input type text.

**Comment by Lumireaver** [comment]
Thanks so much for your help so far. As I continue to use Meta-Bind I'm gradually picking up on what sorts of things I can mess with or invent, and how it all interacts with everything else. Hopefully folks with similar questions find this exchange and it helps them learn, too.

My next question is, concerning the Meta-Bind embed—is it possible to embed just the content under a heading rather than a whole note?

**Comment by mProjectsCode** [comment]
> My next question is, concerning the Meta-Bind embed—is it possible to embed just the content under a heading rather than a whole note?

No

**Comment by Lumireaver** [comment]
> No

No sweat, it's always possible to just break things down into several notes and to embed those separately. Thanks for the quick answer.

**Comment by mProjectsCode** [comment]
As I don't plan to add style settings for now, I will close this issue.
