### ISSUE TITLE
Consistent size of text area

### ISSUE THREAD

**Issue by phlind** [mProjectsCode/obsidian-meta-bind-plugin#24]
Would it be possible to add the option to define the width and height af a text area, so that it stays the same size also when switching to another note and back or closing Obsidian? Would be a great addition imo. :)

**Comment by mProjectsCode** [comment]
there already is, you can add a css class name to it using the `class` argument and in that css class you can define the height and width of the input field. The css class needs to be defined inside a theme or snippet

**Comment by phlind** [comment]
Oh, that's nice! :) Sorry then for the feature request.
