### ISSUE TITLE
Buttons cannot Apply to Properties with Spaces in Them

### ISSUE THREAD

**Issue by rchaklashiya** [mProjectsCode/obsidian-meta-bind-plugin#241]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.5

### Describe the Issue

When I attempt to add to a property via a Meta-Bind Button, it fails if there is a space in the name, even when I use syntax like ["<property name>"]. In that case I get this error:

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/18043279/66c8067e-674e-4bfa-bc47-ca77689dc9ad)

### Steps to Reproduce

1. Create a note with a property like "property name" (make sure there is a space)
2. Create a meta-bind button using the meta-bind button builder that appends to the property "property name" and changes it to the number 1
3. The issue should be reproduced

### Expected Behavior

I expect the plugin to use the ["<property name>"] syntax properly to find the property and change its value.

**Comment by mProjectsCode** [comment]
See the last line in the error code block. `bindTarget: ["some prop"]` is an array. Try `bindTarget: '["some prop"]'`.
