### ISSUE TITLE
Built-in method to see all command IDs

### ISSUE THREAD

**Issue by kun-codes** [mProjectsCode/obsidian-meta-bind-plugin#247]
### Is your Feature Request Related to a Problem?

I have installed the plugin for creating button within the notes, but in the documentation didn't have any mention of the command IDs. I had to search it on my own on the internet. 

I found this: [get-command-id](https://forum.obsidian.md/t/how-to-get-technical-names-for-all-commands/47567/3)

### Describe the Feature you'd Like

I would like the plugin to enter a new command in the command palette using which I can search through all the command IDs. It can be like how the present command palette is like, but instead of searching for commands, I can search for command IDs. After I select the command ID, it copies it into my keyboard. Just like how after I press enter on a command on the command palette, it executes the command.

**Comment by kennygokh** [comment]
Hi, I noticed that even with the correct command id place in the code, it is not working. When I press the button, nothing happen whereas it is suppose to run QuickAdd command like creating a new note. I put the snippet of code as below.

```meta-bind-button
style: primary
label: New Meeting Note
action:
  type: command
  command: quickadd:choice:3A33a908e9-d26f-47f3-a4eb-bb03d1ddc170
```

For workaround, I use open link instead. code as below.
```meta-bind-button
style: primary
label: New Meeting Note (WorkAround)
action:
  type: open
  link: obsidian://advanced-uri?vault=My%20Work&commandid=quickadd%253Achoice%253A33a908e9-d26f-47f3-a4eb-bb03d1ddc170
```

**Comment by mProjectsCode** [comment]
@kennygokh does this happen only with the quickadd commands or other commands as well?

**Comment by kennygokh** [comment]
> @kennygokh does this happen only with the quickadd commands or other commands as well?

After I reload obsidian to try again and it seems ok now.
