### ISSUE TITLE
Question: how to change the place of template insertion using the button?

### ISSUE THREAD

**Issue by Fertion** [mProjectsCode/obsidian-meta-bind-plugin#248]
### Is your Feature Request Related to a Problem?

Hi. If I use the buttons plugins button to insert a template, it inserts it right below the button.

I tried to reproduce this functionality in this plugin, but the template is inserted where the cursor is now, which is very inconvenient, because you have to perform additional actions and move the cursor. Is it possible to make the button insert the template right after itself?

### Describe the Feature you'd Like

-

**Comment by mProjectsCode** [comment]
currently no, but it is planned, see #206.
