### ISSUE TITLE
Button ID not found

### ISSUE THREAD

**Issue by Volker-brdb** [mProjectsCode/obsidian-meta-bind-plugin#251]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0,12,5

### Describe the Issue

I define a button on a note in ```meta-bind-button....id: ABC....```-block with e.g. id ABC.
Using `BUTTON[ABC]` on the same note it works, and the button is displayed and functionable
Using `BUTTON[ABC]` on an other note this is resulting an "Button ID not found" - Message

### Steps to Reproduce

- define button in meta-bind-button - block and give it the id ABC
- use `BUTTON[ABC]` on the same note -> see that button is there and does his job
- use `BUTTON[ABC]` on an other note -> Button is showing "Button ID not found"

### Expected Behavior

 use `BUTTON[ABC]` on an other note -> button is there and does his job

**Comment by mProjectsCode** [comment]
Button IDs are scoped to the file.

**Comment by Volker-brdb** [comment]
Ok, got it.
But to be honest I actually can't really see a Use-Case for this.
Anyway thanks for the great plugin

**Comment by mProjectsCode** [comment]
> But to be honest I actually can't really see a Use-Case for this.

Use case for what? The ID being scoped to the file is a technical choice.

**Comment by Volker-brdb** [comment]
Use-Case for having the same button more than one time in an note. 
I tried to get rid of buttons-plugin. What a did there: i have one note where all my buttons are defined. And then I can use them in any other note.
