### ISSUE TITLE
FYI - Norton marks the docs website as dangerous

### ISSUE THREAD

**Issue by Smitty010** [mProjectsCode/obsidian-meta-bind-plugin#254]
### Is your Feature Request Related to a Problem?

Whenever I try to access the document site, Norton blocks this with a message saying this is a known dangerous site.  I don't know any more than that.
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/3760075/223f08a7-3dfb-45c4-9e94-569d33a6c58e)

### Describe the Feature you'd Like

It would be nice if Norton liked you

**Comment by Smitty010** [comment]
I'm not a huge fan of Norton, but it's what I have currently.

**Comment by mProjectsCode** [comment]
It seems like Norton quickly fixed the issue. At least their response time is good.
