### ISSUE TITLE
Set size for textArea

### ISSUE THREAD

**Issue by 000micky** [mProjectsCode/obsidian-meta-bind-plugin#255]
### Is your Feature Request Related to a Problem?

not really a bug, but every time I make a text area, I get this tenny tiny little textArea to type in.  And if I want to write anything more than a sentence or two, I need to manually drag it out to size each time the inline is rendered.

### Describe the Feature you'd Like

Would love to be able to modify the default size, say by px width or percentage relative to page width, or something like that.  I saw that you can modify things with css classes ... but I know nothing about css yet.  Would be an awesome argument to adjust the size of this and other meta-bind objects

**Comment by mProjectsCode** [comment]
I responded in the other issue you commented on https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues/192#issuecomment-1991181392.
