### ISSUE TITLE
Inherit (but override) frontmatter when using Meta Bind Embeds

### ISSUE THREAD

**Issue by scottTomaszewski** [mProjectsCode/obsidian-meta-bind-plugin#257]
### Is your Feature Request Related to a Problem?

Im trying to have default values in a Meta Bind Embed note available in the note that contains the embed.

### Describe the Feature you'd Like

Frontmatter in the note that's embedded should be available to the embedding note, but the embedding note should be able to override fields

### Additional Context

File: `test.md`
```
---
foo: bar
---

~~~meta-bind-embed
[[test2]]
~~~
```

File: `test2.md`
```
---
hey: "rawr"
---

`=this.foo`
`=this.hey`
```
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/5295276/acaaf4c1-bc9d-4962-b9d5-b73ca96479f3)

In this example, I show that `test.md` is unable to display the `rawr` value of the `hey` field since its defined in `test2.md`.  This feature request would allow the `rawr` to display.

**Comment by mProjectsCode** [comment]
This is
1. Not a design goal of the Meta Bind Embed
2. Not trivial and probably not possible using Obsidians API

So this is not functionality that I want to add to the plugin.
