### ISSUE TITLE
Compability with Dataview when using inline buttons => Parsing error

### ISSUE THREAD

**Issue by oschrenk** [mProjectsCode/obsidian-meta-bind-plugin#258]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.5

### Describe the Issue

I see a Dataview error when trying to use inline button:

```
Dataview (inline field '=BUTTON[help-button]=='): Error: 
-- PARSING FAILED --------------------------------------------------

> 1 | =BUTTON[help-button]==
    | ^

Expected one of the following: 

'(', 'null', boolean, date, duration, file link, list ('[1, 2, 3]'), negated field, number, object ('{ a: 1, b: 2 }'), string, variable
```

### Steps to Reproduce

I'm trying to run the "Inline Buttons" example at https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/

I'm using the following text (as in the example) but since I also have Dataview enabled, I'm getting a parser error. 

```
Meta Bind has an in plugin help page. `==BUTTON[help-button]==` Isn't that cool?
```

### Expected Behavior

Show an inline button

**Comment by oschrenk** [comment]
Ugh.

When you copy the example by highlighting with your mouse and then paste.  Something injects `==` as a delimiter around the button when you paste into Obsidian.

You have to copy the example via the button that appears when you hover over the whole example.

**Comment by mProjectsCode** [comment]
I can't reproduce the copying inserting `==`. Are you using safari?

**Comment by oschrenk** [comment]
https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/52898/dca9e347-b3e8-49e7-9c3f-18cd2054e399

Copying from Arc Browser on macOS

1. time pasting is with Cmd+V. Results in `==....==`
2.. time pasting is with Cmd+Shift+V. Result as expected. 

I think because on the website the `inlinecode` block has a background color, and Cmd+V does rich format pasting in macOS, Obsidian interoprets it as highlighted and injects `==` (obsidian markdown syntax for highlighting)

That;s also why it works when using Cmd+Shift+V, which turns off rich formatting when pasting.


It's a macOS  thing. Not sure if it's worth dealing with.

**Comment by mProjectsCode** [comment]
I will forward this to the framework that I am using for the docs. So they can decide if they want to deal with it or not.
