### ISSUE TITLE
FR: Centering Buttons

### ISSUE THREAD

**Issue by hatredholder** [mProjectsCode/obsidian-meta-bind-plugin#262]
### Is your Feature Request Related to a Problem?

I was looking for a way to center the meta-bind buttons. The only idea that came up to my mind is to use a HTML tag with CSS, but couldn't get it to work. 

I tried putting the buttons in a tag like this:
```
<div style="text-align: center;">`BUTTON[yesterday]` `BUTTON[today]` `BUTTON[tomorrow]`</div>
```
This does center the text, but the meta-bind buttons don't render.

### Describe the Feature you'd Like

If there's a way to do this with CSS, please point me on the right path. If not, then an option to **center button** would be super handy.

**Comment by mProjectsCode** [comment]
> This does center the text, but the meta-bind buttons don't render.

You are running into a limitation of Obsidian. Markdown features don't work inside of HTML tags.

You can add CSS classes to the button with the `class` property, [see the docs](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/#button-properties).

**Comment by hatredholder** [comment]
> You are running into a limitation of Obsidian. Markdown features don't work inside of HTML tags.

Oh, I see. That sucks.
> You can add CSS classes to the button with the `class` property, [see the docs](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/#button-properties).

Can I have an example of how would I do that the right way? Everything I tried didn't work.

**Comment by hatredholder** [comment]
> You are running into a limitation of Obsidian. Markdown features don't work inside of HTML tags.

Oh, I see. That sucks.
 
> You can add CSS classes to the button with the `class` property, [see the docs](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/#button-properties).
```
.button {
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}
```
This CSS class worked, thank you for navigating me in the proper direction!
