### ISSUE TITLE
FR: Support for Referencing Other Metadata Fields in `updateMetadata` Action

### ISSUE THREAD

**Issue by Kardzhilov** [mProjectsCode/obsidian-meta-bind-plugin#263]
### Is your Feature Request Related to a Problem?

Currently, the updateMetadata action does not seem to support referencing other metadata fields directly in the value field. This limitation prevents users from performing operations that involve multiple metadata fields.

### Describe the Feature you'd Like

I am currently using the Meta Bind plugin in Obsidian and I've come across a limitation that I believe could be addressed to greatly enhance the plugin's functionality.

Here's an example to illustrate the issue:

`---`
currentHealth: 10
healthMod: 3
`---`
'''meta-bind
INPUT[textArea:healthMod]
'''
'''meta-bind-button
label: "Health Change"
style: default
action:
  type: updateMetadata
  bindTarget: currentHealth
  evaluate: true
  value: x - healthMod
'''
(Substituted the `` for ' to be able to display in code block here)

In this example, I am trying to update the currentHealth metadata field by adding the value of healthMod to it. However, the plugin throws an error saying healthMod is not defined.

I believe it would be extremely useful if the updateMetadata action could support referencing other metadata fields directly in the value field. This would allow users to perform more complex operations involving multiple metadata fields.

### Additional Context

My specific use case for this feature is for creating interactive character sheets for TTRPGs. Being able to reference and manipulate multiple metadata fields would allow for dynamic updates of character attributes such as health, experience points, etc. However, I believe this feature could be beneficial in a variety of other use cases as well, as it would allow users to perform more complex operations involving multiple metadata fields.

**Comment by mProjectsCode** [comment]
This is not something that I plan to support. If you want to do more complex logic than simply setting a value, you should use the JS action. Meta Bind 1.0 will add an API to easily modify the properties from JS.

**Comment by Kardzhilov** [comment]
Looking forward to 1.0 then 👍
