### ISSUE TITLE
dateTime Does Not Work

### ISSUE THREAD

**Issue by giittyy** [mProjectsCode/obsidian-meta-bind-plugin#265]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.5

### Describe the Issue

The error is "encountered invalid identifier."

I have an example vault from here that I'm using. Made sure the plugin was up to date and relaunched Obsidian. Still not working. 

### Steps to Reproduce

Enter in dateTime as an identifier. 

### Expected Behavior

It shows an input for the date and time.

**Comment by giittyy** [comment]
Also, wouldn't mind having it similar to datePicker that just opens a dialogue box and time is also shown.

**Comment by mProjectsCode** [comment]
Because the update that includes the `dateTime` input field has not yet been released...

The example vault is always for the current code version, not the current released version.

**Comment by mProjectsCode** [comment]
You can find the example vault for `0.12.5` [here](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/tree/0.12.5).
