### ISSUE TITLE
Text input argument to store metadata as an integer rather than a string

### ISSUE THREAD

**Issue by Jason-c-o** [mProjectsCode/obsidian-meta-bind-plugin#27]
**Is your feature request related to a problem? Please describe.**
I want to do use the metadata for an array index and this does not accept a string as a parameter.

```
array[bind_target]
```

**Describe the solution you'd like**
Something along the lines of:

```
INPUT[text(number):bind_target]
```
so that `bind_target: 3` instead of `bind_target: "3"`

**Comment by Audio951** [comment]
For what it's worth, if you are also using the Dataview plugin you can do something like this to work with strings as integers:
`$= parseInt(dv.current().some_string_from_metadata)`

It's just inline javascript - perhaps it will help.

**Comment by mProjectsCode** [comment]
i implemented this as a separate input field `INPUT[number:bind_target]`

**Comment by mProjectsCode** [comment]
I will bundle this into the next release
