### ISSUE TITLE
Date Time is limited to Built in Format

### ISSUE THREAD

**Issue by giittyy** [mProjectsCode/obsidian-meta-bind-plugin#270]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.5-canary. 20240324233103

### Describe the Issue

I write my date format like this YYYY-MM-DDTHH:mm:ssZ but inside the dateTime it is formatted as YYYY-MM-DDTHH:mm and so it does not recognize my date and displays a blank and then when I update my date it's in a new format. Is there any way the date format setting can be used to adjust what the dateTime formats and outputs? 

### Steps to Reproduce

Create dateTime input field and if the field isn't in the format that dateTime is written in it does not display it. Output is only written in YYYY-MM-DDTHH:mm format.

### Expected Behavior

dateTime is displayed in format given in the settings and looks for that same format.

**Comment by mProjectsCode** [comment]
The updated `date`, `time`, and `dateTime` input fields use Obsidian provided time and date inputs, so it should be consistent with the native Obsidian behavior.

**Comment by giittyy** [comment]
![dt-1](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/72840497/8f7d009e-f038-4542-a4bd-f33afc2d55d8)
![dt2](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/72840497/5bbab26a-a90b-4842-8526-a2c3f0abcb99)

The issue may be that it's not able to process the Z because even if I change it locally it removes the Z.
