### ISSUE TITLE
The edit button for existing button templates is non-functional in version 1.0.0

### ISSUE THREAD

**Issue by FeralFlora** [mProjectsCode/obsidian-meta-bind-plugin#276]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.0.0

### Describe the Issue

When I try to edit my existing button templates in version 1.0.0, the edit button is functionally unresponsive. The other buttons (copy template, delete template) work as expected.

### Steps to Reproduce

1. Go to Meta bind templates -> Button templates -> Edit templates
2. Press the edit button with a pencil next to an existing button template.
3. Nothing happens.
4. Optionally, reproduce the same thing with the default template that gets added when pressing "Add template", to confirm that it's not the template that's the issue.

I reproduced this in the Sandbox vault with only Meta bind installed

### Expected Behavior

I would expect the button builder modal / interface to open.

**Comment by mProjectsCode** [comment]
oh no, i found like 3 bugs with the button builder modal and the button template settings UI

**Comment by mProjectsCode** [comment]
this should be fixed in version `1.0.1`

**Comment by FeralFlora** [comment]
> this should be fixed in version `1.0.1`

Thanks a lot for the quick fix! I was excited to try out 1.0.0, so I'm glad I can proceed now. Thanks again, for the great work that Meta Bind is!
