### ISSUE TITLE
Add the number field with increment/decrement buttons

### ISSUE THREAD

**Issue by anareaty** [mProjectsCode/obsidian-meta-bind-plugin#284]
### Describe the Feature you'd Like

I would be cool to have a number field with little buttons before and after it, and clicking on one would change the number to number+1 and another to number-1. Sometimes it is more useful to just list between the numbers instead of changing them manually. It can be used, for example, to build pagination or mark progress, etc.

**Comment by mProjectsCode** [comment]
you can already sort of do this with meta bind buttons, see [this example from the docs](<https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/reference/buttonactions/updatemetadata/>).

**Comment by anareaty** [comment]
Thanks, I didn't see that! Though this solution adds a lot of clutter to the source view...
