### ISSUE TITLE
Buttons fantastic!  UX / UI is tricky..

### ISSUE THREAD

**Issue by pachwi** [mProjectsCode/obsidian-meta-bind-plugin#286]
### Is your Feature Request Related to a Problem?

Thank you for extending your plugin with the Buttons feature. 
I have created up to 15 Buttons, (and working on a lot more) this works fantastic!

I love this plugin!

### Describe the Feature you'd Like

From my perspective, the UI/UX is a little “tricky”  and I think with minimal changes it will be much less difficult to understand and to use.
If wanted, I can provide some suggestions.

**Comment by dbarenholz** [comment]
Friendly reminder: if you want things to change, it's useful to let maintainers know _what_ and _why_. Otherwise, we can't do anything with it.

**Comment by pachwi** [comment]
Thanks @dbarenholz, I will prepare something!

**Comment by mProjectsCode** [comment]
I will close this for now. You can reopen this or another issue when you finish your write-up.

**Comment by pachwi** [comment]
@mProjectsCode  Hi Moriz,  here you are...
maybe this helps?
![actual-layout](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/154025604/6ab1f576-8163-4f6a-832d-afd05a1f3556)

**Comment by pachwi** [comment]
![overview](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/154025604/52e703b3-a5a0-4fae-a428-9317d932cf42)

**Comment by pachwi** [comment]
![detail](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/154025604/d4b6b2ec-4a31-46dd-b5fa-ba36a035bab2)

**Comment by mProjectsCode** [comment]
I am just going to list my opinion on your proposed changes in no particular order.
- I don't like expandable sections, I much prefer the button templates to stay a modal.
- I agree that the option to reorder buttons would be a nice feature.
- Moving the YAML preview into the edit modal for the button makes the UI look nicer, but is a UX loss in my eyes, as now you need to open the edit modal to see that a button does.
- The confirm and cancel buttons of the modals are at the bottom to be consistent with the rest of Obsidians styling/design. But having them sticky and always visible sounds like a good change to me.
- A wider modal could be nice. Currently, it's the default modal width, which is determined by the theme that the user is using.

**Comment by pachwi** [comment]
@mProjectsCode  Moritz, thank you so much for your detailed Feedback.
