### ISSUE TITLE
Outputting the bind of a frontmatter property -OF another bind of a frontmatter property as a Number

### ISSUE THREAD

**Issue by Madjest3r** [mProjectsCode/obsidian-meta-bind-plugin#288]
### Is your Feature Request Related to a Problem?

I was trying to make it so that whenever a toggle was on, it would make a view field add a number from a previous field. It looks something like this.

``INPUT[number:STRMOD]``

``INPUT[number:BONUS]``

``INPUT[toggle(offValue({0}), onValue({BONUS})):STRBONUS]``

``VIEW[{STRMOD}+{STRBONUS}]``

Again, if the toggle was off it wouldn't add anything to the "Strength Mod", but if it was on it would add it by whatever I put in as a bonus.

But when I toggled it couldnt convert {STRBONUS} to a number, I tried doing it with an Inline Select input field thinking it was because it was a toggle thing or smth like so.

``INPUT[number:STRMOD]``

``INPUT[number:BONUS]``

``INPUT[inlineSelect(

option({BONUS}, ■),

option(0, ☐)

):STRBONUS]``

``VIEW[{STRMOD}+{STRBONUS}]``

And the same error was printed of that {STRBONUS} cannot be converted to a number

### Describe the Feature you'd Like

Even though it's pretty apparent from my issue, the feature I'd like is to make numerical values be convertible as numbers, even if it's been filtered through multiple binds, which... sounds like it'll be more of an issue that is way more complicated to workout than expected.

**Comment by mProjectsCode** [comment]
If I understand you correctly you are asking for dynamic argument values. As stated in other issues and discussions, this will not happen for a multitude of reasons.

But you can try this setup, with an additional helper property.

`INPUT[number:STRMOD]`

`INPUT[number:BONUS]`

`INPUT[toggle(offValue(0), onValue(1)):ADDSTRBONUS]`

`VIEW[{STRMOD} + ({ADDSTRBONUS} * {BONUS})]`
