### ISSUE TITLE
Inline code block bug for input types in combination with dataview inline notation

### ISSUE THREAD

**Issue by Morekon** [mProjectsCode/obsidian-meta-bind-plugin#29]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
There seems to be a problem for inline code blocks in combination with dataview inline brackets.
Whenever I use inline brackets after the first line in a code block the data is not bound and the input is broken.
This is true for all inline input types of the meta-bind plugin.

**To Reproduce**

````
```ad-bug
Correct: [T1::`INPUT[basic_slider][:t1]`]

Incorrect: [T2::`INPUT[basic_slider][:t2]`]

Correct: T3::`INPUT[basic_slider][:t3]`
```
````
**Expected behavior**
Every dataview inline value input acts as T1 given in the example.

**Screenshots**
![image](https://user-images.githubusercontent.com/115999613/204112534-c47ab3a1-64b1-4cc3-a28e-82dae6f1da10.png)

**Occurs on**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.3.2

**Additional context**

**Comment by mProjectsCode** [comment]
Yes, the styling seems wrong. It not being bound is because the plugin can't bind to dataview inline fields, only to frontmatter fields, but that might change when dataview releases its inline field parser for other plugins to use.

**Comment by mProjectsCode** [comment]
the styling issues come from dataview putting the input field inside of a span tag

**Comment by Morekon** [comment]
> Yes, the styling seems wrong. It not being bound is because the plugin can't bind to dataview inline fields, only to frontmatter fields, but that might change when dataview releases its inline field parser for other plugins to use.

How so? The first line T1 is bound even though using dataview inline fields. And with bound I also refer to the front matter. T2 can not bind to the front matter somehow.

**Comment by Morekon** [comment]
> the styling issues come from dataview putting the input field inside of a span tag

But why does it work for the first dataview inline field?

**Comment by mProjectsCode** [comment]
![image](https://user-images.githubusercontent.com/61602848/204131202-c00a53c6-4fba-4e8e-99ad-4a1cc0ca5899.png)
for me, both are linked, and the styling is broken on both, but the third example somehow doesn't render
```md
> [!INFO]
> Correct: [T1::`INPUT[slider:t1]`]
> Incorrect: [T2::`INPUT[slider:t2]`]
> Correct: T3::`INPUT[slider:t3]`
```
it would help if you could look into the dev console (`ctrl+shift+i` on windows) for any errors

**Comment by mProjectsCode** [comment]
> but the third example somehow doesn't render

it seems like, for me dataview overrides the input field with a `code` element

**Comment by mProjectsCode** [comment]
> and the styling is broken on both

ok i managed to reproduce your exact problem with the styling working on the first one
![image](https://user-images.githubusercontent.com/61602848/204132140-f61dec55-81d5-4886-ab72-278112bdeca9.png)
honestly, i have no idea what is wrong there, maybe i need to ask someone with more CSS experience

**Comment by mProjectsCode** [comment]
ok i am more than confused... once there is an empty line in the code block, the styling on all following sliders inside of dataview inline brackets are broken, but the one without the brackets starts magically working...

**Comment by mProjectsCode** [comment]
but at least it is not limited to only sliders, but every input field breaks under these conditions

**Comment by Morekon** [comment]
Yes exactly. Thanks for reopening the issue.
I also do not understand why it only breaks for dataview inline brackets even though the first line seems to work.
Yes sorry I forgot to write that it applies to all input fields.

**Comment by mProjectsCode** [comment]
Fixed it, it had to do with the order in which the markdown post processors were applied. By just giving it a higher sort order (so that it gets applied later) the problems went away.
