### ISSUE TITLE
add `hidden` option to js view fields

### ISSUE THREAD

**Issue by mProjectsCode** [mProjectsCode/obsidian-meta-bind-plugin#293]

**Comment by PippoGot** [comment]
Is it possible to bind the value of a (boolean) property to the hidden function ? I'd like to obtainsomething like this:

# Visible case
---
visibility: true
---

`VIEW[TEXT][text(hidden(visibility))]` (in this case the read mode displays TEXT)

# Hidden case
---
visibility: false
---

`VIEW[VISIBLE TEXT][text(hidden(visibility))]`  (in this case the read mode displays nothing)
