### ISSUE TITLE
Add hotkey to meta-bind action 

### ISSUE THREAD

**Issue by bornabare** [mProjectsCode/obsidian-meta-bind-plugin#295]
### Is your Feature Request Related to a Problem?

I want to minimize number of steps to getting a certain end result. 
With meta-bind, I am happy to create buttons in certain pages. Im always frustrated when I cannot find the page where cetain button is placed. 

### Describe the Feature you'd Like

To make the process of getting to an action that is bound to the button on some page more streamlined, I propose a featture that will enable binding meta-bind into a hotkey in obsidian vault.

**Comment by mProjectsCode** [comment]
This is not feasible, as buttons are only loaded when the note is open.

Something that might help you is putting all your important buttons in a note and then moving that to the sidebar.
