### ISSUE TITLE
Issue with multiplication with the math function.

### ISSUE THREAD

**Issue by Sindri17** [mProjectsCode/obsidian-meta-bind-plugin#299]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [x] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.0.4

### Describe the Issue

Hello I'm very new to all this but when trying to do the "view math" function it does not work for multiplication.
![Example(edit)](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/166662837/8d7447ab-2577-401b-a58c-e2c4dd25d666)
![Example(preview)](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/166662837/757b944e-c74b-4983-989d-ee1c2fda79db)
Thank you for your time.

### Steps to Reproduce

Copy & paste this into obsidian. (?)

`VIEW[{Example}*20][math]`

### Expected Behavior

I expected a return value of 20

**Comment by mProjectsCode** [comment]
Disable the iconzie plugin.

**Comment by mProjectsCode** [comment]
see https://github.com/FlorianWoelki/obsidian-iconize/issues/438

**Comment by Sindri17** [comment]
Oh I see I did disable it before but I did not refresh the program so I didn't it resolve. Thank you!
