### ISSUE TITLE
Please give examples for icons

### ISSUE THREAD

**Issue by dxcore35** [mProjectsCode/obsidian-meta-bind-plugin#305]
### Is your Feature Request Related to a Problem?

icon?: string; // An optional lucide icon to display on the button

### Describe the Feature you'd Like

Please provide examples in documentation there is no single example

**Comment by I-Pch** [comment]
Here's an example using an icon 😊 (in case it helps) : 

````javascript
```meta-bind-button
label: Open Today
icon: calendar
hidden: false
class: ""
tooltip: ""
id: ""
style: primary
actions:
  - type: command
    command: daily-notes
```
````
`calendar` is one of the lucide-dev icon available within Obsidian out of the box. 

AFAIK, Obsidian isn't necessarily up-to-date with the latest version of lucide dev icons library available... so I think that not all lucide dev icons can be referenced in this way 😇. 

For the unavailable/custom ones, I can only guess they can be used/added using a CSS `class`  though 🤔.

**Comment by dxcore35** [comment]
Thank you very much. Is here some list of keywords (like calendar) that can be used to get icons?

**Comment by I-Pch** [comment]
> Thank you very much. Is here some list of keywords (like calendar) that can be used to get icons?

Yes, sorry 😅 , I was just editing my previous reply as it occurred to me that I skipped that info 🙈 : 

You can look for an icon to use here: https://lucide.dev/ ... and then, just grab its name to use in the button 😊 .
(This is what `calendar` was in the example I shared, the name of the icon).

I don't know if all icons you'll find on the website will work (as I don't know, maybe Meta Bind uses a more recent version of the lucid dev icon library than the one Obsidian currently uses)... but so far, I didn't had any troubles with that 😊 .

**Comment by dxcore35** [comment]
I really hope your comments will become part of the official documentation! Thank you very much for your time here

**Comment by dxcore35** [comment]
I really hope your comments will become part of the official documentation! Thank you very much for your time here
