### ISSUE TITLE
Emoji as icon

### ISSUE THREAD

**Issue by dxcore35** [mProjectsCode/obsidian-meta-bind-plugin#306]
### Is your Feature Request Related to a Problem?

icon?: string; // An optional lucide icon to display on the button

### Describe the Feature you'd Like

Please allow to show emoji as icon. Not everybody has lucide icon packs, and want it. But eveybody has emoji.

**Comment by mProjectsCode** [comment]
If you want emojis you can simply use unicode emojis in the button label. Lucide icons are shipped as part of Obsidian, so you already have them.
