### ISSUE TITLE
MB_UNLOADED appears on every rename or move of a note

### ISSUE THREAD

**Issue by martyn0ff** [mProjectsCode/obsidian-meta-bind-plugin#314]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [x] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [X] Linux
- [ ] macOS
- [x] Android
- [ ] iOS

### Plugin Version

1.1.0

### Describe the Issue

Hey,
First of all thank you for this awesome plugin. It is essential to my Obsidian flow.

I've been experiencing appearance of `[MB_UNLOADED]` on all items produced by Meta Bind when I either rename a note or move a note (programmatically or not). Reloading the note does help. At first I thought that some plugin interferes with MB, but I've just tried to reproduce this on brand new vault and behavior is the same. That would be great to have a checkbox for force reload of a note where MB items are present when note is renamed or moved.

### Steps to Reproduce

1. Create brand new vault (Obsidian v1.5.12)
2. Install Meta Bind from Community Plugins
3. Embed a button (any button, action does not matter)
4. Rename a note
5. Observe `[MB_UNLOADED]` appearing after  rename (in **Edit mode only**, preview mode functions normally)

### Expected Behavior

`[MB_UNLOADED]` does not appear on rename or on note move.

**Comment by mProjectsCode** [comment]
This is intended behavior. Fields save a reference to the file path that they are in. After a rename this file path would be invalid and things relying on said path might produce incorrect results.

**Comment by Kainkun** [comment]
@mProjectsCode any suggestions for making this work with Templater?
I don't think I can set the name for a created template before the meta bind stuff tries to load?

**Comment by martyn0ff** [comment]
@mProjectsCode  but wouldn't it make sense to reload current note after the rename? Or at least provide an option to turn this feature on? From the docs that you provide this  was not clear that this is intended behavior. I thought that something interferes with your plugin. IMO this gives much better UX than having to do this manually.
@Kainkun I'd look into integrating programmatic reload of a note with `app.workspace.activeLeaf.rebuildView()` as a workaround. Maybe delay that for a few ms.

**Comment by ytmaps** [comment]
I also encountered the same problem, which is of great significance to my workflow. I would like to ask, have you found a solution? @martyn0ff

**Comment by mProjectsCode** [comment]
related issue #396 

I am currently planning an update to some core parts of the code base that should hopefully allow for this behavior to be "fixed".

**Comment by sirlancelot** [comment]
This is currently affecting me on Windows. Should this issue be re-opened?

The workaround described above by @martyn0ff works for me for now, and I've wrapped it up in to a small helper function in my vault so that I can remove it when this issue gets fixed:

![image](https://github.com/user-attachments/assets/0079654e-9ec4-4558-a269-8a26df708598)

![image](https://github.com/user-attachments/assets/4379033b-deda-4423-b3e7-aed36a67ebaf)
