### ISSUE TITLE
Append/Prepend template

### ISSUE THREAD

**Issue by mnaoumov** [mProjectsCode/obsidian-meta-bind-plugin#315]
### Describe the Feature you'd Like

The plugin [Buttons](https://github.com/shabegom/buttons) is deprecated and current plugin is recommended instead.

However it has some features that current plugin is currently missing, `append template` and `prepend template`.

The closest the current plugin has is [Insert Into Note Button Action
](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/reference/buttonactions/insertintonote/)

However it requires explicitly specifying the `line` argument which is quite inconvenient. We need to be able to omit the `line` argument and use `prepend` or `append` instead to insert before/after the button itself

**Comment by mProjectsCode** [comment]
duplicate of #296, see the design idea posted there.
