### ISSUE TITLE
update js view bindings to use format of bind targets

### ISSUE THREAD

**Issue by Shyclops** [mProjectsCode/obsidian-meta-bind-plugin#318]
### Is your Feature Request Related to a Problem?

I can't run javascript code that targets another notes metadata in a meta-bind-js-view

### Describe the Feature you'd Like

I would like the data-view-js-view binding section of the plugin to accept and use the binding format specified on the [binding targets](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/bindtargets/) page

An example would be
```meta-bind-js-view
{NOTE_A#PROPERTY_1} as prop1
---

return prop1
```

**Comment by mProjectsCode** [comment]
It already works that way.

**Comment by Shyclops** [comment]
aaah i see
my trouble comes from the fact that i'm referencing a variable for my page

so an example of what i'm doing would be 


---
NOTE_LINK = [[PageA]]
---

```meta-bind-js-view
{NOTE_LINK} as note
{note#PROPERTY_!} as prop1
---

return prop1
```

**Comment by mProjectsCode** [comment]
see the advanced use case section in the docs

**Comment by Shyclops** [comment]
Neither of the advanced samples returns the value stored which I need as I have some logic that I would like too check against the valu dynamically.

-------- Original Message --------
