### ISSUE TITLE
Error in Insert Into Note Button Example - can not parse button config

### ISSUE THREAD

**Issue by ruxi** [mProjectsCode/obsidian-meta-bind-plugin#320]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.0

### Describe the Issue

I get a `[META_BIND_ERROR]` when I try to run the [insert into note button example](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/reference/buttonactions/insertintonote/)

Here is the details of the error:

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/6733446/0b798c28-0f2f-45b3-b85f-e08796fb2716)

---

I've tested this in an empty vault with just the `Meta Bind` community plugin

### Steps to Reproduce

1. Open a new note
2. Insert the following code block

```meta-bind-button
style: primary
label: Insert Into Note
action:
  type: templaterCreateNote
  line: 3
  value: "Hello, world!"
  templater: false
```

### Expected Behavior

I expected the string "Hello, world!" to be inserted under the button

**Comment by mProjectsCode** [comment]
updated the docs to fix this
