### ISSUE TITLE
It would be great if there was a way to use meta variables to define minValue() or maxValue()

### ISSUE THREAD

**Issue by Geohexamon** [mProjectsCode/obsidian-meta-bind-plugin#323]
### Is your Feature Request Related to a Problem?

I'm using obsidian to keep track of information related to our tabletop game. one thing I like is having a box so you can edit things like current HP for the character. For style I have a slider next to it to act like an HP bar. Unfortunately right now I have to define what the Max HP is in two places to achieve this effect.

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/13168509/40ec12cd-b541-45ba-8dbe-204b4a3fcf5b)

![image_2024-05-15_150333904](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/13168509/652a7095-985b-4579-936d-4226beb05802)

### Describe the Feature you'd Like

I'd like to be able to call meta variables to define the bounds of maxNumber() sorta like how I can grab it via VIEW[]. It would probably look something like this: 

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/13168509/de879c37-3182-455f-bc24-a363c192fcf8)

With it setting the number to whatever the user defines in the Meta under maxHP. In my case here it would be 17. Naturally this would apply to Progress Bars as well.

**Comment by mProjectsCode** [comment]
If you want something like this, you need to create the input fields dynamically, like in the advanced examples in the docs.

**Comment by Geohexamon** [comment]
I hate to ask, but is there a way to cleanly use dynamic input fields in a table as shown in the example? The examples in the doc show it using codeblocks and I've not been able to figure out who to put a code block in a table.
