### ISSUE TITLE
Editor autopoulates link suggestions when typing [[ first

### ISSUE THREAD

**Issue by giittyy** [mProjectsCode/obsidian-meta-bind-plugin#324]
### Is your Feature Request Related to a Problem?

Yes, when I type in the editor a link I want it to autopoulate with possible files. So usually what I end up having to do is write in the file and then copy and paste what I wrote into the editor field

### Describe the Feature you'd Like

Using editor do the same thing obsidian does when typing a link where it auto shows you possible links as you type them.

**Comment by mProjectsCode** [comment]
elaborate more please, where do you want this to show?

**Comment by giittyy** [comment]
[metabindeditorfix.pdf](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/files/15365631/metabindeditorfix.pdf)
[nonmetabindeditorfix.pdf](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/files/15365633/nonmetabindeditorfix.pdf)

**Comment by giittyy** [comment]
![metabindeditorfix](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/72840497/669442c4-6708-4e5f-8ecc-092676922411)
![nonmetabindeditorfix](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/72840497/8f40ec9e-8e3e-4432-9fd5-9d97523ad6ea)

**Comment by mProjectsCode** [comment]
Current;y the editor input is just a simple text area. It is not feasible to add such auto-completion to it. I might rewrite the input field to use obsidians markdown editor, but I will track that in a separate issue.
