### ISSUE TITLE
Is it possible for the `filename` of `TemplaterCreateNoteButtonAction` to be based on an `INPUT[text]`

### ISSUE THREAD

**Issue by RayBB** [mProjectsCode/obsidian-meta-bind-plugin#328]
### Describe the Feature you'd Like

The title says it all.
I want to have a text field where I can enter something like XYZ and then press a button and it creates a new note with the text from that field.
Is this possible?

Based on the docs I don't think so but maybe I'm just not putting 2+2 together here.

### Additional Context

Thanks for all your hard work, this is an awesome plugin :)

**Comment by mProjectsCode** [comment]
you need to create the button dynamically, similar to the the advanced examples in the docs

**Comment by RayBB** [comment]
For anyone that want to know how to do this in the future here is the answer:
[inputTextButton.md](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/files/15388258/inputTextButton.md)

<img width="339" alt="image" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/921217/88b08b9b-65de-4bc7-8b08-977636e709c3">


I'd like to add this to the docs in the future.
