### ISSUE TITLE
Button: Custom Icons

### ISSUE THREAD

**Issue by giittyy** [mProjectsCode/obsidian-meta-bind-plugin#329]
### Describe the Feature you'd Like

Custom Icon in the button. I have custom icons i would like to add to the buttons. If I use Iconize(plugin) buttons in the label they duplicate and before that I was using Icon Shortcodes(plugin) in the label and now that's totally broken. Even if its not through those other plugins just a way to add custom icons to the button would be awesome.

**Comment by mProjectsCode** [comment]
Have you read the docs? There is an option for icons.
https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/#button-properties

**Comment by giittyy** [comment]
“An optional lucide icon to display on the button“

I’m trying to add custom icons like svg or png files that I upload. Iconize plugin allows me to upload a custom icons if I put that in the label area it duplicates the icon.

**Comment by mProjectsCode** [comment]
Not sure that I want to support custom icons. Probably not.
What ever iconize does wrong is a problem with iconize.
