### ISSUE TITLE
Slider label not working 

### ISSUE THREAD

**Issue by chrisnet123** [mProjectsCode/obsidian-meta-bind-plugin#330]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.0

### Describe the Issue

Slider label not showing up:

`INPUT[slider(addLabels, showcase, minValue(0), maxValue(100)):slider2]`
`VIEW[{slider2}]`

```meta-bind
INPUT[slider(addLabels, minValue(-20), maxValue(20)):slider3]
```

### Steps to Reproduce

`INPUT[slider(addLabels, showcase, minValue(0), maxValue(100)):slider2]`
`VIEW[{slider2}]`

```meta-bind
INPUT[slider(addLabels, minValue(-20), maxValue(20)):slider3]
```

### Expected Behavior

Should show a label

**Comment by mProjectsCode** [comment]
I can't reproduce this. The labels show for me as expected.
