### ISSUE TITLE
Advanced Use-Cases first example doesn't work

### ISSUE THREAD

**Issue by RayBB** [mProjectsCode/obsidian-meta-bind-plugin#332]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.0

### Describe the Issue

When I copy the advance use case for "Dynamic Bind Targets with JavaScript" it doesn't show the bottom part (number input).

I'm not sure if I have something wrong, as the JS-engine is installed and enabled.

https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/advancedusecases/

### Steps to Reproduce

1. Create a new file
2. Paste in the example from [here](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/advancedusecases/)
3. Observe that no INPUT[number] is shown

<img width="946" alt="image" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/921217/eb16f08a-ef54-49c6-979a-031c5cbf0036">
<img width="962" alt="image" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/921217/edba29cc-47a4-426a-a2a7-6403fbf56f2d">

Apologizes if I'm just not understanding how the example should work.

When I edit the note to have a simple  `INPUT[number:list[1]]` as I think it is trying to create, it renders fine.

Thanks for helping me understand.

### Expected Behavior

It should show the number input.

**Comment by Geohexamon** [comment]
Did you make sure to enable JS input fields in the Meta Bind settings? Also to have JS Engine enabled.

**Comment by RayBB** [comment]
@Geohexamon thank you for patiently helping me... I didn't see that in the docs.

So I opened a PR to add it to the place in the docs where it might be most useful :)

https://github.com/mProjectsCode/obsidian-meta-bind-plugin-docs/pull/9
