### ISSUE TITLE
Add example of accessing `memory` and `globalMemory` for `View Fields` page

### ISSUE THREAD

**Issue by RayBB** [mProjectsCode/obsidian-meta-bind-plugin#335]
### Describe the Feature you'd Like

It took me a while to piece together the docs here
https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/viewfields/#examples
and here
https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/bindtargets/

To figure out that accessing a globalMemory bind type is as simple as:
```
`INPUT[text:globalMemory^inputText]`

\`\`\`meta-bind-js-view
{globalMemory^inputText} as title
\`\`\`
```

It would be nice to add to the docs on the View Fields page.

**Comment by LynetteCullens** [comment]
How do we access it in js engine?

**Comment by mProjectsCode** [comment]
via [`getMetadata`](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/api/classes/obsidianapi/#getmetadata) from the meta bind api
