### ISSUE TITLE
Document default `storagePath` on Bind Targets page

### ISSUE THREAD

**Issue by RayBB** [mProjectsCode/obsidian-meta-bind-plugin#336]
### Describe the Feature you'd Like

https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/bindtargets/

This page says
> The following bind target will always use the default storage type frontmatter

However, it doesn't list the default storagePath (such as when using Memory). I assume that it is the current file but it would be good to make it explicit.

Thanks again for all your work on this :)
I hope my opening of issues and PRs isn't too overwhelming. Just wanna do my part to improve the docs while I'm with fresh eyes and the issues are popping out at me.

**Comment by mProjectsCode** [comment]
https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/bindtargets/#2-the-storage-path

here it says
> The storage path usually points to a file. If it is omitted, the current file is used.

**Comment by RayBB** [comment]
Would you accept a PR to update it to use the word default?
I see that it says it but to me, it is easy to miss.

If not, feel free to close this issue.

**Comment by mProjectsCode** [comment]
Feel free to make a PR

**Comment by RayBB** [comment]
PR created https://github.com/mProjectsCode/obsidian-meta-bind-plugin-docs/pull/10
