### ISSUE TITLE
Variable Length of input field

### ISSUE THREAD

**Issue by ArneNostitz** [mProjectsCode/obsidian-meta-bind-plugin#337]
### Is your Feature Request Related to a Problem?

Input fields a quite narrow, 15-18 characters. thats too narrow for most of my usecases. 

### Describe the Feature you'd Like

it would be nice to have longer input fields, or define a wider length in the options page or in the field settings. either a char length or a simple width setting (100% of line length, fit line length, ...)

**Comment by mProjectsCode** [comment]
You can already do this via CSS and the `class` argument.

**Comment by ArneNostitz** [comment]
amazing!! thanks for the fast response - sorry for my blindness

**Comment by cheezopath** [comment]
> amazing!! thanks for the fast response - sorry for my blindness

hello! I'm up against the same problem. I'm having trouble finding exactly what css property to change the input field width, even knowing about the class argument. Would it be possible to see your snippet?
