### ISSUE TITLE
Time input on mobile only working in reading view and not in editing view

### ISSUE THREAD

**Issue by TtForge** [mProjectsCode/obsidian-meta-bind-plugin#339]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Android
- [ ] iOS

### Plugin Version

1.1.0

### Describe the Issue

When using the time input field button, nothing happens when pressed unless I'm in reading mode. This started happening when I updated to a new version some weeks ago, when the buttons got redesigned, worked fine as a typed input before then. I can edit the time that is shown in the properties, but I can't open the android clock thing unless I'm in reading mode.

### Steps to Reproduce

Simply just the time input field `INPUT[time]`, nothing happens when pressed in editing mode, only opens the android clock screen in reading mode.

### Expected Behavior

Works as intended in reading mode, so I would hope the exact same in editing mode.

**Comment by mProjectsCode** [comment]
Can reproduce, no idea why it is happening though. I need to take a closer look some other time.

**Comment by anareaty** [comment]
I have the same issue on Windows whith date, time and datetime inputs.

**Comment by mProjectsCode** [comment]
seems like my fix works
