### ISSUE TITLE
Button updateMetadata bindTarget should default to the active file, not the button file

### ISSUE THREAD

**Issue by tim-barnes** [mProjectsCode/obsidian-meta-bind-plugin#342]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.0

### Describe the Issue

Run a 2 step button:
1. Create a new file
2. updateMetadata to add a new tag to the frontmatter 

### Steps to Reproduce

Example button (uses unique note creator core plugin) - similar behaviour with new note or templater:

```meta-bind-button
label: New Example Note
hidden: false
tooltip: Create a new example note
id: newExampleTest
style: default
actions:
  - type: command
    command: zk-prefixer
  - type: updateMetadata
    bindTarget: tags
    evaluate: false
    value: "#example"
```

When run, the note containing the button gets the `#example` tag

### Expected Behavior

The new note created at step 1 gets the updatedMetadata, ie the default `bindTarget` is the new file created.

**Comment by mProjectsCode** [comment]
This is intended behavior. If no file is specified, it will default to the file that the button is in.

**Comment by mProjectsCode** [comment]
It is true that the docs use the wording "current file" which is not optimal.

**Comment by tim-barnes** [comment]
So just to be clear.  Action one replaces the *current file* in the current tab, and then action 2 acts on a file that is now closed. And this is intended behaviour.

Shame, this would have been so powerful had it work the way intuition suggested.
