### ISSUE TITLE
Button `insertIntoNote` below button

### ISSUE THREAD

**Issue by Tejeev** [mProjectsCode/obsidian-meta-bind-plugin#345]
### Is your Feature Request Related to a Problem?

I can't use an `insertIntoNote` button in a dynamic document because line numbers change

### Describe the Feature you'd Like

Insert templates in a new line below the button

**Comment by mProjectsCode** [comment]
duplicate of #296

**Comment by Tejeev** [comment]
Sorry, I missed that issue.
Thank you!
