### ISSUE TITLE
Button doesn't work with multi-column layout(using snippet with multi-column support through callouts)

### ISSUE THREAD

**Issue by OB0NE** [mProjectsCode/obsidian-meta-bind-plugin#349]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.1

### Describe the Issue

I have read the related  #208 #79 #88, which use plugins rather than snippets. I took the tip from #88
> my tip is to use a theme or snippet with multi-column support through callouts. All those multi-column plugins that change the document flow seem to break other plugins in all kinds of strange ways.

So I use a snippet that uses callouts to support multi-columns. And the button doesn't work in the sub-callout(which displays as a column):
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/144986313/ead0b841-9c2a-4547-9e31-c239550ff9c4)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/144986313/2e3c76ca-dcc1-48ff-93f9-dcbd7b5595b7)
But the inline button works:
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/144986313/2e1c7b05-4395-492a-bc60-d944a9750e8e)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/144986313/a931fb14-331d-4b0d-af47-3b0c4d911392)

### Steps to Reproduce

1. Install snippet from https://efemkay.github.io/obsidian-modular-css-layout/multi-column/
2. Create a new note
3. Using callouts to create a two-column layout
4. Create a button in one of the column
5. See the error

### Expected Behavior

In the original plugin "Buttons" by Sam Morrison the button works in multi-column layout. So if it works, it should look like this:
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/144986313/a6f8545d-480d-4972-b2cf-9ffc1ae545a3)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/144986313/aff8a2f6-dc33-4f52-8fd9-2a5b0f97578e)

**Comment by mProjectsCode** [comment]
What is the error message when you click on the error?

**Comment by OB0NE** [comment]
> What is the error message when you click on the error?

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/144986313/d53180df-bb68-4324-82f8-e6a2b7c64f39)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/144986313/52a33368-b017-45f7-a43b-cfc47b0a88dd)

**Comment by mProjectsCode** [comment]
Surround the command with quotes. You have, as the error message says, invalid YAML.

**Comment by OB0NE** [comment]
> Surround the command with quotes. You have, as the error message says, invalid YAML.

I think you are right! I chose the button which creates a new note, and it works:
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/144986313/fe762ded-195f-40f8-ab53-ebd70cf57b6b)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/144986313/697eecca-1355-4f7a-923d-b3b3415dc4e6)
