### ISSUE TITLE
Feature Request: Enable first column as Sunday in Date Picker

### ISSUE THREAD

**Issue by Chris-Andrews** [mProjectsCode/obsidian-meta-bind-plugin#35]
Hello and thank you for creating this plugin. I think a nice feature would be able to display the date picker calendar with Sunday in the first column (currently Monday appears first). I believe the convention for the which day appears first in a calendar view varies regionally.

An ideal solution would enable a preference (similar to the "Use US date input field order") that allows the user to choose between which day appears first in the date picker calendar view. I checked the popular "Calendar" plugin settings, and that plugin allows users to choose between "Locale default" or any specific day. I'm not sure of a use case for other days besides Sunday or Monday, but that could potentially be useful to some users as well.

**Comment by mProjectsCode** [comment]
> I believe the convention for the which day appears first in a calendar view varies regionally.

Correct, I am from Germany and here the week starts on a Monday.

> An ideal solution would enable a preference (similar to the "Use US date input field order") that allows the user to choose between which day appears first in the date picker calendar view.

I agree that would be the best solution.

I can look into this but it will be low on my priority list. This also would be a great first PR for someone looking to contribute.

**Comment by mProjectsCode** [comment]
![image](https://user-images.githubusercontent.com/61602848/210656338-97884ea6-0316-4fc0-b24f-e0f9af2caedd.png)

I added a drow down to the settings to configure the first weekday.

**Comment by Chris-Andrews** [comment]
This is fantastic, thank you for adding this feature!
