### ISSUE TITLE
Issue with inlineListSuggestor and inlineList

### ISSUE THREAD

**Issue by floresben73** [mProjectsCode/obsidian-meta-bind-plugin#350]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.1

### Describe the Issue

When I click on the plus sign for inlineList or inlineListSuggestor it will add what I input into the metadata, but it wont display the entry next to the input field like it does for the other types of input fields. 

Evidence of Metadata Presence:
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/148321050/d66a6431-5385-4aec-a9b2-1e405e067325)

Evidence the inlineList and inlineListSuggestor aren't displaying their input selections:
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/148321050/53fc4f19-e2b7-4226-8bf1-2e07496efb18)

Expected Result should look like this with the entries next to the input field:
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/148321050/d49e4480-22db-4b0e-ab60-29ac71a429ab)

Notably this seems to happen regardless of whether or not the input field is in a codeblock or inline.

### Steps to Reproduce

Go to "exampleVault/Input Fields/List" and see that List and listSuggester inputs display the inputs, but inlineList and inlineListSuggestor are not. 

### Expected Behavior

It's my understanding that INPUT fields should display what was just entered, but with inlineList and inlineListSuggestor, it's not displaying what you just entered next to the plus sign.

**Comment by mProjectsCode** [comment]
I can not reproduce this. The input fields work fine for me. Can you check the console for any errors?

**Comment by floresben73** [comment]
How do I do that? The stuff that shows up with "Ctrl + Shift + I"? If so where would I see a potential error if there were one?

**Comment by floresben73** [comment]
This issue is persistent for me across multiple vaults, even one with nothing but the example vault, default theme, and only Meta Bind and Dataview plugins.

**Comment by floresben73** [comment]
I uninstalled Obsidian entirely from my computer and redownloaded. Issue resolved. Not sure what exactly went wrong tho.

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/148321050/3987f420-8894-40c5-8436-172f056c7347)

I think I've seen in other people's vaults the individual entries should have little Xs to remove them if desired, or am I incorrect?

**Comment by mProjectsCode** [comment]
> I uninstalled Obsidian entirely from my computer and redownloaded. Issue resolved. Not sure what exactly went wrong tho.

Maybe you had an old obsidian installer version. That can sometimes cause problems.
