### ISSUE TITLE
Meta-bind button builder paste code behaving oddly within Obsidian tables

### ISSUE THREAD

**Issue by tarathomasnow** [mProjectsCode/obsidian-meta-bind-plugin#351]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.1

### Describe the Issue

When using meta-bind button builder from the command palette then copying & pasting the code into a table in an obsidian note, the results include `<br>` line break signifiers and the button doesn't render.

Specifically, I was trying to add a command button.

This issue seems the same as issue #264 but the suggested solution didn't work for me (I have tried simply removing the line breaks from the pasted code but that still doesn't work.)

### Steps to Reproduce

1. Open command palette and select Meta Bind: Open Button Builder
2. Build a button, my example is trying to run a command to open date selector (see image)
3. Click "Copy to Clipboard" button
4. Paste the code into a table within an obsidian note.
5. The button DOES work when pasted directly into an Obsidian note.
6. When pasted into a table, it appears like this; 
`meta-bind-button<br>label: Select Date<br>icon: calendar<br>hidden: false<br>class: ""<br>tooltip: ""<br>id: ""<br>style: default<br>actions:<br>  - type: command<br>    command: date-inserter:open-calendar<br><br>`

7. Even if I manually remove the `<br>` in a text editor and paste again, the button doesn't appear or work.

![Button Builder](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/163699561/50efa04a-c38a-420a-953b-f126b6e2625d)

If I highlight the code, the code block displays correctly as per image

![Highlighted](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/163699561/06ebc957-3fc2-4418-b57e-a67129ffd2b0)

But as soon as I click out of the table, the code with line breaks `<br>` displays again.

I tested with all the other plugins disabled. ALL of them!

### Expected Behavior

Paste the code from the button builder into the table, allowing me to use the button from within a table.

**Comment by mProjectsCode** [comment]
This is somewhat expected as markdown tables don't support multi-line content and code blocks are multi-line by design.

There is nothing I can do about this.

**Comment by tarathomasnow** [comment]
Oh! 

That makes sense. I really appreciate you taking the time to explain that to me, I hadn't realised that I was trying to do something that fundamentally wouldn't work.

And thank you for such wonderful plugins!

**Comment by pping** [comment]
# buttons

```meta-bind-button
style: primary
label: Open Meta Bind Docs
action:
  type: open
  link: https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/
```
^docs-button

Obsidian table :![[filepath#^tag]]

example:
![[exampleVault/Examples#^docs-button]]
![[#buttons]]
