### ISSUE TITLE
Meta Bind Embeds are shown in outlines

### ISSUE THREAD

**Issue by lnmiltz** [mProjectsCode/obsidian-meta-bind-plugin#355]
### Is your Feature Request Related to a Problem?

No

### Describe the Feature you'd Like

A problem a lot of people have run into is that built-in outline plugin doesn't show headers from embedded files: https://forum.obsidian.md/t/outline-plugin-should-include-headers-from-embedded-markdown-files/21193

This is kind of a shot in the dark, but since Meta Bind's embeds seem to embed files in a different way that makes the embedded notes function like they're part of the parent note (https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/metabindembed/), it would be great if that could somehow be extended to outlines.

This seems like it'd normally be a huge pain, but I'm wondering if the way Meta Bind embeds work would make it more feasible to implement? I understand if this is out of scope though.

**Comment by mProjectsCode** [comment]
No, the way that meta bind embeds work is fundamentally the same. So it's the same amount of effort.

**Comment by lnmiltz** [comment]
> No, the way that meta bind embeds work is fundamentally the same as normal embeds. So it's the same amount of effort.

That makes sense. I might take a crack at this as a separate plugin then.
