### ISSUE TITLE
button temporarily breaks when title is changed. Shows [MB_UNLOADED] button. Gets fixed when refreshing the note

### ISSUE THREAD

**Issue by rotie-alt** [mProjectsCode/obsidian-meta-bind-plugin#356]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.2

### Describe the Issue

The button temporarily breaks when I change the title of the note. while this can easily be fixed by refreshing the note, this can be a bit annoying as I constantly deal with changing the name of notes. 

Shows [MB_UNLOADED] button.

Did I do anything wrong or is this an actual bug?

### Steps to Reproduce

An example of a note is this

Date: `May 28, 24 - 1꞉52 AM` · `BUTTON[another_fleeting_note]`

```meta-bind-button
label: Issue Yet Another Conflict?
icon: ""
hidden: true
class: ""
tooltip: Opens a fleeting note that can be processed later
id: another_fleeting_note
style: primary
actions:
  - type: command
    command: daily-notes

```

### Expected Behavior

I expected the button to just work normal, not refreshing the note everytime I change the name. Again, it can be easily resolved but would love to have it fixed (or probably find out if I'm doing something wrong here)

**Comment by mProjectsCode** [comment]
This is intended. The buttons need to be reloaded when the file name changes.
