### ISSUE TITLE
Image Meta Binding

### ISSUE THREAD

**Issue by conneroisu** [mProjectsCode/obsidian-meta-bind-plugin#36]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I want to embed an image into the metadata of a file so that it is viewable through data view and have to manually copy and paste an HTML <img> tag surrounding the image or download the image and use obsidian internal links with an exclamation mark preceding it.

**Describe the solution you'd like**
It would be cool to have an input field bring up images within the vault with a specified path(specified within the code block) to allow for the embedding of images into meta fields.
**Additional context**
Awesome plugin BTW!

**Comment by mProjectsCode** [comment]
Great idea, this is what i have so far
![image](https://user-images.githubusercontent.com/61602848/206802878-58364fc0-dc07-4f3b-9bab-b8ff94583789.png)
![image](https://user-images.githubusercontent.com/61602848/206802938-58b254d0-cbfc-4671-a004-d9208ccd9181.png)

Is there any specific way in which the image should be saved to the frontmatter? Currently it is as the local path to the image.

**Comment by conneroisu** [comment]
WOW! That looks great! I'm glad you like my idea. I like the image selector because sometimes the file name isn't all that descriptive unless you manually change each image name. Local paths to the image would probably be less used than web images from URLs, but this is awesome.

**Comment by mProjectsCode** [comment]
released as version `0.4.0`
