### ISSUE TITLE
META_BIND_ERROR : structuredClone is not defined

### ISSUE THREAD

**Issue by Shurikus-crypto** [mProjectsCode/obsidian-meta-bind-plugin#362]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Android
- [ ] iOS

### Plugin Version

1.1.2

### Describe the Issue

Hi! I am using Obsidian 1.6.3 for Android. This plugin version 1.1.2 is installed. But any code (for example from Meta Bind Playground) fails - structuredClone is not defined. As I understand it, this is due to the wrong version Node.js
Please advise me how to run this plugin!

### Steps to Reproduce

Any code does not work

### Expected Behavior

I want this plugin to work for me.

**Comment by mProjectsCode** [comment]
I can't reproduce this. It works perfectly fine for me on my android device. You can try reinstalling Obsidian.

**Comment by Shurikus-crypto** [comment]
No effect. I installed a completely "clean" Obsidian. No other plugins are installed. Here is the full description of the error:

ReferenceError: structuredClone is not defined
    at ph.partialToFullDeclaration (plugin:obsidian-meta-bind-plugin:109:168485)
    at ph.fromString (plugin:obsidian-meta-bind-plugin:109:167785)
    at Rg (plugin:obsidian-meta-bind-plugin:44:14429)
    at Die (plugin:obsidian-meta-bind-plugin:117:38714)
    at Be (plugin:obsidian-meta-bind-plugin:57:7991)
    at new IM (plugin:obsidian-meta-bind-plugin:132:2508)
    at og.onOpen (plugin:obsidian-meta-bind-plugin:132:2774)
    at og.<anonymous> (http://localhost/app.js:1:1442350)
    at http://localhost/app.js:1:237077
    at Object.next (http://localhost/app.js:1:237182)

**Comment by Shurikus-crypto** [comment]
Android 11 is installed on the tablet - the plugin does not work and terminates with this error. Android 13 is installed on the phone - the plugin works.

**Comment by mProjectsCode** [comment]
`structuredClone` has been supported in Android WebView since version 98 which was released 2022-02-02.

Try to update your Android and apps or if that is not possible, you are out of luck.

**Comment by Shurikus-crypto** [comment]
Hi! Thanks for the advice! Updated Android WebView to version 128 and now everything works as it should. Thanks for the cool plugin!
