### ISSUE TITLE
Add the Custom Color property for Buttons

### ISSUE THREAD

**Issue by Moyf** [mProjectsCode/obsidian-meta-bind-plugin#364]
### Describe the Feature you'd Like

Hi! I'm trying to move from the **Buttons** plugin into MetaBind.

Most function works great!
But I used to use the `cutomColor` and `customTextColor` properties in **Buttons** to modify the button's colors, however, MetaBind doesn't support it for now.

I know I can use the `class` to change it ,but in that way I have to create many css snippets - just to change the color. And this is not very convinient, especially when I just want to modify a single button.

So, could you please consider adding the `color-background` and `color-text` properties for MetaBind's Buttons?

### Additional Context

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/4013062/3fe77a61-23d3-420e-ae38-2988f5e772e6)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/4013062/7bc09070-c0e4-44e1-af63-afba4b39698c)

↑ what I can easily achive in Buttons Plugin

**Comment by mProjectsCode** [comment]
with the addition of inline CSS styles in `1.2.5-canary.20241127T230712` this FR seems somewhat fullfilled.
