### ISSUE TITLE
Question: What does addLabels property for sliders and progressBar do?

### ISSUE THREAD

**Issue by praveendhawan** [mProjectsCode/obsidian-meta-bind-plugin#366]
What does addLabels property for sliders and progressBar do?
I am unable to understand what this property do? Whats the use case? If I add this option or not add I dont see any difference? Can you please explain it here or in doc?

Thanks
and Sorry if its a noob question.

**Comment by mProjectsCode** [comment]
https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/reference/inputfieldarguments/addlabels/

**Comment by mProjectsCode** [comment]
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/61602848/f29c31a2-8732-4758-9d23-91993d019f31)
