### ISSUE TITLE
Validating Input Fields

### ISSUE THREAD

**Issue by svenschuldt** [mProjectsCode/obsidian-meta-bind-plugin#367]
### Is your Feature Request Related to a Problem?

Validating an input field based on pre-defined context or on comparison (dates).

### Describe the Feature you'd Like

How do I validate e.g. two input fields in comparison? Example:

Project Start Date: `INPUT[date:project-start]`
Project End Date: `INPUT[date:project-end]`

In 99.9% of the cases, the end-date has to be after the start-date - is there a function to validate input fields by comparison (or other elements such as min./max. value, etc.)?

### Additional Context

This can be used in many aspects, such as dates, values, etc.

**Comment by mProjectsCode** [comment]
No, there is not. I am not planning to add validation, as it can be quite complex. You could use a js-view-field to validate the two dates and display an error message when the dates are invalid. This gives you quite a lot of flexibility.
