### ISSUE TITLE
Why the default date is not hardcoded to the current date ?

### ISSUE THREAD

**Issue by olcariz** [mProjectsCode/obsidian-meta-bind-plugin#37]
When initializing a date_picker field, date output is `2022-02-01`. It affects plugin benefits for this one.

it should in my opinion be hardcoded to the date when the field is initialized.

**Comment by mProjectsCode** [comment]
> It affects plugin benefits for this one.

Idk what you mean with this sentence.

But yes I can change the default date for the date picker to the current date, if that is beneficial.

**Comment by oliviercarizzoni** [comment]
Hi, thanks for the quick answer, that means I am very less prone to use the plugin for picking date.

That said, the plugin is good, I appreciate your work !

**Comment by oliviercarizzoni** [comment]
Thank you for that !
