### ISSUE TITLE
Append Templater Note into an existing Note

### ISSUE THREAD

**Issue by rycue** [mProjectsCode/obsidian-meta-bind-plugin#370]
### Describe the Feature you'd Like

I wish there was a feature that allows me to append a **Templater note** to an existing note or to other existing notes using a button.

My request is similar to "templaterCreateNote" function, but it only creates a new note.

I hope this feature will be implemented as it would be a nice addition for easier automation to existing notes.

### Additional Context

Thank you so much for developing the best plugin.

**Comment by mProjectsCode** [comment]
duplicate of #296
