### ISSUE TITLE
Custom regexp flags for RegExp Replace In Note Button Action

### ISSUE THREAD

**Issue by IAmWhitBran** [mProjectsCode/obsidian-meta-bind-plugin#372]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.2

### Describe the Issue

The regexpreplaceinnote action does not seem to work as expected. When pressing the button to replace the regex in the file, the expression in the button recognises and replaces itself, often breaking the button syntax.
Even the example in the docs page doesn't function correctly.
https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/reference/buttonactions/regexpreplaceinnote/

### Steps to Reproduce

1. Open a new note
2. paste the following
````
```meta-bind-button
style: primary
label: RexExp Replace In Note
action:
  type: "regexpReplaceInNote"
  regexp: "(TODO: .*)\\n"
  replacement: "$1 - Done"
```

TODO: ...
TODO: something
TODO: something else
````
3. press the button

![MetabindExample](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/10598809/bcd10393-5ff1-455f-a357-cb278aac3839)

### Expected Behavior

I would expect the button to not replace the regex in itself.

As an aside, I have tried changing the expression to handle this scenario using the regex start and end of string tokens (^ and $) as well as trying to set the flags (g m i e s etc) but can't seem to work out if / how these would be applied. Could the docs be updated with more complex examples that cover setting expression flags?
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/10598809/fa1591b7-4970-4d14-bb49-66afc5d44eca)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/10598809/e6366113-f5c1-4820-a162-0bc134440b85)

**Comment by mProjectsCode** [comment]
A flags option sounds like a good idea, with the fallback being `g`.

> [...] it would be good if there was a way to avoid the button replacing regex within itself.

That does not sound feasible to me. The plugin would need to somehow modify the regexp to make it not match the button and I have no idea how I would do that.

**Comment by IAmWhitBran** [comment]
>That does not sound feasible to me. The plugin would need to somehow modify the regexp to make it not match the button  

I completely appreciate this and had the same thought myself.   

> I have no idea how I would do that

My hope was some wizardry could be done with something similar to the "replace self" functionality (since this is how I am handling it at the moment).

I'll admit I've not looked into how it works, but the replace self means the button has someway to identify itself as a button(?). My thinking is that a copy of the original button could be taken, regex replace run, then the original button inserted back over the resulting button...
Still, just a suggestion, less of an issue I think.

Flags would go a long way to helping with this.

**Comment by mProjectsCode** [comment]
> My thinking is that a copy of the original button could be taken, regex replace run, then the original button inserted back over the resulting button...

This does not work because we do not know how many lines above the button have been changed. E.g. the regex could insert 5 lines above the button position (which we can't know reliably) and if we try to re-insert the button we reinsert it at the wrong place.
