### ISSUE TITLE
Bug within keyword 'showcase' and imageSuggester?

### ISSUE THREAD

**Issue by conneroisu** [mProjectsCode/obsidian-meta-bind-plugin#38]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

Taken from the example vault
Any code block with a showcase in it results in:
-> ERROR: [MB_PARSING_ERROR] unknown argument 'showcase'
AND 
From image suggester
-> ERROR: [MB_PARSING_ERROR] argument 'suggestOptionQuery' is only applicable to suggester input fields
when you remove this, you receive the following
```
INPUT[ImageSuggester:image]
-> ERROR: [MB_PARSING_ERROR] unknown input field type
```

**Describe the bug**
Broken 
**To Reproduce**

1. Go to 'Example Vault'
2. Click on 'ImageSuggester'

**Screenshots**
![image](https://user-images.githubusercontent.com/88785126/207146206-84ff644f-1dce-47a7-b112-ef0ce6243d8f.png)
![image](https://user-images.githubusercontent.com/88785126/207146238-9b961610-eafc-4ada-b9ee-7d1f3c2047b7.png)

**Occurs on**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.3.3
**Additional context**

**Comment by mProjectsCode** [comment]
Yeah, that is expected. Those things were added to the plugin, but not yet released. You can ignore them for now, or use the example vault from the release branch.

**Comment by conneroisu** [comment]
Sorry guess I just got excited!
