### ISSUE TITLE
Add a "null value" option

### ISSUE THREAD

**Issue by sweetcornwhiskey** [mProjectsCode/obsidian-meta-bind-plugin#381]
### Describe the Feature you'd Like

I would like to have the ability to add options to suggesters/selects/etc. that return a null value / empty string, resetting it to its default state (with no default value provided). It would be helpful to be able to clear the selection without having to go into the frontmatter for bound items or without having to reload the element for unbound items.

**Comment by mProjectsCode** [comment]
You should be able to add an empty option `option()`, or one with the value `null` `option(null)`.

**Comment by sweetcornwhiskey** [comment]
Neither of these options work. Providing the empty option ```option()``` gives a parsing error, and ```option(null)``` returns the string "null".

**Comment by sweetcornwhiskey** [comment]
Here's what it shows on my screen:
![image](https://github.com/user-attachments/assets/037ecc36-1274-418b-9e5b-81fd53a764f7)

When I click on the warning sign, it gives this popup:
![image](https://github.com/user-attachments/assets/16fe9958-7909-40c0-972f-d8dc4f407b66)

**Comment by mProjectsCode** [comment]
Ah, then my suspicion about `option()` is correct. But `option(null)` works as an empty value in my testing. You can even give it another label in the select itself e.g. `option(null, Empty)`
