### ISSUE TITLE
Access `memory` and `globalMemory` bind targets from javascript

### ISSUE THREAD

**Issue by GRA0007** [mProjectsCode/obsidian-meta-bind-plugin#382]
### Describe the Feature you'd Like

I'm not sure if there's already a way to do this, but I've trawled through the discussions and forums and even the source code and I can't seem to find anything.

Essentially, I'd like a way to access values I bind to `memory` or `globalMemory` to be accessible via javascript, more specifically, in a `dataviewjs` block.

My use-case is using an `inlineSelect` control to filter a `dataviewjs` query. If there's another way to achieve this please let me know.

### Additional Context

Note that I'm current achieving this by binding to a frontmatter property and reading that via `dv.current()`, but I'd prefer if this value wasn't stored in the frontmatter since I don't mind if the value is lost on restart.

**Comment by mProjectsCode** [comment]
This should work
`<mb api reference>.getMetadata('globalMemory^property')` 

https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/api/classes/obsidianapi/#getmetadata

**Comment by GRA0007** [comment]
Thanks for the pointer, through some more research I was able to put together this which works in a `dataviewjs` block:

```js
const currentPage = dv.current()
const mb = app.plugins.plugins["obsidian-meta-bind-plugin"].api
const filter = mb.getMetadata(mb.parseBindTarget('memory^filter', currentPage.file.path))
const sort = mb.getMetadata(mb.parseBindTarget('memory^sort', currentPage.file.path))

// do something with filter and sort
```

However, I can't trigger the meta bind select inputs to refresh the dataview when updated, so I have to manually call the `Dataview: Rebuild current view` command after changing them. I've decided to keep using frontmatter instead as with the `Automatic view refreshing` option enabled in dataview, this will cause it to refresh when the frontmatter changes.

**Comment by ValryonOmega** [comment]
> This should work `<mb api reference>.getMetadata('globalMemory^property')`
> 
> https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/api/classes/obsidianapi/#getmetadata

I'm trying to use this for another use case but I am not actually getting this to work as intended. I just get an error that it is expecting an object, not a string, when I remove the quotes, it says memory is not defined.

**Comment by mProjectsCode** [comment]
Ah yeah, you do need that `parseBindTarget` like in GRA0007s example
