### ISSUE TITLE
Remove unnecessary logging (follow Obsidian plugin guidelines)

### ISSUE THREAD

**Issue by Mara-Li** [mProjectsCode/obsidian-meta-bind-plugin#384]
### Is your Feature Request Related to a Problem?

The plugin print a **enormous** amount of text in the console. All content of each view is printed. On big project, it can lead to more than 1000 console.log statement per page.

The plugin policies state that you must avoid unncessary logging (see [here](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+unnecessary+logging+to+console)). I created my own fork just to comment the log, because it is really complated with it, but I'm afraid I broken some things as I'm not really confiant with my work.

### Describe the Feature you'd Like

Remove the unncessary logging info statement of the plugin.

### Additional Context

https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+unnecessary+logging+to+console

**Comment by mProjectsCode** [comment]
I am not quite sure what you are referring to. Could you clarify with maybe a screenshot?
The plugin uses quite a bit of `console.debug` statements, but that does not violate the guidelines.

**Comment by Mara-Li** [comment]
![image](https://github.com/user-attachments/assets/dcc03127-4cb5-43bc-b35b-4b4dca281c94)

**Comment by Mara-Li** [comment]
![image](https://github.com/user-attachments/assets/60b55d65-8914-4aa5-9e2f-b8873dd75f90)
Have to censure because of sensitive information, but here an example.

Each time I open any file with meta-bind-js-view, this pop. As all my file in this vault use a lot of this… Well, the logs are flooded.

**Comment by mProjectsCode** [comment]
ah, yeah. I definitely overlooked some. I could probably do some build time stuff to exclude logs in prod builds 
https://github.com/evanw/esbuild/issues/28

**Comment by mProjectsCode** [comment]
I made it so that the logs are stripped in release builds. That should solve this problem.
