### ISSUE TITLE
Auto trigger button on input change

### ISSUE THREAD

**Issue by ishanarora** [mProjectsCode/obsidian-meta-bind-plugin#386]
### Is your Feature Request Related to a Problem?

I'd like to run some button actions every-time I change an input. Right now I have a button next to the input field that I must click manually to trigger the actions.

### Describe the Feature you'd Like

INPUT could be extended to accept an optional button id which would get triggered every time a bind target is updated.

**Comment by mProjectsCode** [comment]
I don't think this is a good idea. Buttons should be triggered manually.

You can achieve something similar by using a js view field with the bind target of the input field as a dependency. Though you would have to write your logic via JS and not button actions, but button actions can be called from the meta bind api.
