### ISSUE TITLE
Allow list-based operations (map, filter, sort, etc) in view fields

### ISSUE THREAD

**Issue by miscoined** [mProjectsCode/obsidian-meta-bind-plugin#388]
### Is your Feature Request Related to a Problem?

I'd like to be able to do list transformation in view fields. I can think of many places this would be useful, but in particular my use case is that I have a list of things that contribute to an attribute for my character:
```yaml
attrBuild:
  str:
    - 11 base
    - 2 Ysoki racial penalty
    - 2 LV5 ability increase
    - 2 LV10 ability increase
```
This list is populated via a MetaBind input field. I'd then like to calculate the result of splitting these values and then summing the first entry in each split. I know that if I didn't have the labels attached I could do `VIEW[sum({attrBuild.str})]` and that would work, but I want the labels there so that I have context on what caused the attribute boost.

After a bit of tinkering I realized that while there is a [map](https://mathjs.org/docs/reference/functions/map.html) function in mathjs, it doesn't appear to be usable within the expression context because the parser doesn't recognize lambda functions. So even this simpler example fails with a SyntaxError (tested using the [MathJS demo](https://mathjs.org/index.html)): `map(["1", "2"], x => numeric(x))`

`map(["1", "2"], numeric)` doesn't cause a SyntaxError, but still fails because `numeric` only accepts a single argument and `map` by default passes multiple in.

I know that I can probably achieve this with JS Engine, but that feels quite heavyweight for what feels like a simple transformation.

### Describe the Feature you'd Like

It'd be great if MetaBind could implement another view field type for lists only which accepts a MathJS expression and applies it to every element of the list.

### Additional Context

I'm quite new to MathJS so there's some syntax for this that I might have missed. The documentation is pretty sparse.

Thank you!

**Comment by mProjectsCode** [comment]
> It'd be great if MetaBind could implement another view field type for lists only which accepts a MathJS expression and applies it to every element of the list.

This will most likely not happen. The math js view fields are intended for simple calculations. If the math js expression language can't express what you are trying to compute, you are probably better off with JS instead of trying to hack what you want into the math js expression language.

I am thinking about an inline version of the js view field, but there are some conflicts around the characters `{`, `}`, `[`, and `]` there.

**Comment by miscoined** [comment]
Thank you for the quick response and providing your reasoning :) Feel free to close this one.

An inline JS view field would be fantastic. Could you use normal escaping for the conflicting characters? Or, personally I'd prefer something like a plain JS expression which gets given a named parameter for the frontmatter (like `params` or `frontmatter` or something). Then you don't have to worry about escaping or weird regexes at all. Just a suggestion :)
