### ISSUE TITLE
Possible Typo In Official Document?

### ISSUE THREAD

**Issue by WhoAmI-WhereAmI** [mProjectsCode/obsidian-meta-bind-plugin#394]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

doesn't matter

### Describe the Issue

I was reading through the (very well written) meta bind document and encountered this.
I couldn't get what the phrase 'The storage path points to a file and the property to an in memory field' means.

![image](https://github.com/user-attachments/assets/5a27ccb3-f330-4296-9240-afdaadb1e9cc)

### Steps to Reproduce

visit https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/bindtargets/#2-the-storage-path
and scroll to section `1. The Storage Type`

### Expected Behavior

No idea what the original intention is...

**Comment by WhoAmI-WhereAmI** [comment]
oh an in-memory... never mind

**Comment by WhoAmI-WhereAmI** [comment]
maybe an hyphen would help

**Comment by mProjectsCode** [comment]
> maybe an hyphen would help

Good idea, I will add one.
