### ISSUE TITLE
Buttons unloaded when renaming note

### ISSUE THREAD

**Issue by Simon40000** [mProjectsCode/obsidian-meta-bind-plugin#396]
### Please fill out these Check-boxes

- [X] I checked for existing similar issues
- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### Plugin Version

1.1.3

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Debug Info

```text
It might be this is not considered a bug but it creates problems in my workflow. No output in console when this happens.
```

### Describe the Issue

I have multiple buttons in my templates. When creating a new note the first action at hand is to rename the note. After renaming the note all buttons are unloaded. Perhaps I can prevent this behaviour somehow? The work around is to edit every button but it is to tedious to to.

### Steps to Reproduce

1. Create a new note
2. Add a button
3. Rename note
4.All buttons are unloaded. Instead of the button I see "[MB_UNLOADED] button".

or to demonstrate in my use case
1. Create a template with muliple buttons.
2. Create a new note based on the template
3. Set a name of the new note
5. All buttons are unloaded. Instead of the button I see "[MB_UNLOADED] button".

### Expected Behavior

The button remains loaded.

**Comment by mProjectsCode** [comment]
As stated in similar issues, this is intended. The plugin currently can not handle file renaming, and to protect your notes from unintended behavior, it unloads all active fields and buttons in the renamed note.

**Comment by Andrew-Eathan** [comment]
for anyone else who's also often slowed down by this issue: you can quickly restore your buttons by selecting all the text in the note with ctrl+a and then pressing somewhere to quickly deselect it :)
