### ISSUE TITLE
How to set conditional css classes for changing number values ?

### ISSUE THREAD

**Issue by AnasImr** [mProjectsCode/obsidian-meta-bind-plugin#397]
how do I change this metabind query so if the propery's value is above 0 it has the class:"mod-success" and if it's at 0 then it has the class:"mod-warning": `VIEW[{BlackTshirtSizeS}>0?:][math]`

**Comment by mProjectsCode** [comment]
This is not possible with view fields, but it can be done with JS view fields.
Issues are not the right place for questions. Please use the discussions or the thread in the official Obsidian discord server.
