### ISSUE TITLE
How to bind target to nested properties

### ISSUE THREAD

**Issue by lotusccong** [mProjectsCode/obsidian-meta-bind-plugin#401]
### Page

N/A

### Issue or Enhancement

I have the following nested  frontmatter properties  -
readdates:
- started: 2023-08-10
  finished: 2023-08-15
- started: 2023-09-05
  finished: 2023-09-12

It seems that I can't find a to use the input fields to bind target to started and finished nested properties.

**Comment by mProjectsCode** [comment]
See [Properties with Spaces and Nested Properties](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/bindtargets/#3-the-property). In your case you would want `readdates[0].started`, or `readdates[1].finished`, ...
