### ISSUE TITLE
Date picker adds time to frontmatter property

### ISSUE THREAD

**Issue by Smitty010** [mProjectsCode/obsidian-meta-bind-plugin#402]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

I'm using the datePicker to modify a frontmatter field that has a date in it.  However, when I modify the date, I also get a time.  I can't find anything to avoid having the time added

### Describe the Feature you'd like

I would like to have a way to tell datePicker that I don't want the time included.  Currently, if I use datePicker on a field that is "YYYY-MM-DD", it will change it to "YYYY-MM-DDTHH:mm:SS-'timezone offset'".  I just want the date, i.e., I want the output to be "YYYY-MM-DD"

**Comment by mProjectsCode** [comment]
Oh, that should not happen.

**Comment by Smitty010** [comment]
I don't need the time, so if it just went away.... :)
