### ISSUE TITLE
Add option to open existing note instead of creating duplicate for createNote action

### ISSUE THREAD

**Issue by root-T2** [mProjectsCode/obsidian-meta-bind-plugin#405]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Describe the Feature you'd like

Currently, when using the createNote action, if a note with the same title already exists, the plugin creates a new note with a numbered suffix (e.g., 'Note 1', 'Note 2'). This can lead to unintended duplicate notes.

Feature request:
Add a new option to the createNote action that, when enabled, will open the existing note instead of creating a duplicate if a note with the same title already exists.

This feature would:

1. Check if a note with the given title already exists
2. If it exists, open that note instead of creating a new one
3. If it doesn't exist, create a new note as usual

This option would help prevent the creation of unnecessary duplicate notes and improve workflow efficiency for users who prefer to update existing notes rather than create new ones with similar titles.

**Comment by mProjectsCode** [comment]
The next release will include a new property `openIfAlreadyExists` for the Create Note and Templater Create Note button actions.
