### ISSUE TITLE
How to insert Defaultvalue in inlineSelect

### ISSUE THREAD

**Issue by lotusccong** [mProjectsCode/obsidian-meta-bind-plugin#407]
How to insert the DefaultValue in inlineSelect .
For example the default Value is ok. 

INPUT[inlineSelect(
    option(trash),
    option(bad),
    option(ok),
    option(good),
    option(great)
):rating]

**Comment by mProjectsCode** [comment]
https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/reference/inputfieldarguments/defaultvalue/

**Comment by yinlokc** [comment]
I found the following cannot set the default value, is the syntax correct? Thanks. 

`INPUT[inlineSelect(option(1), option(2), option(3), defaultValue(3)):selected]`
