### ISSUE TITLE
Impossible to display the toggle input as a checkbox.

### ISSUE THREAD

**Issue by irodionzaytsev** [mProjectsCode/obsidian-meta-bind-plugin#409]
### Please fill out these Check-boxes

- [X] I checked for existing similar issues
- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### Plugin Version

Latest

### This Issue Occurs on

- [X] Windows
- [X] Linux
- [X] macOS
- [X] Android
- [X] iOS

### Debug Info

```text
output
```

### Describe the Issue

So I want to apply some styling to the toggle input, so that it looks like a checkbox. 
As I understand, I have to apply it to a class something like this:
`.mb-input-type-toggle.toggle-as-checkbox .checkbox-container`
and then inside obsidian
`INPUT[toggle(class(toggle-as-checkbox))]`
The problem is, no matter what I put inside my css snippet, I don't think it's possible to make the toggle switch disappear and make it look like a checkbox. I try to take code from [here](https://www.w3schools.com/howto/howto_css_custom_checkbox.asp), and change accordingly, but I get rubbish. The problem is, I can't make the toggle sit inside the span of my own class. 
Could you either add a separate checkbox input that can be used inline, or make the styling more accessible (like maybe add this usecase into documentation)?
I try to achieve this with chatGPT, but it doesn't work.

### Steps to Reproduce

Described above

### Expected Behavior

i expect to be able to have a checkbox input instead of a toggle. Right now the only way is to install the ITS theme where all toggles are replaced by checkboxes.

**Comment by irodionzaytsev** [comment]
Actually someone already ask this as feature request [here](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues/316), but I don't think this is a feature request, because technically it should be possible to achieve this by CSS styling. If you prefer to add another field, namely checkbox, that of course solves this styling bug because then toggle is just a toggle.

**Comment by mProjectsCode** [comment]
The toggle styling comes from Obsidian and not this plugin. I do want to implement separate checkboxes at some point when I find the time and motivation.
