### ISSUE TITLE
Remove input field after edit

### ISSUE THREAD

**Issue by conneroisu** [mProjectsCode/obsidian-meta-bind-plugin#41]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I only use a meta-bind code block once inside of a note to set the designation or status, for instance and have to manually delete the field myself to make space for my note.

**Describe the solution you'd like**
I saw something in the recent commits about the destroy method, but I am not certain this is the same feature. I think it would be very nice to argue inside of a code block to remove the code block after it is changed.

**Comment by mProjectsCode** [comment]
No, the `destroy` method is just to ensure, that svelte components, which are part of the input field, are unloaded correctly when the input field is unloaded.

> I think it would be very nice to argue inside of a code block to remove the code block after it is changed

This is not a feature that i am planning to implement, as it is not really the intended use case of the plugin. But i would merge a well-structured PR that implements this logic.
