### ISSUE TITLE
Input fields not rendering in reading mode.

### ISSUE THREAD

**Issue by Akunus** [mProjectsCode/obsidian-meta-bind-plugin#411]
### Please fill out these Check-boxes

- [X] I checked for existing similar issues
- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### Plugin Version

1.1.3

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Debug Info

```text
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.5.12
	Operating system: Windows 10 Pro 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Meta Bind v1.1.3

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Describe the Issue

This issue only happens in reading view. When a < h > element is before an input field, it fails to render. Can be fixed, by inserting an empty line beteween the < h > element and the input field.

### Steps to Reproduce

1. Write ```<h2>something</h2>``` 2. Go to next line. 3. Write Food `INPUT[number:food]` 4. Go to reading view. 5. See error.

### Expected Behavior

I expected the plugin to not care about where its code is relative to other things in the document.

**Comment by mProjectsCode** [comment]
Can you attach a note where this issue occurs to this issue as a code block?

**Comment by Akunus** [comment]
```
<h2>Bug</h2>
Question `INPUT[number:anwser]`

<h2>Works correctly</h2>

Question `INPUT[number:anwser]`
```

**Comment by mProjectsCode** [comment]
![image](https://github.com/user-attachments/assets/e0959a72-79ec-4a8e-8ee1-f179a4492331)
This seems to be an Obsidian limitation, note that other markdown features such as bold also don't render.
