### ISSUE TITLE
Render for the 2nd input fail when there are two INPUT in the string 

### ISSUE THREAD

**Issue by yinlokc** [mProjectsCode/obsidian-meta-bind-plugin#412]
### Please fill out these Check-boxes

- [X] I checked for existing similar issues
- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### Plugin Version

1.13

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Debug Info

```text
SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.5.12
	Operating system: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64 23.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.5.4
	Snippets enabled: 36
	Restricted mode: off
	Plugins installed: 130
	Plugins enabled: 89
		1: Quick Plugin Switcher v7.10.1
		2: Advanced URI v1.44.1
		3: Actions URI v1.6.3
		4: Apple Books Highlights v1.0.1
		5: Better footnote v1.0.1
		6: Better PDF 2 v2.0.3
		7: Commander v0.5.1
		8: cMenu v1.1.2
		9: CSS Editor v1.2.1
		10: Dataview v0.5.67
		11: Find and replace in selection v1.0.1
		12: Habit Tracker 21 v1.4.5
		13: Hotkeys++ v0.2.7
		14: ibook v2.0.12
		15: JS Engine v0.1.12
		16: Local Quotes v1.9.0
		17: Mermaid Tools v1.1.3
		18: MetaEdit v1.8.2
		19: Admonition v10.3.2
		20: Better Command Palette v0.17.1
		21: Excalidraw v2.4.2
		22: Local REST API v2.5.4
		23: Markmind v3.0.2
		24: Meta Bind v1.1.3
		25: Minimal Theme Settings v8.1.1
		26: Regex Find/Replace v1.2.0
		27: Style Settings v1.0.9
		28: Tracker v1.14.0
		29: Force note view mode v1.2.2
		30: BRAT v1.0.2
		31: ProgressBar v0.6.0
		32: QuickAdd v1.11.1
		33: Readwise Official v2.1.1
		34: Recent Files v1.4.2
		35: Repeat v1.8.0
		36: Slash Commander v0.2.16
		37: Templater v2.7.1
		38: URI Commands v1.0.0
		39: Custom File Explorer sorting v2.1.13
		40: File Hider v1.1.1
		41: Obsidian Columns v1.5.2
		42: Text Generator v0.7.37
		43: Execute Code v1.12.0
		44: Text to Speech v0.5.4
		45: Iconize v2.14.3
		46: Image Toolkit v1.4.1
		47: Modal forms v1.50.0
		48: Fleeting Notes Sync v0.6.3
		49: Jump to link v0.5.9
		50: Hotkeys for Bookmarks v1.1.1
		51: Thumbnails v1.3.0
		52: Image Gallery v1.1.1
		53: Folder notes v1.7.26
		54: Daily Prompt v1.0.0
		55: Remember cursor position v1.0.9
		56: Natural Language Syntax Highlighting v0.3.0
		57: Collapse All v2.1.0
		58: Advanced Slides v1.20.0
		59: Copilot v2.5.3
		60: Painter v1.1.0
		61: Multi Properties v1.1.1
		62: MathLive v1.3.1
		63: Color Palette v2.14.0
		64: YTranscript v0.9.2
		65: Perilous Writing v1.2.1
		66: Writing Goals v0.9.5
		67: Calendar v1.5.10
		68: Periodic Notes v0.0.17
		69: Chronology v1.1.11
		70: Widgets v0.0.9
		71: Note Toolbar v1.9.12
		72: CustomJS v1.0.21
		73: Code Styler v1.1.7
		74: Hotkeys for templates v1.4.3
		75: Terminal v3.15.1
		76: Daily Note Outline v1.5.0
		77: Simple Embeds v1.15.0
		78: Find orphaned files and broken links v1.10.1
		79: Aloud v0.4.1
		80: Audio Notes v0.7.2
		81: Audio Player v0.1.1
		82: Media Extended v3.2.6
		83: Plugins Annotations v1.7.2
		84: MySnippets v1.2.3
		85: Style Importer v1.0.4
		86: Creases v0.7.0
		87: Focus and Highlight v1.3.2
		88: Zen v0.6.5
		89: Smart Connections v2.1.101

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Describe the Issue

Render for the 2nd input fail when there are two INPUT in the string 

<img width="488" alt="image" src="https://github.com/user-attachments/assets/777a1ab1-b1d9-4054-9a98-c296f3b64b9c">

### Steps to Reproduce

run the following code

---
options:
  - "1"
  - "2"
  - "3"
options1:
  - "a"
  - "b"
  - "c"
selected: 1
---

Options: `INPUT[inlineList:options]`

```meta-bind-js-view
{options} as options
{options1} as options1
---
const options = context.bound.options.map(x => `option(${x})`).join(", ");
const options1 = context.bound.options1.map(x => `option(${x})`).join(", ");
let str = `\`INPUT[inlineSelect(${options}):selected]\``;
const str1 = `\`INPUT[inlineSelect(${options1}):selected]\``;
str+="abc"+str1
return engine.markdown.create(str);
```

### Expected Behavior

2 dropdown box show properly

<img width="163" alt="image" src="https://github.com/user-attachments/assets/034b3aaf-6685-4d5c-924f-720da7bcf1c5">

**Comment by SumyGanas** [comment]
I'm using 1 .13 and am on MacOS but I'm not able to reproduce the issue. The render looks like the expected behaviour. 

**Code:**
<img width="668" alt="Screenshot 2024-09-13 at 3 58 50 PM" src="https://github.com/user-attachments/assets/2f28a088-72cd-4f4c-aeac-a687ce12c2d7">

**Result:**
<img width="295" alt="Screenshot 2024-09-13 at 3 59 06 PM" src="https://github.com/user-attachments/assets/d0bc6611-c711-413f-9089-5c4a1739436f">

**Comment by yinlokc** [comment]
Thanks for validating! 

The reason is because I turned on the setting "Disable Code Block Restriction" setting.

**Comment by mProjectsCode** [comment]
> The reason is because I turned on the setting "Disable Code Block Restriction" setting.

That should not influence this.

**Comment by yinlokc** [comment]
ok may be I overlooked, I try to put the html code as below if it may help

**Abnormal result**
<div class="block-language-meta-bind-js-view mb-view">
<div class="mb-view-wrapper">
<p dir="auto">
<code class="code-styler-inline mb-input mb-input-inline">
<div class="mb-input-wrapper mb-input-type-inlineSelect">
<select class="dropdown"><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></div></code>abc

<code class="mb-input mb-input-inline code-styler-inline">aa<br>bbb<br>ccc</code></p></div></div>

**Expected result**
<div class="mb-view-wrapper">
<p dir="auto">
<code class="mb-input mb-input-inline">
<div class="mb-input-wrapper mb-input-type-inlineSelect">
<select class="dropdown"><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></div></code>abc

<code class="mb-input mb-input-inline"><div class="mb-input-wrapper mb-input-type-inlineSelect">
<select class="dropdown"><option value="a">a</option><option value="b">b</option><option value="c">c</option></select></div></code></p></div>

**Comment by mProjectsCode** [comment]
I can't reproduce the behavior with your example regardless of the `Disable Code Block Restrictions` setting. 
I would guess it has to do with one of the other 88 plugins that you have enabled, even though you checked this box `The issue persist with all other plugins and themes disabled`.

**Comment by yinlokc** [comment]
I finally figure out that this is due to another plugin called "Code Styler" and is now fixed. Thanks all for the help.
