### ISSUE TITLE
Get position of the pressed button in the inline JS

### ISSUE THREAD

**Issue by ujikol** [mProjectsCode/obsidian-meta-bind-plugin#414]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Describe the Feature you'd like

I need to process the text in the context of the button, e.g. the markdown section below the button.
For that I need to know the buttons line or offset.
The editors cursor might be somewhere else.

### Alternatives

At least get the ID of the button. But would be off much less help because duplicating section with related buttons would lead to non-distinguishable IDs.

**Comment by mProjectsCode** [comment]
This is not possible in reading mode, which is a limitation of the Obsidian API.

**Comment by ujikol** [comment]
Is it possible to get the rendered output, i.e. the contents of
preview/reading mode? This would help with another issue.

Moritz Jung ***@***.***> schrieb am Mo., 16. Sep. 2024, 20:59:

**Comment by mProjectsCode** [comment]
what exactly do you mean by output? The HTML element of the button? You should never modify that.

**Comment by ujikol** [comment]
I did not want to modify the rendered html. I want to parse it, actually
not the button but the context (section below it).

Moritz Jung ***@***.***> schrieb am Mo., 16. Sep. 2024, 21:43:

**Comment by ujikol** [comment]
Maybe my question was misleading. With inline I ment inline of the button
definition, not in markdown inline code.

The issue is that your plugin provides notePosition to
e.g. runReplaceSelfAction but not to runInlineJsAction. In that inline Js
code I would need to position.

Am Mo., 16. Sept. 2024 um 20:59 Uhr schrieb Moritz Jung <
***@***.***>:

**Comment by mProjectsCode** [comment]
In the next version of the plugin you can access some extra information about the button including its location (if known) via `context.buttonContext`

**Comment by ujikol** [comment]
Great, thanks.
Any planned release date?

Am Sa., 21. Sept. 2024 um 14:02 Uhr schrieb Moritz Jung <
***@***.***>:

**Comment by mProjectsCode** [comment]
No. When it's ready. A canary release will come tomorrow, if you can't wait.
