### ISSUE TITLE
Tooltips for Inputs and Views

### ISSUE THREAD

**Issue by akashchopra** [mProjectsCode/obsidian-meta-bind-plugin#418]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Describe the Feature you'd like

When viewing a note containing an input and/or view, it would be nice to know which metadata property the control is bound to. I think a simple tooltip showing the name of the property would be sufficient.

**Comment by mProjectsCode** [comment]
I don't think this is something the plugin needs. You can already make the reader of the note aware of what a specific input does by the surrounding text. E.g.
```md
Completion date: `INPUT[datePicker:completion_date]`
```
