### ISSUE TITLE
Loss of metadata from other input fields when typing in text fields.

### ISSUE THREAD

**Issue by sky297823** [mProjectsCode/obsidian-meta-bind-plugin#42]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
Similar to issue #23, when typing text into meta-bind text fields, metadata already added in any other type of field within the same document sometimes disappears completely. All added metadata in that note disappears. Happens with sync on and off. Happens in reading mode.

**To Reproduce**

1. Add different input fields to a note, among them text fields.
2. Enter different types of data.
3. Go to a text field and keep on typing, sometimes for a prolonged amount of time, sometimes not.
4. At some point, all the previously added information disappears.

**Expected behavior**
I expect previously added metadata in other fields to stay.

**Occurs on**

-   [ ] Windows
-   [ ] macOS
-   [x] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.3.3

**Comment by mProjectsCode** [comment]
I already have a fix for this issue, but i need to test it a bit more before i release it.

**Comment by Teighe** [comment]
> Now that OBS 1.1 has been released publicly, I can release the update, but it seems like the new OBS API method has a bug outlined [here](https://discord.com/channels/686053708261228577/840286264964022302/1054786358775906344), so I am unsure, if I want to release it now or wait until that is fixed.

Was this ever addressed? I am having this issue.

**Comment by mProjectsCode** [comment]
The newest version of the plugin is using Obsidians metadata API. Rollback should not be an issue anymore in the latest version of the plugin.
