### ISSUE TITLE
Inline Button Name change

### ISSUE THREAD

**Issue by KimoSabeCode** [mProjectsCode/obsidian-meta-bind-plugin#420]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

i can in cases forget the id of my buttons and therefore i name them the same as the id (camelcase). But when im done creating my note i would like to make it pretty but i cant change the buttons names incase i will use them elsewhere in the future.

### Describe the Feature you'd like

I ask but a simple feature of the mighty Lemons.
Can thou spare thine time to make `BUTTON[id-example]` into `BUTTON[ button( "id", "name") ]`
I thank thou for thine time

### Alternatives

i know not of a simplar solution but the one I have presented thee

### Additional Context

thou = you
thine = your/yours
thee = to you
From Shakespeare pronouns

idk why im like this

**Comment by mProjectsCode** [comment]
This would fall under #317
