### ISSUE TITLE
Boolean Control Flow in MetaBind Objects

### ISSUE THREAD

**Issue by jackhagley** [mProjectsCode/obsidian-meta-bind-plugin#421]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Describe the Feature you'd like

A simple way to display one of two things based on a boolean function
for example `IF(prop1+prop2) > 5 THEN "foo" ELSE "bar"`

### Additional Context

I feel that this could open up some other ideas from others regarding uses of MetaBind

**Comment by mProjectsCode** [comment]
You can already use ternary expressions in math view fields.
