### ISSUE TITLE
Custom icons in buttons

### ISSUE THREAD

**Issue by PippoGot** [mProjectsCode/obsidian-meta-bind-plugin#425]
### Page

https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues

### Issue or Enhancement

I noticed that when adding an icon to a button, you can't use custom ones.  I tried adding custom icons with Iconize plugin but despite working in the normal notes the icon won't appear in the buttons. Then I inspected the editor, and the source of the icon seems to be a link and not some internal resource file. 

I was wondering if I'm doing something wrong or it's actually like this.

**Comment by PippoGot** [comment]
I apologize for any wrongdoing, but Im kinda new to using GitHub for issues and stuff other than saving repos.

**Comment by mProjectsCode** [comment]
You can't use custom icons. Only the ones that are included with Obsidian.

**Comment by PippoGot** [comment]
So is it possible to make it a feature request then ? Or would it be out of the scope of the plugin ?

**Comment by mProjectsCode** [comment]
not is scope, see #329
