### ISSUE TITLE
`MarkdownRenderer.render` cause render fail

### ISSUE THREAD

**Issue by LincZero** [mProjectsCode/obsidian-meta-bind-plugin#428]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

## The effect I want

(Used with other plugins (anyblock plugin, I am the author of this plugin))

![image](https://github.com/user-attachments/assets/94294a10-c54e-4e4e-b626-e79a86eda308)

## Actual result

The collaboration with `buttons plugin` was successful (See picture above),
but there were some problems with `metabind` (see image below)：

- Some btn live/read modes failed to render
- Some btn failed in real time while reading mode succeeded

## Analysis of causes

![image](https://github.com/user-attachments/assets/4e43d9ad-31a8-4390-a78c-54232ded2ccb)

`Anyblock Plugin` use the `MarkdownRenderer.render`, it can renders a piece of markdown text and return element.
(Note: The result of re-rendering is the result of reading mode. so in reading mode, it might be better to work with plugins)

But there may be some differences between the ctx of 'MarkdownRenderer.render' and the ctx in reading mode, which may be the reason why it doesn't work:  (See the bottom of the picture)

- plugins may decide that something is not working in live mode (despite rendering something in read mode in live mode)
- ctx differences, such as `containerEl` is no longer `div.cm-scroller`, but the parent element that triggers `MardownRenderer.render`

**Comment by LincZero** [comment]
## Repeat tips

when use

````md
```anyblock
```
````

And the first line in the code block is not `[...]`

All he does is call the contents of the code block through 'MarkdownRenderer.render', and little else is done.

So you can use this feature to facilitate debugging

## test demo

`````md
````anyblock
test1
```meta-bind-button
style: primary
label: Meta Bind Help
action:
  type: command
  command: obsidian-meta-bind-plugin:open-faq
```
test2
```meta-bind
INPUT[inputType]
```
test3
`INPUT[toggle]`

test4
`INPUT[inputType]`

test5
```button
name Toggle spellcheck
type comand
action Toggle spellcheck
color blue
```
^button-spellcheck
````
`````

**Comment by mProjectsCode** [comment]
Are you passing a loaded component to the render function?

**Comment by mProjectsCode** [comment]
Can you send me the errors that should appear in the console? What does it say when you click on the error message I  the rendered content?

**Comment by LincZero** [comment]
## console message

The console did not report an error or print any other information

## It simplifies what I do

```ts
this.registerMarkdownCodeBlockProcessor("anyblock", ABReplacer_CodeBlock.processor);
...
export class ABReplacer_CodeBlock{
  static processor(
    src: string,
    blockEl: HTMLElement,
    ctx: MarkdownPostProcessorContext,
  ) {
    let dom_replaceEl = blockEl.createDiv({
      cls: ["ab-replaceEl"]
    })
    MarkdownRenderer.render(app, src, dom_replaceEl, app.workspace.activeLeaf?.view?.file.path, new MarkdownRenderChild(dom_replaceEl));
  }
}
```

## This way it can be matched with the plugin

https://github.com/LincZero/obsidian-any-block/issues/74

buttons、dataview、mindmap nextgen、and many other rendering-related plugins.

**Comment by LincZero** [comment]
A better demo

![image](https://github.com/user-attachments/assets/0e50a5d9-c35f-449c-a78b-1575802b8fc2)

**Comment by mProjectsCode** [comment]
Like I suspected, you are not correctly passing a component to the `render` function. Try something like this.

this.registerMarkdownCodeBlockProcessor("anyblock", ABReplacer_CodeBlock.processor);
```ts
export class ABReplacer_CodeBlock{
  static processor(
    src: string,
    blockEl: HTMLElement,
    ctx: MarkdownPostProcessorContext,
  ) {
    let dom_replaceEl = blockEl.createDiv({
      cls: ["ab-replaceEl"]
    });
    const mdrc = new MarkdownRenderChild(dom_replaceEl);
    ctx.addChild(mdrc); // you must register your mdrc to the context object. Otherwise stuff won't work correctly any will leak memory
    MarkdownRenderer.render(app, src, dom_replaceEl, app.workspace.activeLeaf?.view?.file.path, mdrc);
  }
}
```

**Comment by LincZero** [comment]
Yes, you are right. When I add ctx.addChild, everything goes back to normal.

I've done this in the past, but later removed it for compatibility when migrating to markdown-it (not sure what this step does at the time  T_T).

Thank you very much for your help.
