### ISSUE TITLE
Add more ways to add CSS classes into the DOM

### ISSUE THREAD

**Issue by holroy** [mProjectsCode/obsidian-meta-bind-plugin#43]
My first use of _Meta bind_ was to make a language selector for code blocks, which uses a select to choose which programming language to display. In order for this to work I utilised the `cssClass` frontmatter field, as it triggers a change in the DOM element which I then could use CSS to do my changes. However, my input field will overwrite any other values in `cssClass`, so it would be nice to have an alternative trigger. See [forum thread](https://forum.obsidian.md/t/code-blocks-for-code-snippets/49356/4?u=holroy) for my current use case, using `cssClass`.

## Add a `cssClass()` option

It would be nice, if one in addition to the `class()` option which only applies for the input field elements, had a `cssClass()` option which would insert a class into the DOM at the same level as the `cssClass` frontmatter field. 

This would both allow for other `cssClass` values to be preserved, and it would also allow for tagging the DOM in away which would allow for more custom CSS options to be handled. 

## Add a way to propagate the `option()` into a global class

In addition to the `cssClass()` would serve as the global flag, one would also need a way to propagate the `option()` value into the DOM, so maybe an additional parameter to that which would be the `cssClass` value for that option.

## Example of usage (based on my use case)

````md
```meta-bind
INPUT[select(cssClass(langSelector),
class(langField),
option(javascript, langJavascript),
option(python, langPython),
option(css, langCss)):chosenLanguage]
```
````

This would then _always_ add `langSelector` into the main DOM, and if the first option was selected, then it would _also_ add `langJavascript` into the DOM.

Then one could use CSS selectors like `.langSelector .langJavascript .language-javascript` to properly select code blocks in the javascript language, without changing the `cssClass` in the frontmatter for other uses, and still preserve the chosen language in the frontmatter field: `chosenLanguage`. (And still also be able to change this particular input field using the `.langField` selector.

**Comment by mProjectsCode** [comment]
this goes a bit above the scope of the plugin
