### ISSUE TITLE
AllowOther doesn't seem to work on inlineListSuggester

### ISSUE THREAD

**Issue by nirodaonline** [mProjectsCode/obsidian-meta-bind-plugin#430]
### Please fill out these Check-boxes

- [X] I checked for existing similar issues
- [X] I checked that the plugin is up to date

### Plugin Version

1.2.1

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Debug Info

```text
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Enterprise LTSC 2019 10.0.17763
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: Git v2.27.0
		2: Meta Bind v1.2.1
		3: Templater v2.8.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Describe the Issue

inlineListSelector with allowOther doesn't allow for new / other values.

### Steps to Reproduce

Examples:

```meta-bind
INPUT[ inlineListSuggester( option(option 1), option(option 2), option(option 3), allowOther(value: true) ) ]
```
```meta-bind
INPUT[ inlineListSuggester( option(option 1), option(option 2), option(option 3), allowOther ) ]
```
`INPUT[ inlineListSuggester( option(option 1), option(option 2), option(option 3), allowOther ) ]`

### Expected Behavior

I would expect to be able to add other values to the inlineListSuggester input.
Let me know if I'm doing anything wrong.

**Comment by mProjectsCode** [comment]
ah, there was a small typo in the code

**Comment by nirodaonline** [comment]
Thanks
