### ISSUE TITLE
Make buttons middle mouse clickable to open as a new tab

### ISSUE THREAD

**Issue by motion2082** [mProjectsCode/obsidian-meta-bind-plugin#436]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

Sort of

### Describe the Feature you'd like

You can left click the button but you can't middle mouse button to open it as a new tab or new note side by side

### Alternatives

Using a CSS Button

### Additional Context

None

**Comment by mProjectsCode** [comment]
Middle mouse button and modifier key support for buttons sounds like a good idea. Regarding middle mouse click, most button actions already support specifying a `newTab` option. Middle mouse click would simply override this to always be true.

**Comment by mProjectsCode** [comment]
Already implemented in the latest canary release. It will be in an official release Soon TM.
