### ISSUE TITLE
Formatting inline with the current theme...

### ISSUE THREAD

**Issue by melmaninga** [mProjectsCode/obsidian-meta-bind-plugin#44]
**Is your feature request related to a problem? Please describe.**
While the functionality of Meta-Bind is AWESOME and a potential game changer, I'm a noob about how to make a select code block appear in the same format as normal text in the minimal theme. Currently, it stands out like a sore thumb!

**Describe the solution you'd like**
Is there some kind of trick (css snippet, etc.) I could deploy that would allow for a select code block to "blend in" with the Minimal Theme?

**Comment by mProjectsCode** [comment]
Theme compatibility is more the responsibility of the theme than the plugin but I can look into this and see what I can do

**Comment by mProjectsCode** [comment]
![image](https://user-images.githubusercontent.com/61602848/209714729-10863b23-7772-44fc-a320-7a5c58c0717f.png)

I changed some stuff and now they look ok with minimal imo.

**Comment by mProjectsCode** [comment]
i am closing this, since there hasn't been a response for a week
