### ISSUE TITLE
Unclear on the use of `hidden` View Field Argument with arguments

### ISSUE THREAD

**Issue by Krustal** [mProjectsCode/obsidian-meta-bind-plugin#442]
### Page

https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/reference/viewfieldarguments/hidden/

### Issue or Enhancement

The basic usage of `hidden` is clear but I would expect, given the `hidden(value: true | false)` field documentation that we could do something like:

`VIEW[+1 for modifying effect][text(hidden({modifyEffect}))]`

And it would only show the field if the true/false property was `true`. This doesn't appear to be the case however. If you can only use `hidden` with true/false literals then I'm not clear on the use case.

**Comment by mProjectsCode** [comment]
> This doesn't appear to be the case however.

Correct.

> If you can only use hidden with true/false literals then I'm not clear on the use case.

The docs give a use case: "This can be useful if you want the view field to compute an intermediate value and write that value to the frontmatter."

**Comment by Krustal** [comment]
So in what case would you use:

```
VIEW[+1 for modifying effect][text(hidden(false))]
```

Is the fact you can pass a value just a side effect of the way the parser operates?
