### ISSUE TITLE
MB_INTERNAL_ERROR: Can not update metadata for input fields, received metadata is undefined

### ISSUE THREAD

**Issue by holroy** [mProjectsCode/obsidian-meta-bind-plugin#45]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
When typing in a note, I get this error message when looking in the console. I don't have any code related to _Meta bind_ running in this file.  I even tried with an empty note, and as long as the 'MetadataCacheChange' is triggered it appears.

**Condensed error message**
```
plugin:obsidian-meta-bind-plugin:10720 Error: [MB_INTERNAL_ERROR - please report this error here https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues] Can not update metadata for input fields, received metadata is undefined
    at MetaBindPlugin.updateMarkdownInputFieldsOnMetadataCacheChange (plugin:obsidian-meta-bind-plugin:10720:20)
    at eval (plugin:obsidian-meta-bind-plugin:10698:20)
    at t.e.tryTrigger (app.js:1:1045441)
    at t.e.trigger (app.js:1:1045374)
    at t.trigger (app.js:1:1132779)
    at t.<anonymous> (app.js:1:1129269)
    at app.js:1:235505
    at Object.next (app.js:1:235610)
    at a (app.js:1:234349)
```

**To Reproduce**

1. Close all files
2. Open a new note with _Developer Tools > Console_ open
3. Either just wait a few seconds, or type any character

**Expected behavior**
As long as I don't do any meta bind stuff, I expect it to be quiet, and not produce any error messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/11348165/209336832-b2fc41c5-d298-4393-bd00-3b0c27c1a5bb.png)

Shown when typing the three dashes to start a frontmatter section, but any characters works.

**Occurs on**

-   [ ] Windows
-   [x] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.3.3

**Additional context**
All other plugins are also **updated and disabled**, but the error still shows. For what it's worth this is a test vault with the following plugins installed: Admonition, Advanced Tables, Buttons, Copy Block Link, Dataview, Hider, Meta Bind Plugin, Minimal Theme Settings, Plaintext, Quick snippets and navigation, Templater.

**Comment by mProjectsCode** [comment]
Thanks for the report. 

This is already fixed in the update I am currently working on and which will hopefully still release this year.
