### ISSUE TITLE
Add example for Button action type "JS" and "args"

### ISSUE THREAD

**Issue by MathiasAugstein** [mProjectsCode/obsidian-meta-bind-plugin#452]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

I am struggling to pass arguments to an external JS function. `context.args` is always `undefined`, and I cannot find an example.

### Describe the Feature you'd like

In exampleVault -> Buttons -> "Button Example.md", please add an example how an external JS function can receive arguments using the `actions.args` property.

### Alternatives

In my case, I try to add a task with the title specified in an `input`. As I want to reuse the JS code I wrote it in a separate file. This use case might be popular among other people (use a button as "add" or "replace" of whatever is inserted in the `input`), so it might be worth writing an "Advanced Example".

But this would be second priority for me, clear example where people search it would be better.

**Comment by mProjectsCode** [comment]
I added an example to the docs, [here](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/reference/buttonactions/runjavascript/)

**Comment by MathiasAugstein** [comment]
Thank you
