### ISSUE TITLE
Have title for all input field types

### ISSUE THREAD

**Issue by MarceloCajueiro** [mProjectsCode/obsidian-meta-bind-plugin#46]
**Is your feature request related to a problem? Please describe.**
It would be great to have a standard title for every field, to maintain a pattern in the layout. I can do something similar with `[!INFO]`, but it has different style from the select.

**Describe the solution you'd like**
Allow title for every input field tyoe.

**Comment by mProjectsCode** [comment]
Will do, but not for inline input fields.

**Comment by mProjectsCode** [comment]
![image](https://user-images.githubusercontent.com/61602848/209714455-cfb5a78a-0523-46fe-be8a-f31c10def8b7.png)

The `title` argument can now be used for every input field and it will create a card around the input field, looking exactly like the select input field.

**Comment by MarceloCajueiro** [comment]
Great! Thanks a lot.

**Comment by MarceloCajueiro** [comment]
@mProjectsCode when are you going to release?

**Comment by mProjectsCode** [comment]
I am aiming for the 30th or early next year
