### ISSUE TITLE
Native integration with CustomJS

### ISSUE THREAD

**Issue by Devilofether** [mProjectsCode/obsidian-meta-bind-plugin#460]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

I have CustomJS installed, and I am unable to properly install JS Engine (or the installation is bugged) In the docs, the "run javascript file" only accepts JS engine, and is unable to recognize my files. This debug report was logged.
![Capture](https://github.com/user-attachments/assets/25578415-1427-4376-a514-5f36d62ca006)

### Describe the Feature you'd like

I would like to use CustomJS as the script engine as an option when using JavaScript with Meta Bind

### Alternatives

If there is already a way to do this; then please update the documentation to reflect it.

**Comment by mProjectsCode** [comment]
No. JS Engine will stay the only option for running JavaScript.
