### ISSUE TITLE
Option To Disable Button Tooltip

### ISSUE THREAD

**Issue by Graywaren** [mProjectsCode/obsidian-meta-bind-plugin#462]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

Tooltips are great, but I often find them redundant in my personal vault for most buttons. When the button is labeled "add x" and I don't need any further info, it just ends up annoying me, in the way, or looking weird when I just put a space in it. 

### Describe the Feature you'd like

I'd like to be able to disable the tooltip for buttons entirely. I think "tooltip: false" would work nicely.

### Additional Context

Thanks again for such an awesome plugin!

**Comment by mProjectsCode** [comment]
In the next release, the tooltip will now be hidden when none is specified.
