### ISSUE TITLE
please allow for inline embeds 

### ISSUE THREAD

**Issue by DryIce1** [mProjectsCode/obsidian-meta-bind-plugin#464]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

I want to put an embed within a callout. 
Thus it must be inline rather than a full code block. 

### Describe the Feature you'd like

Please can you allow embeds to be inline

e.g. 
`meta-bind-embed[[[Test file]]]`

**Comment by mProjectsCode** [comment]
You can put full code blocks in callouts

```
> [!info]
> 
> ```meta-bind-embed
> [[some link]]
> ```
```

**Comment by DryIce1** [comment]
Perfect! I had been thinking of many ways to approach this problem
from different embed/linking angles, but the problem didn't even exist
haha! Thanks for teaching me something simple but very useful! Consider
this issue closed.
