### ISSUE TITLE
Button YAML very sensitive

### ISSUE THREAD

**Issue by intellekta** [mProjectsCode/obsidian-meta-bind-plugin#467]
### Page

https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/

### Issue or Enhancement

i use 7 inline buttons on my home.md, when i edit it, not the button YAML part, sometimes i got

1. "Button ID not found"
then i set Hidden true and the error is gone
then i set Hidden false and its also okay
I can't reproduce this, it happens from one day to the next

2. META_BIND_ERROR
The indentation for type: and command: is very restrictive.
There must be 2 spaces, neither 1 nor 3 nor a TAB is accepted.
This could be a bit more relaxed to save newbies like me some time or it should be explicitly stated

**Comment by intellekta** [comment]
It may be wrong YAML, but it is not easy for the user to find.
Can you say why light mode throws an error and dark mode doesnt.
But don't say "its the dark side of the force" ;-)
![image](https://github.com/user-attachments/assets/f1d11524-ee5a-4a90-9226-da04b5360381)
![image](https://github.com/user-attachments/assets/6f760618-e70e-44f6-8dca-0ca5c98fff96)

**Comment by mProjectsCode** [comment]
> Can you say why light mode throws an error and dark mode doesn't.

Because tabs are not allowed as indentation in YAML. Maybe this website helps https://www.yamllint.com/

**Comment by intellekta** [comment]
I know but without "show whitespace" both blocks looks good and you can't see any differences.
