### ISSUE TITLE
Documentation refers to non-existent 'Open Meta Bind Playground' command

### ISSUE THREAD

**Issue by claremacrae** [mProjectsCode/obsidian-meta-bind-plugin#471]
### Page

https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/examples/

### Issue or Enhancement

It seems the command name is actually `Open Playground`:

![image](https://github.com/user-attachments/assets/2d4166f1-2182-416d-8524-5c9c4d458391)

**Comment by mProjectsCode** [comment]
Ah, thanks. It seems like I renamed the command to comply with the plugin guidelines but forgot to update the docs.
