### ISSUE TITLE
Asking to fill it when creating the note

### ISSUE THREAD

**Issue by Dopairym** [mProjectsCode/obsidian-meta-bind-plugin#486]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [x] My feature request consists of only one feature

### Describe the Feature you'd like

It would be great if we could use those image select or the time select , slider and others when making a new note so the are like a pop out window thst asks you to like choose image or any other thing and thrn the note will get made with those thigns i chose

**Comment by mProjectsCode** [comment]
That goes beyond the scope of this plugin.
