### ISSUE TITLE
Drop Down / Inline Select

### ISSUE THREAD

**Issue by mikebarkmin** [mProjectsCode/obsidian-meta-bind-plugin#51]
I think this plugin is a great addition to Obsidian. But I need inline selects, therefore I propose a new input type `drop_down` or `inline_select`. Or even better is the select is detected as inline it should render like the example below.

The input type should be using the html element `select` and `option` see https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Comment by mProjectsCode** [comment]
There already was a FR for this which I closed in because of the suggested input field, which is an inline select but with added keyboard accessibility.
#13

**Comment by mProjectsCode** [comment]
https://github.com/users/mProjectsCode/projects/3/views/1?pane=issue&itemId=29730871
