### ISSUE TITLE
Nested fields should not throw an error if the parent is missing, but create it

### ISSUE THREAD

**Issue by mikebarkmin** [mProjectsCode/obsidian-meta-bind-plugin#52]
Nested fields should not throw an error if the parent is missing, but create it.

# Example

This example currently creates an error.

````
---
people:
---
```meta-bind
INPUT[select(
option(excused),
option(absent),
option(present)
):people["carlo"]["presence"]]
```
````

**Comment by mProjectsCode** [comment]
added in https://github.com/mProjectsCode/obsidian-meta-bind-plugin/commit/d13865d61a3cc1630596ee65601f4b30dfa8b83e and https://github.com/mProjectsCode/obsidian-meta-bind-plugin/commit/dc7dac0d0d270206da63fb181f4f216e6b4e9cb3
