### ISSUE TITLE
Changing fields on Android version does not update metadata fields

### ISSUE THREAD

**Issue by ironman820** [mProjectsCode/obsidian-meta-bind-plugin#55]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**

Changing any meta-bind field in the Obsidian Android reading view produces errors and does not edit or change metadata. The same page and vault are working fine on Linux. I have tested both inline and full meta-bind code blocks with the same result and have produced the error with toggles and text fields so far.

Concise error message produced in the console:  
```
Uncaught (in promise) TypeError: this.plugin.app.fileManager.processFrontMatter is not a function
    at ei.updateFrontmatter (plugin:obsidian-meta-bind-plugin:31:57854)
    at ei.update (plugin:obsidian-meta-bind-plugin:31:57644)
    at eval (plugin:obsidian-meta-bind-plugin:31:56541)
updateFrontmatter @ plugin:obsidian-meta-bind-plugin:31
update @ plugin:obsidian-meta-bind-plugin:31
eval @ plugin:obsidian-meta-bind-plugin:31
```

**To Reproduce**

1. Open or create a page with a meta-bind element.
2. Switch to the reading view.
3. Attempt to change any meta-bind field. (focusing on text boxes does not start the problem, but any input after focus does)

**Expected behavior**

Meta Bind updates the referenced metadata tag.

**Occurs on**

-   [ ] Windows
-   [ ] macOS
-   [ ] Linux
-   [x] Android (v1.4.1 (83) - API v1.0.3)
-   [ ] iOS

**Plugin version**
0.4.0

**Comment by mProjectsCode** [comment]
https://github.com/mProjectsCode/obsidian-meta-bind-plugin/discussions/53

Already answered here
