### ISSUE TITLE
Plugin changing metadata fields its not 'bound' to

### ISSUE THREAD

**Issue by spasticginger** [mProjectsCode/obsidian-meta-bind-plugin#56]
-   [ x ] The Plugin is up to date - Meta-Bind 0.4.0
-   [ X ] Obsidian is up to date - Desktop 1.1.9,  Mobile 1.4.1

**Describe the bug**
When any Meta-bind Inputs are added to a page, the plugin is changing the formatting of existing frontmatter, such as codes for the core Templates plugin, that it isn't 'bound' to, and happens with both inline & code blocks.  Removing the Input code does not fix the problem.  Even if the existing frontmatter is corrected, it will still be automatically reformatted even without any inputs on the page anymore.  This does not occur on pages where Inputs have never been added, or if the inputs have never been activated.
**To Reproduce**

1. Create new note with one pre-filled in metadata field (such as {{date:MM}} ), & one blank one to bind to.
2. Toggle between reading & editing modes a couple times to ensure it's not changing on its own
3. Add any inputs
4. Switch back to reading & activate toggle, adjust the slider, etc. once.  (Does not occur if not activated)
5. Switch back to editing mode to see reformatted metadata

**Expected behavior**
For plugin to not reformat pre-filled metadata that it isn't 'bound' to.
(I do realize there's other issues with text fields clearing metadata, this seems independent of that)

**Screenshots**

![Before](https://user-images.githubusercontent.com/22240867/213442226-c8acb023-eb87-4898-9cf7-60c9d2d5c0d6.JPG)

![After](https://user-images.githubusercontent.com/22240867/213442247-0fcbc9ce-0ef4-48ed-b099-39b7f99a7a56.JPG)

**Occurs on**

-   [ X ] Windows
-   [ ? ] macOS
-   [ ? ] Linux
-   [ ] Android - No - Frontmatter can be corrected on a note even with an active Input.  It will not reformat until the note is loaded again on PC since the Inputs do not work yet on mobile.  (I do NOT have the Insider build)
-   [ ] iOS - No - Same behavior as Android

**Plugin version**
0.4.0

**Additional context**
n/a

**Comment by mProjectsCode** [comment]
> (I do realize there's other issues with text fields clearing metadata, this seems independent of that)

Those are fixed AFAIK

> Month: {{date:MM}}

This is not valid YAML. As such obsidian metadata API might do unexpected things

`Month: "{{date:MM}}"` 

Will work without any issues.

**Comment by mProjectsCode** [comment]
> This is not valid YAML.

Small correction, `Month: {{date:MM}}` is actually kind of valid YAML. 
`{{date:MM}}` is interpreted as an object with `{date:MM}` as a key and no value. 
Thus, what obsidian does is correct.
```yaml
Month: 
    "{date:MM}": null
```

**Comment by mProjectsCode** [comment]
As to why the plugin changes metadata it is not bound to, that is just how obsidians metadata API works.

**Comment by spasticginger** [comment]
> > This is not valid YAML.
> 
> Small correction, `Month: {{date:MM}}` is actually kind of valid YAML. `{{date:MM}}` is interpreted as an object with `{date:MM}` as a key and no value. Thus, what obsidian does is correct.
> 
> ```yaml
> Month: 
>     "{date:MM}": null
> ```

The problem is that the core Templates feature doesn't recognize it anymore as a key:value pair.  It seems like it has to stay an object with the double curly brackets for the Templates to do what it does.  Adding the quotes keeps it as an object, but the quotes stay on the outputted value, which doesn't match up to dates from other notes without inputs & causes problems with the Dataview query.

Seems weird the new metadata API isn't leaving the core Templates objects alone, but my programming knowledge is non-existent, so I honestly don't know how any of it really works!  

As a workaround I should be able to stick the Templates fields as inline at the bottom of the note in a collapsed call-out.

**Comment by mProjectsCode** [comment]
I guess the obsidian template syntax was not designed to be used inside of frontmatter. 

I am going to close this issue, as it is problem with the core templates and not meta-bind.
