### ISSUE TITLE
Plugin not working on mobile

### ISSUE THREAD

**Issue by dxcore35** [mProjectsCode/obsidian-meta-bind-plugin#58]
-   [X] The Plugin is up to date
-   [X] Obsidian is up to date

**Describe the bug**

Toogle is not changling status of YAML field in mobile app. On desktop all works!

**Occurs on**

-   [ ] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [X] iOS

**Plugin version**
0.4

**Comment by mProjectsCode** [comment]
Already answered here
https://github.com/mProjectsCode/obsidian-meta-bind-plugin/discussions/53
