### ISSUE TITLE
Add inputs as inline block instead of multiline block

### ISSUE THREAD

**Issue by Shoggomo** [mProjectsCode/obsidian-meta-bind-plugin#59]
**Is your feature request related to a problem? Please describe.**
Currently, input fields can only be added via multiline code blocks. This way, inputs cannot be added to table cells, as these don't support multiple lines.

**Describe the solution you'd like**
A possible solution is to enable adding inputs via inline blocks with a "mb" prefix. These could look like this: 
```
`mb INPUT[number:amount]`
```

So these two would be equivalent:
```
`mb INPUT[number:amount]`
```

```
```meta-bind
INPUT[number:amount]
` ``
```
(^ Ignore the space in the last line. It wouldn't render properly otherweise.)

**Comment by Shoggomo** [comment]
[Here ](https://github.com/blacksmithgu/obsidian-dataview/blob/master/src/main.ts#L179)can be seen how dataviewjs handles this.

**Comment by mProjectsCode** [comment]
> `mb INPUT[number:amount]`

If you remove the `mb` from it, this should work in reading mode

**Comment by Shoggomo** [comment]
Yes, it does! Very cool, I couldn't find anything about this in the docs. Did I miss it, or should it be added?

**Comment by mProjectsCode** [comment]
> Did I miss it, or should it be added?

It seems like I forgot to add it to the docs.

**Comment by mProjectsCode** [comment]
retired in favor of #68
