### ISSUE TITLE
Provide an option to ignore a specific yaml key(s)

### ISSUE THREAD

**Issue by erauner12** [mProjectsCode/obsidian-meta-bind-plugin#60]
Problem I have is that I have specific automation that relies on `tags` to be single line. And my linter changes it back to single line upon saving. Meta-bind change it to multi-line causing a conflict.

I tried to attempt to use multi-line via linter settings but the automation I rely on has no way of updating the tag in a way fits the multi-line way.

I was wondering if you could introduce a way to ignore a specific yaml key from settings such as `tags`.

Thanks for your consideration!

**Comment by erauner12** [comment]
I suppose an additional way to go about it could also be to provide an option to maintain single-line values instead of enforcing multi-line. Would either of these be a trivial change?

**Comment by mProjectsCode** [comment]
Meta-bind uses the metadata API obsidian provides. This means that meta-bind has no influence when it comes to the format of the front matter. That is all done by obsidian. 
You will need to open a FR to obsidian if you want a different format of the frontmatter/meta data.

**Comment by erauner12** [comment]
Great thank you! Will work on this!

**Comment by erauner12** [comment]
Just wanted to say for anyone else who might find this and having conflict with metaedit. I was able to solve my dataviewjs script problem with `update` by switching to metadata menu `getValues` and `postValues`!

reference:

specifically with the following:  
[https://github.com/mdelobelle/metadatamenu/blob/master/docs/api.md#getvalues](https://github.com/mdelobelle/metadatamenu/blob/master/docs/api.md#getvalues)

[https://github.com/mdelobelle/metadatamenu/blob/master/docs/api.md#postvalues](https://github.com/mdelobelle/metadatamenu/blob/master/docs/api.md#postvalues)

old:

https://github.com/chhoumann/MetaEdit#updatepropertyname-string-propertyvalue-string-file-tfile--string
