### ISSUE TITLE
(question) Is the API accessible yet from dataviewjs?

### ISSUE THREAD

**Issue by erauner12** [mProjectsCode/obsidian-meta-bind-plugin#61]
I was looking at the [following commit](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/commit/7179ba1a53e70f91cc146f10c73fc1347213c6bd). Trying to understand how to access this API to test it out.

Could you point me in the right direction?

```
class Test {
    async testMetadataBindApi(container) {
        const { mb } = app.plugins.plugins["obsidian-meta-bind-plugin"].api;
        console.log(mb)
    }
}
```

```
Evaluation Error: TypeError: Cannot destructure property 'mb' of 'app.plugins.plugins.obsidian-meta-bind-plugin.api' as it is undefined.
```

comparing to metadata menu for context:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/59383957/218854844-91d6ecc3-77c7-4055-8cab-abe4fd1bb436.png">

<img width="281" alt="image" src="https://user-images.githubusercontent.com/59383957/218854887-5f64ca02-39bf-4e9a-b68c-0469b3dae16d.png">

thanks in advance 🙂

**Comment by mProjectsCode** [comment]
I am currently taking a break to concentrate on my exams, but if I remember correctly the API has not yet been released.
