### ISSUE TITLE
Why it is showing the query with render

### ISSUE THREAD

**Issue by Gourav1910** [mProjectsCode/obsidian-meta-bind-plugin#64]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
After writing our codeblock/query it is also rendering the query with the desired render. I have also attached the screenshot. 

**Expected behavior**
Is there a way to hide that? I want a clean render for example only slider and not the query below the slider.

**Screenshots**

This is the rendered screenshot.
![image](https://user-images.githubusercontent.com/101202140/223560202-063b339f-ea9f-4ff4-8f56-f2fac9823dfd.png)

And this is what it looks like in source mode.
![image](https://user-images.githubusercontent.com/101202140/223561024-f2399f75-110d-4dad-b9c6-2366a2fac3b0.png)

**Occurs on**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.4.0

**Comment by mProjectsCode** [comment]
Remove the `showcase` argument

**Comment by Gourav1910** [comment]
> Remove the `showcase` argument

ohk thanks. I wonder why this plugin is still not available in obsidian community plugin tab. Is there any plan?

**Comment by Gourav1910** [comment]
> Remove the `showcase` argument
Hi thanks for the solution. I have one more question, as I am showing in this screen recorded video, I did a dataview query with tag #metabind and also I asked it to render the slider and toggle but as I am clicking on toggle or moving slider it is nothing doing in original files but it is doing it for the same file in which the query is existing and also the queried result showing two results but both results toggle and slider are like behaving as a single unit which is only affecting the same file's metadata which also created automatically after i did the query. So do you have any fix to this problem so that when i do something in query with metabind elements then it only affect the metadata of original file and not the file in which it is queried.

https://user-images.githubusercontent.com/101202140/223587762-7f0464dd-f527-40d7-959e-b39324564441.mp4

**Comment by mProjectsCode** [comment]
You can fix this by specifying the file path in the bind target of the input field like described here https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/tutorial#binding_to_metadata

**Comment by Gourav1910** [comment]
> You can fix this by specifying the file path in the bind target of the input field like described here https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/tutorial#binding_to_metadata

Ok thankuu it worked😊😊
