### ISSUE TITLE
How do I bind the inputs to the transcluding parent file's front matter?

### ISSUE THREAD

**Issue by opyh** [mProjectsCode/obsidian-meta-bind-plugin#66]
I want to include a meta-bind-based form into a file, but want the form to be bound to the front matter variables of the file that **includes** the form file.

Is it possible to bind form inputs to the parent's front matter?

**Comment by opyh** [comment]
Yep, exactly! I would like to use the context's parent/top parent `B` for binding instead of the embedded file `A`.

This would enable me to create DRY, reusable forms that I can embed, e.g. in my daily journal files.

**Comment by mProjectsCode** [comment]
That is not currently possible and I don't know if that can be done using obsidians API, but I will see what I can do.

**Comment by terrychenzw** [comment]
there is a perfect solution for this case——[Obsidian dynbedded](https://github.com/MMoMM-org/obsidian-dynbedded)

😀😀

![dynbedded](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/114856910/22994f34-cc56-4f25-a72c-2396580dbbec)

**Comment by mProjectsCode** [comment]
I haven't found a way to do this with the obsidian API.
The comment above shows a good workaround though.
