### ISSUE TITLE
range input : option for different track colour + output value

### ISSUE THREAD

**Issue by liiyung** [mProjectsCode/obsidian-meta-bind-plugin#70]
At the moment, I'm not able to see clearly what value the slider is currently at. I think having :
1) the option for a different colour along the slider track, and
2) having the option to view the output value right next to/on the slider

would be very useful to combat this, without having to refer to frontmatter metadata just to check the values.

Additional justification : I think adding these features in would likely make people switch to this plugin for more interactive progress bar type visualizations. At the moment, there are no interactive progress bars yet (all depend on manually typing the values and using dataview), and I believe this plugin is in the best position to remedy that. 

=====**Additional context**=====
[Codepen demo](https://codepen.io/liiyung/pen/mdzyJMX) of what I would like to achieve.

**Comment by mProjectsCode** [comment]
Different colors can be achieved using CSS I believe. 
Currently, the plugin is using obsidians build-in slider component. To show the current value like in the codepen demo, I would need to write my own slider component, which i might do as a separate input field type.

**Comment by liiyung** [comment]
Yes, actually the reason I suggested the tracker colours is because it seems to be non-trivial and requires javascript; there isn't a specific tracker/thumb name to reference in the css for the default slider. As such, most themes also don't have a coloured tracker bar.

Having said that, I did play around and manage to get the main style working (point 1) with pure css!  [Here](https://imgur.com/a/cSPC7DI) is a demonstration gif of it. 

For anyone interested : to get just the tracker colour itself working, you can start from something like 
`
@media screen and (-webkit-min-device-pixel-ratio: 0) {
  input[type="range"] {
    overflow: hidden;
    width: 80px;
    -webkit-appearance: none;
    background-color: var(--secondary);
  }

  .meta-bind-plugin-slider-input[type="range"]::-webkit-slider-thumb,
  .meta-bind-plugin-slider-input[type="range"]:hover::-webkit-slider-thumb {
    width: 1px;
    border-radius: 0;
    -webkit-appearance: none;
    height: 45px;
    margin-top: -11px;
    background: #43e5f7;
    box-shadow: -98px 0 0 98px #43e5f7;
  }`

and then style .meta-bind-plugin-slider-input[type="range"] accordingly. 

In any case, I've found this so much more intuitive to work with for progress-tracking with dataview (as compared to arbitrary string arguments like "completed", "in progress", etc.), so thank you very much for working on this plugin :D

**Comment by mProjectsCode** [comment]
Released in 0.5.0
