### ISSUE TITLE
The file containing the form control with the meta-bind-plugin plugin cannot be opened.

### ISSUE THREAD

**Issue by ribber** [mProjectsCode/obsidian-meta-bind-plugin#71]
## Describe the bug

PC

![图片](https://user-images.githubusercontent.com/5986011/231741857-8debb69d-154c-420f-a6c1-3795b3fdff84.png)

Android

![图片](https://user-images.githubusercontent.com/5986011/231741787-4b349339-7696-484d-b39a-30a566037343.png)

## Device info (please complete the following information):
- API version 1.1.16
- Android 12

**Comment by mProjectsCode** [comment]
I can't reproduce the issue with my Android 11 phone with plugin version 0.4.0, obsidian version 1.4.3(95), and API version 1.1.16.

Also please use the bug report issue template next time
