### ISSUE TITLE
Q: How to use this with a Dataview table?

### ISSUE THREAD

**Issue by replete** [mProjectsCode/obsidian-meta-bind-plugin#73]
First of all, thank you for making such a useful plugin - this functionality should be core functionality IMO. Bravo.

I read somewhere - in your docs I believe - that you can use meta-bind with Dataview Tables. I looked through the repo and example vault but could not find an example. 

Do you have any examples to share on this? I've had a look through the dataview docs but couldn't quite see how it fits in..

Kind Regards,

Phil

**Comment by mProjectsCode** [comment]
```dataview
TABLE task AS "Task", "`INPUT[toggle:" + file.name + "#completed]`" AS Completed FROM #task
SORT file.name ASC
```

this is one example that I made a while back. I hope it helps
