### ISSUE TITLE
MB_PARSING_ERROR when using suggester/suggestOption

### ISSUE THREAD

**Issue by melmaninga** [mProjectsCode/obsidian-meta-bind-plugin#78]
-   [ X ] The Plugin is up to date
-   [ X ] Obsidian is up to date

**Describe the bug**
When using the suggested options, I get an error message
[MB_PARSING_ERROR] unknown argument 'Tool1Tool2Tool3#test'

**To Reproduce**
The following in a code block
```meta-bind
INPUT[suggester(suggestOption(Tool1),suggestOption(Tool2),suggestOption(Tool3),suggestOptionQuery(#test):suggester1]
```

**Expected behavior**
A menu should appear where I get to choose Too1, Tool2, or Tool3

**Screenshots**

**Occurs on**
-   [? ] Windows
-   [X] macOS
-   [ ?] Linux
-   [ ?] Android
-   [ ?] iOS

**Plugin version**
0.4.3

**Additional context**

**Comment by mProjectsCode** [comment]
You are missing a parenthesis. Try this

`INPUT[suggester(suggestOption(Tool1),suggestOption(Tool2),suggestOption(Tool3),suggestOptionQuery(#test)):suggester1]`

**Comment by melmaninga** [comment]
Thanks @mProjectsCode.

I tried that but to no avail; I still got the error of "MB_PARSING_ERROR] unknown argument 'suggestOption'"

BUT the following works:

INPUT[suggester(option(Tool1),option(Tool2),option(Tool3),optionQuery(#test)):suggester1]

I dunno why, I'm a noob with this.

**Comment by mProjectsCode** [comment]
https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/arguments#option

Because `option` is the correct argument. `suggestOption` does not exist.
