### ISSUE TITLE
Multi-Column Markdown plugin support

### ISSUE THREAD

**Issue by Marco-ITH** [mProjectsCode/obsidian-meta-bind-plugin#79]
**Is your feature request related to a problem? Please describe.**
I use Multi-Column Markdown plugin in some template for a "better look". I've tried to use it with Meta Bind and it seems not working. Everytime I fill a field that is binded to a metadata field, it doesn't update it and if I change note and come back, I lose all the data.

**Describe the solution you'd like**
I just would like to use Meta Bind plugin inside the Multi-Column Markdown plugin syntax.

**Additional context**
This is a screenshot of the syntax WITH Multi-Column Markdown plugin (this DOESN'T work):

![immagine](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/112725579/e8844e80-f3ac-47c9-bba0-fdc1f06ed08c)

This is a screenshot of the syntax WITHOUT Multi-Column Markdown plugin (this WORK):

![immagine](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/112725579/02ce7123-521b-4768-9ea4-d218e8ca7ef3)

**Comment by mProjectsCode** [comment]
The columns plugin seems to mess with the event listeners on the input fields. There is nothing I can do. This is a problem with the columns plugin doing some janky stuff incorrectly.
