### ISSUE TITLE
Other types of input

### ISSUE THREAD

**Issue by imeed166** [mProjectsCode/obsidian-meta-bind-plugin#8]
**Is your feature request related to a problem? Please describe.**
As I'm planning to use this plugin with dataview, would it be possible to have additional types of input just like what is available in notion ?

**Describe the solution you'd like**
The most important ones that are missing for me :
1. Select
2. Multi-select
3. Date
4. Time

**Comment by mProjectsCode** [comment]
Yes I am planning to support more input field types.

**Comment by mProjectsCode** [comment]
The first version of select and multi-select input fields are available in the latest version.

![image](https://user-images.githubusercontent.com/61602848/175074177-3e021fdb-ebb2-41c7-af29-bd966a4b487c.png)
![image](https://user-images.githubusercontent.com/61602848/175074225-7cf31b83-503d-4e82-8fce-b8bfc60b947d.png)

**Comment by mProjectsCode** [comment]
It is not included in the latest release, but in the latest commit, so if you want to test it now you need to clone the repo and build the plugin yourself (`npm install` then `npm run dev`)
