### ISSUE TITLE
Nested metadata not binding

### ISSUE THREAD

**Issue by henriklynggaard** [mProjectsCode/obsidian-meta-bind-plugin#80]
I cannot get the plugin to bind to nested metadata

```
---
test: false
habit:
  - sleep: 3
---

This works: `INPUT[toggle:test]`
This does not: `INPUT[number:habit.sleep]`
```
I have also tried the code block version but same result

**Comment by mProjectsCode** [comment]
Please use the bug report template next time.

**Comment by mProjectsCode** [comment]
This is a discrepancy between your yaml and the way you are binding to it. In your case `habit` is an array with one element - an object that has the property `sleep`. But you are binding to the key `sleep` in the  object named `habit`.

Either do this:

```md
---
test: false
habit:
    sleep: 3
---

This works: `INPUT[toggle:test]`
This does not: `INPUT[number:habit.sleep]`
```

or this:


```md
---
test: false
habit:
  - sleep: 3
---

This works: `INPUT[toggle:test]`
This does not: `INPUT[number:habit[0].sleep]`
```

**Comment by henriklynggaard** [comment]
Yeah, I realised that this morning :-( Sorry had a newbie moment there

**Comment by mProjectsCode** [comment]
All good, it happens to everyone sometimes xD
