### ISSUE TITLE
Exclude Folder

### ISSUE THREAD

**Issue by Civilianpig** [mProjectsCode/obsidian-meta-bind-plugin#81]
I am trying to write collections of meta-binds into a template note for repeated use, but the plugin is obviously always trying to add fields to the YAML of the template file, which then contaminates the target files. Is there any way to exclude whole folders from the plugin?

**Comment by mProjectsCode** [comment]
Finally got around to it. 

You can specify them in the settings.
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/61602848/e1c7c1f2-2668-4b0f-b043-2a945e0c7bb4)

And a note in an excluded folder looks like this
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/61602848/109ab806-0d6a-444e-a8db-52c85c9f9795)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/61602848/6f70133d-a010-4ee3-954e-44850da8970a)

**Comment by mProjectsCode** [comment]
This will be part of the next release
