### ISSUE TITLE
MB inserts "null" when I am typing new frontmatter

### ISSUE THREAD

**Issue by ScottKillen** [mProjectsCode/obsidian-meta-bind-plugin#86]
-   [x] The Plugin is up to date
-   [X] Obsidian is up to date

**Describe the bug**
If I have a note with meta-bind fields and frontmatter aliases in this form:
```
aliases:
  - alias1
  - alias2
```

When I try to add alias three, meta-bind inserts 'null' after I type the '-' and fouls up the typing of the new alias

**To Reproduce**

1. Create a note
2. Add frontmatter as aboe.
3. Add a metabind date field inside of a callout:
    ```
    > [!info]
    > Date of Birth: `INPUT[date:TP_dob]`
    ```
5. Try to add a new alias.

**Expected behavior**
Meta bind should not mess with frontmatter unless I have updated a metabind fie;d/

**Occurs on**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.4.3

**Comment by mProjectsCode** [comment]
Fixed, hopefully
