### ISSUE TITLE
custom values for toggle

### ISSUE THREAD

**Issue by henriklynggaard** [mProjectsCode/obsidian-meta-bind-plugin#87]
**Is your feature request related to a problem? Please describe.**
I have been trying to use the toggle input for some of my habit tracking where the answer is only yes/no. However the Trackr plugin which I use for a calendar view of my habits only supports numerical values not boolean true/false. Hence it does not detect it when I switch the toggle

**Describe the solution you'd like**
It would be great if I could configure the toggle to use 0 & 1 instead of boolean because I could then configure 1 as the numeric threshold in Trackr plugin. 

Perhaps extend to allowing the user to specify values e.g. trueValue(),falseValue() 
 
**Additional context**
One could argue that Trackr plugin should support boolean values, but it doesn't look like it is being actively developed

My current workaround is to configure a slider with min=0 and max=1 but that takes up more screen real estate

**Comment by mProjectsCode** [comment]
implemented. The arguments are `onValue` and `offValue`.
