### ISSUE TITLE
No Teamworking together with Modular CSS Layout - Multi Column

### ISSUE THREAD

**Issue by macmorri** [mProjectsCode/obsidian-meta-bind-plugin#88]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
I truly hesitated to call this a bug cause I am quite unsure whom to address - Meta Bind or Modular CSS Layout or even me. :) Whatever I have to start somewhere.
It's not possible to get Meta Bind working inside a column of a multi column note. Inputs are shown but cannot be clicked. Codeblocks are somewhat working but mostly you have to click twice or more to get a response from the input field (no matter which to choose).

**To Reproduce**

1. Create a multi column area with using Modular CSS Layout - Multi Column
2. Fill in whether inline meta bind input or meta bind codeblock
3. Try to use

**Expected behavior**
I expected to see working and clickable input fields. ^^

**Screenshots**

**Occurs on**

-   [ ] Windows
-   [x] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.4.3

**Additional context**
Maybe it's just some css stuff we need to change - maybe it's just me being too blah ... :)

**Comment by mProjectsCode** [comment]
i took the liberty to transfer it to the correct repo

**Comment by mProjectsCode** [comment]
and now i can point you here to this issue https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues/79

**Comment by macmorri** [comment]
Thank you very much and take my sorry for misaddressing. :)

**Comment by mProjectsCode** [comment]
my tip is to use a theme or snippet with multi-column support through callouts. All those multi-column plugins that change the document flow seem to break other plugins in all kind of strange ways.
