### ISSUE TITLE
Using inline INPUT clobbers value of parent in frontmatter

### ISSUE THREAD

**Issue by cjam** [mProjectsCode/obsidian-meta-bind-plugin#90]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
I was trying to create a template for my daily note that would have a form at the top of the note for my habits to track and various other items.  My frontmatter also defines a relationship `parent: [[journal]]` to be able to leverage the breadcrumbs plugin.

**To Reproduce**

1. Create a new note
2. Paste the following into the contents:

```md
---
parent: [[journal]]
tags: journal/daily
test: false
---
# {{date:dddd MMMM DD, YYYY}}

| test                       |     |
| -------------------------- | --- |
| `INPUT[toggle:test]` |     |
```

4. Allow the table to render
5. Click toggle, notice what happens to the parent property, mine becomes:
```
parent:
  - - journal
```
  

**Expected behavior**
Expect this plugin to only touch fields that it has been bound to.

**Screenshots**

https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/1000288/472dbade-f1f4-4693-af55-f922324350d4

**Occurs on**

-   [ ] Windows
-   [x] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.4.3

**Comment by mProjectsCode** [comment]
This works as intended. Obsidians frontmatter API detects the `[[...]]`, as the YAML standard defines, as an array within an array and updates it to the preferred way to represent an array. If you want it to keep it as a "link", you need to wrap it in quotation marks like this `"[[...]]"`.

**Comment by cjam** [comment]
ah ok, i'll give that a try thanks

**Comment by mProjectsCode** [comment]
Note, that because of this, obsidian does not support links in the fontmatter.
