### ISSUE TITLE
Syntax error in Meta Bind Docs

### ISSUE THREAD

**Issue by Amir1453** [mProjectsCode/obsidian-meta-bind-plugin#91]
Hello, noticed a syntax error in Meta Bind Docs. 

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/63464110/d8225329-bdaa-4a81-be8b-dde64df982a1)

The line is lacking a closing paranthesis:

```sh
INPUT[slider(minValue(0), maxValue(10)):bind_target]
```

Link is [here](https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/arguments#minmaxValue)

**Comment by mProjectsCode** [comment]
thanks, i will fix this when i am updating the docs for version 0.5.0

**Comment by Amir1453** [comment]
Also, pressing "Showcase Argument"

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/63464110/de5f26ae-445a-40a7-a658-a4f5295bd4a7)

Shows the page for "Align Right Argument". (https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/arguments#alignRight)

**Comment by mProjectsCode** [comment]
i will upload the fixed version when I release the new plugin version
