### ISSUE TITLE
a "defaultValue" argument

### ISSUE THREAD

**Issue by thecookiemomma** [mProjectsCode/obsidian-meta-bind-plugin#93]
**Is your feature request related to a problem? Please describe.** 
I use sliders and clickers in my daily notes to mark different information.  Sliders start at the beginning, and toggles start "false."  

**Describe the solution you'd like**
I would like there to be the possibility of a default value, especially with sliders, it would be nice to be able to set a default value... like for my "mood" slider, have it set at 3/5 unless I move it. 

Thank you for consideration.

**Comment by mProjectsCode** [comment]
Will be part of the next release
