### ISSUE TITLE
meta-bind-js for all objects

### ISSUE THREAD

**Issue by dxcore35** [mProjectsCode/obsidian-meta-bind-plugin#97]
For example I would like to build progressbar where on left side will be title, all in one line. Now it is not possible to do it

**Comment by dxcore35** [comment]
Allowed in: code block and inline code block.

What I asked is to make ALL OBJECTS (in my case progressbar) to be able to insert is as inline field.

**Comment by mProjectsCode** [comment]
there is already an option for it in the settings

**Comment by dxcore35** [comment]
Then documentation is not updated?

![Screenshot 2023-06-21 at 20 59 31](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/7279156/3fd853aa-9be8-4ccd-9dcb-a9f1ff8e1b94)

**Comment by mProjectsCode** [comment]
It is. But for those that want it, there is a setting in the plugin's settings page to disable the code block / inline code block check. 
This setting is not enabled by default because the input fields are not designed to be used outside of their allowed code block type.
